-- ============================================================
-- GeraFicha — Módulo 4: Sintaxe e Análise
-- Níveis 73–84 | Séries A e B
-- ============================================================

-- Nível 73A — Frase, oração e período
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 73, 'A', 'MC', 'O que é uma FRASE?', '["Conjunto de palavras com verbo","Enunciado com sentido completo, com ou sem verbo","Grupo de palavras sem sentido","Conjunto de orações"]', 'Enunciado com sentido completo, com ou sem verbo', 'Frase é qualquer enunciado com sentido, com ou sem verbo: "Silêncio!" / "O menino correu."'),
('sintaxe', 73, 'A', 'CL', 'Classifique em Frase (F) ou Oração (O): "Que dia lindo!" / "A chuva caiu." / "Silêncio!" / "Ela estuda."', '[]', 'F — O — F — O', 'Oração tem verbo; frase pode ser com ou sem verbo. Exemplos sem verbo são apenas frases.'),
('sintaxe', 73, 'A', 'VF', '"Período" é a frase formada por uma ou mais orações.', '[]', 'Verdadeiro', 'Período simples = uma oração. Período composto = duas ou mais orações.'),
('sintaxe', 73, 'A', 'RF', 'Identifique o número de orações em cada período: "O aluno estudou." / "Ela acordou, se vestiu e saiu." / "Espero que venhas logo."', '[]', '1 oração / 3 orações / 2 orações', 'Cada verbo geralmente corresponde a uma oração.'),
('sintaxe', 73, 'A', 'MC', '"A menina cantou e dançou." É um período:', '["simples com 1 oração","composto com 2 orações","composto com 3 orações","frase sem sentido"]', 'composto com 2 orações', 'Cantou e dançou = dois verbos = duas orações → período composto.'),
('sintaxe', 73, 'A', 'DS', 'Escreva: 1 frase sem verbo, 1 período simples e 1 período composto.', '[]', 'Sem verbo: Que silêncio! / Simples: Ela correu. / Composto: Ela correu porque estava atrasada.', 'Identificar a estrutura dos enunciados é o primeiro passo da análise sintática.'),
('sintaxe', 73, 'A', 'VF', 'Uma oração é sempre um período, mas um período não é sempre uma única oração.', '[]', 'Verdadeiro', 'Uma oração pode formar um período simples, ou um período pode ter várias orações.'),
('sintaxe', 73, 'A', 'CL', 'Quantas orações há em cada período? "Ele dormiu." / "Choveu e ventou muito." / "Sei que você virá."', '[]', '1 / 2 / 2', 'Cada verbo corresponde a uma oração.'),
('sintaxe', 73, 'A', 'MC', '"Silêncio!" é uma:', '["oração","frase sem verbo","oração sem sujeito","período composto"]', 'frase sem verbo', '"Silêncio!" tem sentido completo mas não tem verbo — é frase nominal.'),
('sintaxe', 73, 'A', 'DS', 'Explique a diferença entre período simples e composto com exemplos.', '[]', 'Simples: "Ela estudou muito." (1 oração, 1 verbo) / Composto: "Ela estudou muito porque queria passar." (2 orações, 2 verbos)', 'A diferença está no número de orações/verbos.'),

-- Nível 73B — Frase, oração e período
('sintaxe', 73, 'B', 'VF', '"Que calor!" é uma frase mas não é uma oração.', '[]', 'Verdadeiro', '"Que calor!" tem sentido mas não tem verbo — é frase nominal, não oração.'),
('sintaxe', 73, 'B', 'MC', 'Qual é o período composto?', '["A menina dormiu.","Choveu muito hoje.","Ele saiu e não voltou.","Que dia agradável!"]', 'Ele saiu e não voltou.', '"Saiu" e "voltou" = dois verbos = duas orações = período composto.'),
('sintaxe', 73, 'B', 'CL', 'Separe as orações do período: "Ela acordou, tomou café e foi para a escola."', '[]', '1. Ela acordou / 2. tomou café / 3. foi para a escola', 'Três verbos = três orações coordenadas.'),
('sintaxe', 73, 'B', 'RF', 'Transforme o período simples em composto acrescentando uma oração: "Ela estudou." → "Ela estudou porque ___."', '[]', 'Ela estudou porque queria aprender. (ou qualquer conclusão coerente)', 'Acrescentar uma oração causal transforma o período de simples em composto.'),
('sintaxe', 73, 'B', 'DS', 'Escreva um parágrafo com 2 períodos simples e 1 composto.', '[]', 'Exemplo: "O dia amanheceu ensolarado. (simples) As crianças brincaram. (simples) Elas correram, pularam e gargalharam muito. (composto com 3 orações)"', 'Varia o tipo de período para tornar o texto mais dinâmico.'),
('sintaxe', 73, 'B', 'MC', '"Espero que você melhore." Quantas orações há?', '["1","2","3","4"]', '2', '"Espero" (1ª oração) + "que você melhore" (2ª oração) = período composto com 2 orações.'),
('sintaxe', 73, 'B', 'VF', 'Todo período composto tem pelo menos 2 verbos.', '[]', 'Verdadeiro', 'Cada oração tem um verbo — período composto (2+ orações) tem 2+ verbos.'),
('sintaxe', 73, 'B', 'CL', 'Identifique os verbos e conte as orações: "Quando ela chegou, todos sorriam e comemoravam."', '[]', 'Verbos: chegou, sorriam, comemoravam → 3 orações', 'Três verbos = três orações formando um período composto.'),
('sintaxe', 73, 'B', 'RF', 'Desmembre o período composto em orações: "Embora estivesse cansada, ela terminou o trabalho e foi dormir."', '[]', '1. Embora estivesse cansada / 2. ela terminou o trabalho / 3. foi dormir', 'Identificar as orações de um período composto com 3 verbos.'),
('sintaxe', 73, 'B', 'MC', 'Um período formado por uma única oração é chamado de:', '["período composto","frase nominal","período simples","oração subordinada"]', 'período simples', 'Período simples = uma única oração com um verbo.');

-- Nível 74A — Sujeito: identificação e tipos
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 74, 'A', 'MC', 'O sujeito da oração é:', '["o ser sobre quem se declara algo","a ação praticada na frase","o complemento do verbo","a palavra que modifica o verbo"]', 'o ser sobre quem se declara algo', 'Sujeito é o termo da oração sobre o qual se faz uma declaração (predicado).'),
('sintaxe', 74, 'A', 'CL', 'Identifique o sujeito: "A menina correu." / "Os alunos chegaram." / "Ela sorriu."', '[]', 'A menina / Os alunos / Ela', 'Sujeito responde à pergunta: "Quem praticou a ação?" ou "De quem se fala?"'),
('sintaxe', 74, 'A', 'VF', 'O sujeito simples tem apenas um núcleo.', '[]', 'Verdadeiro', 'Sujeito simples tem um só núcleo: "O menino correu" — núcleo: menino.'),
('sintaxe', 74, 'A', 'RF', 'Encontre o sujeito: "Os cachorros latem muito." / "A professora e os alunos chegaram." / "Choveu."', '[]', 'Os cachorros / A professora e os alunos / Não há sujeito (oração sem sujeito)', '"Choveu" é verbo impessoal — não tem sujeito.'),
('sintaxe', 74, 'A', 'MC', '"A menina e o menino estudam." O sujeito é:', '["simples","composto","indeterminado","inexistente"]', 'composto', '"A menina e o menino" = dois núcleos = sujeito composto.'),
('sintaxe', 74, 'A', 'DS', 'Escreva um exemplo de: sujeito simples / sujeito composto / sujeito oculto / oração sem sujeito.', '[]', 'Simples: O gato miou. / Composto: Pedro e Ana chegaram. / Oculto: Estudei muito. (= eu) / Sem sujeito: Faz calor.', 'Existem 4 tipos principais de sujeito na análise sintática.'),
('sintaxe', 74, 'A', 'VF', 'Em "Estudamos muito", o sujeito é oculto (= nós).', '[]', 'Verdadeiro', 'Sujeito oculto (elíptico): não aparece explicitamente mas pode ser identificado pela desinência verbal.'),
('sintaxe', 74, 'A', 'CL', 'Classifique o sujeito — Simples (S), Composto (C), Oculto (O), Sem sujeito (SS): "Choveu muito." / "João e Maria vieram." / "Corri rápido." / "O sol brilha."', '[]', 'SS / C / O (eu) / S', 'Choveu = impessoal sem sujeito; João e Maria = composto; Corri = oculto (eu); O sol = simples.'),
('sintaxe', 74, 'A', 'MC', 'Qual é o sujeito de "Fazem anos que não te vejo"?', '["anos","te","eu","não tem sujeito"]', 'não tem sujeito', '"Fazer" no sentido de tempo decorrido é impessoal — sem sujeito.'),
('sintaxe', 74, 'A', 'DS', 'Explique o que é sujeito indeterminado e dê 2 exemplos.', '[]', 'Sujeito indeterminado: quando não se sabe ou não se quer identificar quem praticou a ação. Ex: "Estão chamando você." / "Falam muito de você."', 'Verbo na 3ª pessoa do plural sem sujeito explícito = sujeito indeterminado.'),

-- Nível 74B — Sujeito: identificação e tipos
('sintaxe', 74, 'B', 'VF', '"Vendem-se casas" — o sujeito é "casas" (passivo com se).', '[]', 'Verdadeiro', '"Casas" é o sujeito paciente — o "se" é índice de voz passiva. O verbo concorda: vendem-se (pl.).'),
('sintaxe', 74, 'B', 'MC', 'Em "Precisa-se de ajudantes", o "se" indica:', '["voz passiva","sujeito indeterminado","reflexivo","sujeito oculto"]', 'sujeito indeterminado', '"Precisa-se de" = construção com sujeito indeterminado (verbo + se, transitivo indireto).'),
('sintaxe', 74, 'B', 'CL', 'Identifique o tipo de sujeito: "Há soluções para isso." / "Chove muito em abril." / "Comemos o bolo."', '[]', 'sem sujeito (há impessoal) / sem sujeito (chover impessoal) / oculto (nós)', 'Há e chover são verbos impessoais. Comemos = nós (oculto).'),
('sintaxe', 74, 'B', 'RF', 'Identifique e classifique o sujeito: "O professor e a diretora discutiram a proposta."', '[]', '"O professor e a diretora" = sujeito composto com dois núcleos: professor e diretora.', 'Dois substantivos ligados por "e" formam sujeito composto.'),
('sintaxe', 74, 'B', 'DS', 'Explique a diferença entre sujeito simples e sujeito composto, com exemplos originais.', '[]', 'Simples: um núcleo — "A aluna chegou cedo." / Composto: dois ou mais núcleos — "A aluna e o aluno chegaram cedo."', 'O número de núcleos define se o sujeito é simples ou composto.'),
('sintaxe', 74, 'B', 'MC', 'Qual frase tem sujeito INDETERMINADO?', '["Ela correu muito.","Estudamos juntos.","Dizem que vai chover.","O cachorro latiu."]', 'Dizem que vai chover.', '"Dizem" na 3ª pessoa plural sem sujeito explícito = sujeito indeterminado.'),
('sintaxe', 74, 'B', 'VF', 'O sujeito sempre vem antes do verbo.', '[]', 'Falso', 'O sujeito pode vir depois do verbo (sujeito posposto): "Chegaram os alunos."'),
('sintaxe', 74, 'B', 'CL', 'Encontre o sujeito em cada frase: "Chegaram os primeiros." / "Que sorte a nossa!" / "Existem muitas opções."', '[]', '"os primeiros" (posposto) / sem sujeito (frase exclamativa nominal) / "muitas opções" (posposto)', 'Sujeito pode estar em posição posposta ao verbo.'),
('sintaxe', 74, 'B', 'RF', 'Reescreva a frase com sujeito posposto: "Os alunos chegaram." → "Chegaram ___."', '[]', 'Chegaram os alunos.', 'Sujeito posposto: o verbo vem antes do sujeito, mas a concordância é mantida.'),
('sintaxe', 74, 'B', 'MC', 'Qual é o núcleo do sujeito em "Os colegas de turma chegaram cedo"?', '["os","colegas","turma","chegaram"]', 'colegas', 'Núcleo = palavra mais importante do sujeito. "Colegas" é o substantivo principal — os, de turma são adjuntos.');

-- Nível 75A — Predicado: identificação e tipos
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 75, 'A', 'MC', 'O predicado é:', '["o ser de quem se fala","tudo o que se diz sobre o sujeito","o verbo da oração","o complemento do sujeito"]', 'tudo o que se diz sobre o sujeito', 'Predicado é a parte da oração que traz informações sobre o sujeito — inclui o verbo e seus complementos.'),
('sintaxe', 75, 'A', 'CL', 'Identifique sujeito e predicado: "A chuva caiu forte." / "Os alunos estudaram." / "Ela é inteligente."', '[]', 'Suj.: A chuva | Pred.: caiu forte. / Suj.: Os alunos | Pred.: estudaram. / Suj.: Ela | Pred.: é inteligente.', 'O predicado sempre inclui o verbo.'),
('sintaxe', 75, 'A', 'VF', 'No predicado nominal, há um verbo de ligação + predicativo do sujeito.', '[]', 'Verdadeiro', 'Predicado nominal: "Ela é inteligente." — é (verbo de ligação) + inteligente (predicativo do sujeito).'),
('sintaxe', 75, 'A', 'RF', 'Identifique o tipo de predicado: "Ela cantou." / "Ela é bonita." / "Ela cantou uma música bonita."', '[]', 'verbal / nominal / verbo-nominal', 'Verbal = só verbo de ação. Nominal = verbo de ligação + predicativo. Verbo-nominal = verbo de ação + predicativo.'),
('sintaxe', 75, 'A', 'MC', '"O dia ficou nublado." O predicado é do tipo:', '["verbal","nominal","verbo-nominal","inexistente"]', 'nominal', '"Ficou" é verbo de ligação + "nublado" (predicativo do sujeito) = predicado nominal.'),
('sintaxe', 75, 'A', 'DS', 'Escreva um exemplo de cada tipo de predicado: verbal, nominal e verbo-nominal.', '[]', 'Verbal: Ela dormiu cedo. / Nominal: Ela é estudiosa. / Verbo-nominal: Ela chegou cansada.', 'Os três tipos de predicado têm estruturas diferentes.'),
('sintaxe', 75, 'A', 'VF', 'No predicado verbal, há um verbo de ação ou impessoal.', '[]', 'Verdadeiro', 'Predicado verbal tem verbo de ação (correr, estudar) ou impessoal (chover, nevar).'),
('sintaxe', 75, 'A', 'CL', 'Classifique em Verbal (V), Nominal (N) ou Verbo-Nominal (VN): "O atleta corre." / "O atleta é veloz." / "O atleta corre veloz."', '[]', 'V / N / VN', 'Verbal = só verbo de ação; nominal = verbo de ligação + predicativo; verbo-nominal = ação + predicativo.'),
('sintaxe', 75, 'A', 'MC', 'Qual verbo é de LIGAÇÃO?', '["correr","estudar","parecer","cantar"]', 'parecer', 'Parecer é verbo de ligação — conecta sujeito ao predicativo: "Ela parece feliz."'),
('sintaxe', 75, 'A', 'DS', 'Explique o que é predicativo do sujeito com 2 exemplos.', '[]', 'Predicativo do sujeito: adjetivo ou substantivo que caracteriza o sujeito após verbo de ligação. Ex: "Ela é médica." (médica = predicativo) / "O dia está quente." (quente = predicativo)', 'O predicativo do sujeito faz parte do predicado nominal.'),

-- Nível 75B — Predicado: identificação e tipos
('sintaxe', 75, 'B', 'VF', 'No predicado verbo-nominal, há dois núcleos: um verbo de ação e um predicativo.', '[]', 'Verdadeiro', '"Ela chegou sorrindo" — chegou (núcleo verbal) + sorrindo (predicativo do sujeito).'),
('sintaxe', 75, 'B', 'MC', '"A equipe trabalhou animada." O predicado é:', '["verbal — trabalhou","nominal — animada","verbo-nominal — trabalhou + animada","sujeito composto"]', 'verbo-nominal — trabalhou + animada', 'Trabalhou (verbo de ação) + animada (predicativo do sujeito) = verbo-nominal.'),
('sintaxe', 75, 'B', 'CL', 'Identifique o predicativo (do sujeito ou do objeto) em cada frase: "Ela ficou feliz." / "Consideramos o filme excelente."', '[]', 'feliz = predicativo do sujeito (ela) / excelente = predicativo do objeto (o filme)', 'O predicativo pode se referir ao sujeito ou ao objeto.'),
('sintaxe', 75, 'B', 'RF', 'Complete com um predicado nominal (verbo de ligação + predicativo): "O concurso ___ muito ___."', '[]', 'Exemplo: O concurso estava muito difícil. / O concurso pareceu muito interessante.', 'Qualquer verbo de ligação + adjetivo é válido.'),
('sintaxe', 75, 'B', 'DS', 'Analise o predicado de cada frase: tipo, verbo e predicativo (se houver): "Ela riu." / "Ela é alegre." / "Ela ria alegremente."', '[]', '"Riu" = verbal, verbo: riu, sem predicativo. / "É alegre" = nominal, verbo: é (ligação), predicativo: alegre. / "Ria alegremente" = verbal (alegremente é advérbio, não predicativo).', 'Distinguir predicativo de adjunto adverbial é importante na análise sintática.'),
('sintaxe', 75, 'B', 'MC', 'Verbos de ligação são: ser, estar, ficar, parecer, continuar, tornar-se. Qual deles é PERMANENTE?', '["estar","ficar","ser","tornar-se"]', 'ser', 'Ser indica estado permanente: "Ela é médica." Estar indica estado transitório.'),
('sintaxe', 75, 'B', 'VF', '"Ela tornara-se professora" tem predicado nominal.', '[]', 'Verdadeiro', '"Tornar-se" é verbo de ligação + "professora" (predicativo do sujeito) = predicado nominal.'),
('sintaxe', 75, 'B', 'CL', 'Classifique o predicado: "O menino correu e caiu." / "Eles parecem cansados." / "Ela estudou concentrada."', '[]', 'verbal (2 verbos de ação) / nominal / verbo-nominal', 'Correu e caiu = verbal; parecem cansados = nominal; estudou concentrada = verbo-nominal.'),
('sintaxe', 75, 'B', 'RF', 'Reescreva com predicado NOMINAL, mantendo o sentido: "Ela chegou contente." → "Ela ___."', '[]', 'Ela estava contente. / Ela é muito contente. / Ela pareceu contente.', 'Substituir verbo de ação + predicativo por verbo de ligação + predicativo.'),
('sintaxe', 75, 'B', 'MC', 'Em "O resultado saiu perfeito", "perfeito" é:', '["objeto direto","predicativo do sujeito","adjunto adverbial","sujeito"]', 'predicativo do sujeito', '"Saiu" é verbo de ligação aqui — perfeito é o predicativo do sujeito "resultado".');

-- Nível 76A — Complementos verbais: objeto direto e indireto
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 76, 'A', 'MC', 'O objeto direto completa o sentido do verbo:', '["com preposição","sem preposição","com qualquer preposição","substituído por pronome oblíquo tônico"]', 'sem preposição', 'Objeto direto não usa preposição: "Ela comprou o livro." — o livro = OD.'),
('sintaxe', 76, 'A', 'CL', 'Identifique OD (objeto direto) ou OI (objeto indireto): "Ela comprou pão." / "Ele gosta de música." / "Vi você." / "Obedeceu ao pai."', '[]', 'OD / OI / OD / OI', 'Comprou o quê? = pão (OD). Gosta de quê? = música (OI). Vi quem? = você (OD). Obedeceu a quem? = ao pai (OI).'),
('sintaxe', 76, 'A', 'VF', 'O objeto indireto é sempre introduzido por preposição.', '[]', 'Verdadeiro', 'OI sempre tem preposição: "Preciso de ajuda." (de) / "Gosto de você." (de) / "Obedeci ao professor." (a).'),
('sintaxe', 76, 'A', 'RF', 'Identifique e classifique o complemento verbal: "Ela presenteou [o amigo] [com flores]."', '[]', 'o amigo = OD / com flores = OI (objeto indireto)','Presentear alguém (OD) com algo (OI) — verbo com duplo objeto.'),
('sintaxe', 76, 'A', 'MC', '"Eu preciso de você." O complemento verbal é:', '["objeto direto","objeto indireto","adjunto adverbial","predicativo"]', 'objeto indireto', '"Precisar de" = transitivo indireto → de você = OI.'),
('sintaxe', 76, 'A', 'DS', 'Escreva 3 frases com OD e 3 com OI.', '[]', 'OD: Comprei um livro. / Vi o filme. / Ela abraçou a mãe. / OI: Gostei da prova. / Obedeci ao professor. / Preciso de ajuda.', 'OD = sem preposição; OI = com preposição.'),
('sintaxe', 76, 'A', 'VF', 'Um mesmo verbo pode exigir OD e OI ao mesmo tempo.', '[]', 'Verdadeiro', '"Dei o livro ao Pedro." — livro = OD; ao Pedro = OI. Verbos bitransitivos têm os dois.'),
('sintaxe', 76, 'A', 'CL', 'Identifique o tipo de complemento: "Eles enviaram [um e-mail] [ao diretor]."', '[]', 'um e-mail = OD / ao diretor = OI', '"Enviaram o quê?" = um e-mail (OD). "Enviaram a quem?" = ao diretor (OI).'),
('sintaxe', 76, 'A', 'MC', '"Ela contou a história para mim." Qual é o OI?', '["a história","para mim","ela","contou"]', 'para mim', '"Contou a quem / para quem?" = para mim (OI). A história = OD.'),
('sintaxe', 76, 'A', 'DS', 'Explique como substituir o OD por pronome oblíquo átono.', '[]', '"Comprei o livro." → "Comprei-o." (o = lo, na, a) / "Vi você." → "Vi-a/o." / Regra: OD masculino → o/lo; feminino → a/la; plural → os/las.', 'Pronomes oblíquos átonos (o, a, os, as, lo, la) substituem o objeto direto.'),

-- Nível 76B — Complementos verbais: objeto direto e indireto
('sintaxe', 76, 'B', 'VF', 'O pronome oblíquo "lhe" substitui o objeto indireto.', '[]', 'Verdadeiro', '"Dei o livro a ele." → "Dei-lhe o livro." — lhe substitui o OI "a ele".'),
('sintaxe', 76, 'B', 'MC', 'Em "Ela lhe contou um segredo", "lhe" é:', '["objeto direto","objeto indireto","sujeito","predicativo"]', 'objeto indireto', '"Lhe" = OI (a ele/a ela). A frase completa: Ela contou um segredo a ele.'),
('sintaxe', 76, 'B', 'CL', 'Substitua o OD ou OI pelo pronome correto: "Comprei o carro." → ___ / "Dei o livro ao Pedro." → ___', '[]', '"Comprei-o." / "Dei-lhe o livro."', 'O (OD masc. sing.) e lhe (OI) são os pronomes substitutos corretos.'),
('sintaxe', 76, 'B', 'RF', 'Reescreva a frase com o pronome oblíquo: "Ela viu os meninos." → "Ela ___." / "Contei a verdade a ela." → "___-lhe a verdade."', '[]', 'Ela os viu. / Contei-lhe a verdade.', 'Os = OD masc. pl.; lhe = OI.'),
('sintaxe', 76, 'B', 'DS', 'Analise os complementos da frase: "Ela enviou flores à professora para agradecê-la."', '[]', 'flores = OD / à professora = OI / agradecê-la = OD do verbo agradecer (la = ela = professora)', 'Uma frase pode ter OD e OI de verbos diferentes.'),
('sintaxe', 76, 'B', 'MC', 'O OD pode ser substituído pelo pronome:', '["lhe","se","o/a","nos"]', 'o/a', 'OD é substituído por o, a, os, as (pronomes de 3ª pessoa, caso acusativo).'),
('sintaxe', 76, 'B', 'VF', '"Informar alguém de algo" — "alguém" é OD e "algo" é OI.', '[]', 'Verdadeiro', '"Informei você (OD) da notícia (OI)." — dupla regência com OD e OI.'),
('sintaxe', 76, 'B', 'CL', 'Identifique se é OD ou OI: "Eles obedeceram [ao regulamento]." / "Ela comprou [flores]." / "Ele gosta [de livros]."', '[]', 'OI / OD / OI', 'Ao regulamento (preposição a) = OI; flores = OD; de livros (preposição de) = OI.'),
('sintaxe', 76, 'B', 'RF', 'Complete com o complemento verbal adequado (OD ou OI): "Ela confiou ___ ao amigo." / "Ele informou ___ da decisão."', '[]', 'segredo (OD) ao amigo (OI) / Ele informou o diretor (OD) da decisão (OI)', 'Confiar algo a alguém; informar alguém de algo — verbos bitransitivos.'),
('sintaxe', 76, 'B', 'MC', 'Qual verbo é INTRANSITIVO (não pede complemento)?', '["comprar","gostar","chover","ver"]', 'chover', 'Chover é impessoal e intransitivo — não pede objeto.');

-- Nível 77A — Adjuntos: adverbial e adnominal
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 77, 'A', 'MC', 'O adjunto adverbial é o termo que:', '["complementa o verbo transitivo","caracteriza o substantivo","expressa circunstâncias do verbo","é o sujeito da oração"]', 'expressa circunstâncias do verbo', 'Adjunto adverbial indica circunstâncias como tempo, lugar, modo, causa, etc.'),
('sintaxe', 77, 'A', 'CL', 'Identifique o adjunto adverbial e seu tipo: "Ela chegou [ontem]." / "Ele mora [aqui]." / "Correu [rapidamente]."', '[]', 'ontem = tempo / aqui = lugar / rapidamente = modo', 'Adjuntos adverbiais indicam as circunstâncias da ação.'),
('sintaxe', 77, 'A', 'VF', 'O adjunto adnominal caracteriza o substantivo (como um adjetivo).', '[]', 'Verdadeiro', 'Adjunto adnominal modifica o substantivo: "livro de matemática" (de matemática = adj. adnominal).'),
('sintaxe', 77, 'A', 'RF', 'Identifique o adjunto adnominal em: "A bela casa de pedra ficou famosa."', '[]', 'bela = adj. adnominal (adjetivo) / de pedra = adj. adnominal (locução adjetiva)', 'Bela e de pedra qualificam/caracterizam o substantivo casa.'),
('sintaxe', 77, 'A', 'MC', 'Em "Comprei um livro de história ontem", os adjuntos são:', '["de história = adnominal / ontem = adverbial","de história = adverbial / ontem = adnominal","ambos adverbiais","ambos adnominais"]', 'de história = adnominal / ontem = adverbial', '"De história" caracteriza o livro (adnominal). "Ontem" indica quando (adverbial).'),
('sintaxe', 77, 'A', 'DS', 'Escreva uma frase com 2 adjuntos adverbiais diferentes e identifique-os.', '[]', 'Exemplo: "Ela estudou muito (intensidade) em casa (lugar)." — muito = adj. adverbial de intensidade; em casa = adj. adverbial de lugar.', 'Uma frase pode ter vários adjuntos adverbiais de tipos diferentes.'),
('sintaxe', 77, 'A', 'VF', 'O adjunto adverbial pode ser removido da frase sem alterar o sentido essencial.', '[]', 'Verdadeiro', '"Ela chegou ontem." → "Ela chegou." — o sentido básico permanece. Adjunto adverbial é optativo.'),
('sintaxe', 77, 'A', 'CL', 'Classifique os adjuntos em adnominal (AN) ou adverbial (AV): "a casa [de tijolo] ficou pronta [rapidamente]"', '[]', 'de tijolo = AN (caracteriza a casa) / rapidamente = AV (indica modo)', 'Adjunto adnominal → substantivo; adjunto adverbial → verbo.'),
('sintaxe', 77, 'A', 'MC', 'Qual é o adjunto adverbial em "Ela cantou com alegria"?', '["Ela","cantou","com alegria","alegria"]', 'com alegria', '"Com alegria" indica o modo como ela cantou — adjunto adverbial de modo.'),
('sintaxe', 77, 'A', 'DS', 'Reescreva a frase acrescentando 3 adjuntos adverbiais: "Ela chegou."', '[]', 'Exemplo: "Ela chegou [ontem] (tempo) [em casa] (lugar) [cansada] (modo/estado) — ou — "Ela chegou tarde (tempo) ao trabalho (lugar) de táxi (meio)."', 'Adjuntos adverbiais enriquecem as frases com informações de circunstância.'),

-- Nível 77B — Adjuntos: adverbial e adnominal
('sintaxe', 77, 'B', 'VF', 'O adjunto adnominal pode ser um adjetivo, locução adjetiva, artigo ou numeral.', '[]', 'Verdadeiro', 'Todo termo que modifica o substantivo na oração é adjunto adnominal.'),
('sintaxe', 77, 'B', 'MC', 'Em "Os três meninos brasileiros chegaram", quais são os adjuntos adnominais?', '["Os e três e brasileiros","três e meninos","chegaram","os e chegaram"]', 'Os e três e brasileiros', 'Os (artigo), três (numeral) e brasileiros (adjetivo) caracterizam o substantivo meninos.'),
('sintaxe', 77, 'B', 'CL', 'Identifique o tipo de adjunto adverbial: "por medo" (___) / "durante a tarde" (___) / "para ajudar" (__)', '[]', 'causa / tempo / finalidade', 'Adjuntos adverbiais têm tipos variados conforme a circunstância que indicam.'),
('sintaxe', 77, 'B', 'RF', 'Encontre todos os adjuntos (adnominal e adverbial) na frase: "O jovem aluno correu rapidamente para a escola ontem."', '[]', 'jovem = adj. adnominal (adjetivo de aluno) / rapidamente = adj. adverbial de modo / para a escola = adj. adverbial de lugar / ontem = adj. adverbial de tempo', 'Uma frase pode ter vários adjuntos de tipos diferentes.'),
('sintaxe', 77, 'B', 'DS', 'Explique a diferença entre "complemento nominal" e "adjunto adnominal" com exemplos.', '[]', 'Adjunto adnominal: caracteriza o substantivo — "casa de pedra" (de pedra qualifica a casa). / Complemento nominal: completa o sentido de um substantivo abstrato — "necessidade de ajuda" (de ajuda completa o sentido de necessidade).', 'A diferença está na relação com o substantivo: caracterização vs. complementação de sentido.'),
('sintaxe', 77, 'B', 'MC', '"Fez a tarefa com cuidado." O adjunto adverbial "com cuidado" indica:', '["tempo","lugar","modo","causa"]', 'modo', '"Com cuidado" indica como a ação foi realizada — adjunto adverbial de modo.'),
('sintaxe', 77, 'B', 'VF', 'Adjuntos adverbiais de lugar respondem à pergunta "onde?" ou "aonde?".', '[]', 'Verdadeiro', '"Ela foi para a escola." — Para a escola responde a "aonde?" = adjunto adverbial de lugar.'),
('sintaxe', 77, 'B', 'CL', 'Classifique os adjuntos adverbiais: "Porque estava com pressa" (___) / "Para ganhar tempo" (___) / "Embora chovesse" (___)', '[]', 'causa / finalidade / concessão', 'Diferentes relações lógicas expressas por adjuntos adverbiais.'),
('sintaxe', 77, 'B', 'RF', 'Identifique o adjunto adnominal e o adverbial: "A pequena cidade do interior ficou famosa por causa do festival."', '[]', 'Adnominal: pequena (adj. de cidade) / do interior (loc. adj. de cidade) / Adverbial: por causa do festival (causa)', '"Pequena" e "do interior" caracterizam a cidade; "por causa do festival" indica a causa de ficar famosa.'),
('sintaxe', 77, 'B', 'MC', 'Qual é o adjunto ADNOMINAL em "A aula de português foi excelente"?', '["A aula","de português","foi","excelente"]', 'de português', '"De português" caracteriza a aula — é locução adjetiva com função de adjunto adnominal.');

-- Nível 78A — Orações coordenadas
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 78, 'A', 'MC', 'Orações coordenadas são:', '["orações com relação de dependência entre si","orações independentes, ligadas por coordenação","orações que completam o sentido do verbo","orações subordinadas"]', 'orações independentes, ligadas por coordenação', 'Coordenação: as orações têm sentido independente e se ligam por conjunções coordenativas.'),
('sintaxe', 78, 'A', 'CL', 'Identifique a oração e a conjunção coordenativa: "Estudei, [mas] não passei." / "Fui ao cinema [e] comi pipoca."', '[]', 'mas = adversativa / e = aditiva', '"Mas" indica oposição; "e" indica adição.'),
('sintaxe', 78, 'A', 'VF', 'Orações coordenadas assindéticas não têm conjunção.', '[]', 'Verdadeiro', 'Assindéticas: sem conjunção, separadas por vírgula: "Entrou, sentou, estudou."'),
('sintaxe', 78, 'A', 'RF', 'Ligue as orações com a conjunção coordenativa adequada: "Ela estudou. (adição) Ela foi aprovada." / "Chegou cedo. (concessão/adversidade) Não encontrou ninguém."', '[]', 'Ela estudou e foi aprovada. / Chegou cedo, mas não encontrou ninguém.', '"E" = aditiva; "mas" = adversativa.'),
('sintaxe', 78, 'A', 'MC', '"Ele trabalha, portanto tem dinheiro." A conjunção "portanto" é:', '["aditiva","adversativa","conclusiva","alternativa"]', 'conclusiva', '"Portanto", "logo", "então" são conjunções conclusivas — indicam conclusão.'),
('sintaxe', 78, 'A', 'DS', 'Escreva um exemplo de cada tipo de oração coordenada: aditiva, adversativa, alternativa, conclusiva, explicativa.', '[]', 'Aditiva: Estudou e passou. / Adversativa: Estudou, mas não passou. / Alternativa: Ou estuda ou reprova. / Conclusiva: Estudou, logo passou. / Explicativa: Corre, pois está atrasado.', 'Cinco tipos de coordenadas sindéticas.'),
('sintaxe', 78, 'A', 'VF', '"Ou come, ou sai!" — a conjunção "ou...ou" indica alternativa.', '[]', 'Verdadeiro', '"Ou...ou" é conjunção alternativa — indica escolha ou alternância.'),
('sintaxe', 78, 'A', 'CL', 'Identifique o tipo da coordenada sindética: "Ela é inteligente, portanto foi aprovada." / "Fique, pois preciso de você." / "Vai ou fica?"', '[]', 'conclusiva / explicativa / alternativa', '"Portanto" = conclusiva; "pois" (antes do verbo) = explicativa; "ou" = alternativa.'),
('sintaxe', 78, 'A', 'MC', 'Qual conjunção é EXPLICATIVA?', '["mas","porque (após imperativo)","e","portanto"]', 'porque (após imperativo)', '"Porque" após imperativo explica: "Venha, porque preciso de ajuda." (= pois).'),
('sintaxe', 78, 'A', 'DS', 'Escreva um período com 3 orações coordenadas de tipos diferentes.', '[]', 'Exemplo: "Ela estudou (assindética), foi ao exame e (aditiva) foi aprovada, portanto (conclusiva) ficou feliz."', 'Períodos com múltiplas orações coordenadas são comuns em textos.'),

-- Nível 78B — Orações coordenadas
('sintaxe', 78, 'B', 'VF', '"Mas", "porém", "todavia", "contudo", "entretanto" são todas conjunções adversativas.', '[]', 'Verdadeiro', 'Todas indicam oposição/contraste entre as orações.'),
('sintaxe', 78, 'B', 'MC', 'Qual par de conjunções forma oração alternativa?', '["e...e","ora...ora","tanto...quanto","não só...mas também"]', 'ora...ora', '"Ora...ora" indica alternância: "Ora ri, ora chora." Alternativa.'),
('sintaxe', 78, 'B', 'CL', 'Classifique as orações coordenadas: "Correu depressa, porém chegou tarde." / "Estude, pois a prova é amanhã." / "Ela gosta de dançar e de cantar."', '[]', 'adversativa / explicativa / aditiva', '"Porém" = adversativa; "pois" + explicação = explicativa; "e" = aditiva.'),
('sintaxe', 78, 'B', 'RF', 'Una com a conjunção conclusiva correta: "Ela se dedicou muito. Merece o prêmio."', '[]', 'Ela se dedicou muito, portanto (logo, então) merece o prêmio.', '"Portanto", "logo" ou "então" indicam conclusão.'),
('sintaxe', 78, 'B', 'DS', 'Explique a diferença entre "porque" explicativo e "porque" causal, com exemplos.', '[]', 'Causal (subordinada): indica causa — "Chorou porque se machucou." (antes do fato) / Explicativo (coordenada): justifica — "Traga o casaco, porque está frio." (justifica o pedido)', '"Porque" coordenativo explica uma ordem/afirmação; subordinativo indica causa.'),
('sintaxe', 78, 'B', 'MC', 'Em "Não só estudou, mas também se preparou bem", a conjunção é:', '["adversativa simples","aditiva correlativa","alternativa","conclusiva"]', 'aditiva correlativa', '"Não só...mas também" é conjunção aditiva correlativa — indica adição com ênfase.'),
('sintaxe', 78, 'B', 'VF', 'Orações assindéticas são separadas por vírgula, ponto e vírgula ou dois-pontos.', '[]', 'Verdadeiro', 'Sem conjunção, a pausa é marcada pela pontuação: "Entrou, olhou, saiu."'),
('sintaxe', 78, 'B', 'CL', 'Diga se são sindéticas (S) ou assindéticas (A): "Ela entrou e cumprimentou." / "Ele correu, pulou, caiu." / "Faz frio, logo vista o casaco."', '[]', 'S (e = aditiva) / A (sem conjunção) / S (logo = conclusiva)', 'Sindéticas têm conjunção; assindéticas não têm.'),
('sintaxe', 78, 'B', 'RF', 'Reescreva as orações assindéticas transformando-as em sindéticas: "Chegou, viu, venceu."', '[]', 'Chegou, viu e venceu. (aditiva) — ou — Chegou, viu, portanto venceu. (conclusiva)', 'Assindéticas podem ser transformadas em sindéticas com conjunção.'),
('sintaxe', 78, 'B', 'MC', '"Venha cedo, pois temos muito a fazer." A conjunção "pois" é:', '["conclusiva","explicativa","adversativa","alternativa"]', 'explicativa', '"Pois" antes do verbo = explicativa. "Pois" após o verbo pode ser conclusiva.');

-- Nível 79A — Orações subordinadas substantivas
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 79, 'A', 'MC', 'Orações subordinadas são:', '["orações independentes","orações que dependem de outra oração (principal)","orações sem verbo","orações coordenadas"]', 'orações que dependem de outra oração (principal)', 'Subordinadas dependem sintaticamente da oração principal para ter sentido completo.'),
('sintaxe', 79, 'A', 'CL', 'Identifique a oração principal (OP) e a subordinada (OS): "Sei [que você virá]." / "Espero [que tudo melhore]."', '[]', 'Sei = OP / que você virá = OS / Espero = OP / que tudo melhore = OS', 'A oração principal contém o verbo principal; a subordinada completa o sentido.'),
('sintaxe', 79, 'A', 'VF', 'As orações subordinadas substantivas exercem a função de substantivo (sujeito, objeto, etc.).', '[]', 'Verdadeiro', 'Subordinadas substantivas podem ser sujeito: "Que ela viesse era importante." / ou OD: "Espero que você venha."'),
('sintaxe', 79, 'A', 'RF', 'Identifique a função da subordinada: "[Que ele estude] é importante." / "Espero [que chova]." / "Duvido [de que ela saiba]."', '[]', 'sujeito / objeto direto / objeto indireto', '"Que ele estude" = sujeito. "Que chova" = OD de espero. "De que ela saiba" = OI de duvido.'),
('sintaxe', 79, 'A', 'MC', 'Em "É importante que você estude", a oração "que você estude" é:', '["oração principal","subordinada substantiva subjetiva","subordinada adverbial","oração coordenada"]', 'subordinada substantiva subjetiva', '"Que você estude" é o sujeito de "é importante" — subordinada substantiva subjetiva.'),
('sintaxe', 79, 'A', 'DS', 'Escreva 3 frases com orações subordinadas substantivas em funções diferentes: sujeito, OD, OI.', '[]', 'Sujeito: "Que você venha é essencial." / OD: "Quero que você fique." / OI: "Preciso de que você me ajude."', 'Subordinadas substantivas exercem funções de substantivo na oração.'),
('sintaxe', 79, 'A', 'VF', '"Não sei o que fazer." — "o que fazer" é uma oração subordinada substantiva.', '[]', 'Verdadeiro', '"O que fazer" = OD de sei — é uma subordinada substantiva objetiva direta.'),
('sintaxe', 79, 'A', 'CL', 'Classifique as subordinadas: "Não sei [se ela virá]." / "É necessário [que estudem]." / "Estou certo [de que voltará]."', '[]', 'OD objetiva direta / sujeito subjetiva / predicativo predicativa', '"Se ela virá" = OD; "que estudem" = sujeito; "de que voltará" = predicativo.'),
('sintaxe', 79, 'A', 'MC', 'A conjunção "que" nas subordinadas substantivas é chamada de:', '["conjunção adversativa","conjunção integrante","pronome relativo","conjunção alternativa"]', 'conjunção integrante', '"Que" e "se" são conjunções integrantes — introduzem orações subordinadas substantivas.'),
('sintaxe', 79, 'A', 'DS', 'Explique a diferença entre oração subordinada substantiva subjetiva e objetiva direta, com exemplos.', '[]', 'Subjetiva = funciona como sujeito: "É certo que ele virá." / Objetiva direta = funciona como OD: "Espero que ele venha."', 'A função sintática dentro da oração principal diferencia os tipos de subordinada substantiva.'),

-- Nível 79B — Orações subordinadas adverbiais
('sintaxe', 79, 'B', 'MC', 'Orações subordinadas adverbiais exercem a função de:', '["sujeito","objeto direto","adjunto adverbial","predicativo"]', 'adjunto adverbial', 'Adverbiais são como adjuntos adverbiais — indicam circunstâncias (tempo, causa, condição, etc.).'),
('sintaxe', 79, 'B', 'VF', '"Embora fosse difícil, ela conseguiu." — "Embora fosse difícil" é oração subordinada adverbial concessiva.', '[]', 'Verdadeiro', '"Embora" introduz oração concessiva — indica concessão/contraste.'),
('sintaxe', 79, 'B', 'CL', 'Identifique o tipo de adverbial: "Quando ela chegou, todos aplaudiram." / "Porque estudou, foi aprovada." / "Se você vier, fico feliz."', '[]', 'temporal / causal / condicional', 'Quando = temporal; porque = causal; se = condicional.'),
('sintaxe', 79, 'B', 'RF', 'Complete com a conjunção adverbial adequada: "___ ele correr muito, não chegará a tempo." / "___ fosse tarde, ela saiu."', '[]', 'Mesmo que / Embora (concessivas) — Mesmo que ele corra muito, não chegará. / Embora fosse tarde, ela saiu.', 'Concessivas indicam que o fato ocorre apesar de outro fato contrário.'),
('sintaxe', 79, 'B', 'DS', 'Escreva exemplos de orações subordinadas adverbiais: temporal, causal, condicional, concessiva, final.', '[]', 'Temporal: Quando cheguei, ele já tinha ido. / Causal: Como estava cansada, dormiu cedo. / Condicional: Se estudar, passará. / Concessiva: Embora chovesse, saímos. / Final: Estudou para que passasse.', 'Cinco dos principais tipos de orações adverbiais.'),
('sintaxe', 79, 'B', 'MC', '"Para que você entenda, explicarei de novo." A oração sublinhada é adverbial:', '["temporal","final","condicional","comparativa"]', 'final', '"Para que" indica finalidade — adverbial final.'),
('sintaxe', 79, 'B', 'VF', 'As orações adverbiais sempre vêm depois da oração principal.', '[]', 'Falso', 'Orações adverbiais podem vir antes: "Embora chovesse, saímos." ou depois: "Saímos embora chovesse."'),
('sintaxe', 79, 'B', 'CL', 'Identifique as conjunções e os tipos de adverbiais: "Conforme o manual instrui, ..." / "À medida que envelhece, ..." / "Tanto estudou que passou."', '[]', 'Conforme = conformativa / À medida que = proporcional / Tanto...que = consecutiva', 'Tipos menos comuns de orações adverbiais.'),
('sintaxe', 79, 'B', 'RF', 'Reescreva juntando as duas orações com conjunção adverbial adequada: "Ela ficou em casa. Estava doente."', '[]', 'Ela ficou em casa porque estava doente. (causal) / Como estava doente, ela ficou em casa.', '"Porque" e "como" são conjunções causais comuns.'),
('sintaxe', 79, 'B', 'MC', '"Ela estudou tanto que passou com louvor." É uma oração adverbial:', '["causal","concessiva","consecutiva","comparativa"]', 'consecutiva', '"Tanto...que" introduz oração consecutiva — indica consequência.');
