-- ============================================================
-- GeraFicha — Módulo 5: Interpretação e Produção de Texto
-- Níveis 103–120 | Séries A e B
-- ============================================================

-- Nível 103A — Produção textual: planejamento e parágrafo
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 103, 'A', 'MC', 'Qual é a primeira etapa da produção textual?', '["Escrever tudo de uma vez","Planejar: definir tema, objetivo, público e estrutura","Revisar o texto","Publicar o texto"]', 'Planejar: definir tema, objetivo, público e estrutura', 'Bom texto começa com planejamento: o que escrever, para quem, com que propósito.'),
('interpretacao', 103, 'A', 'CL', 'Organize as etapas da produção textual na ordem correta: Revisão / Publicação / Planejamento / Escrita da 1ª versão', '[]', '1. Planejamento → 2. Escrita da 1ª versão → 3. Revisão → 4. Publicação', 'Etapas da produção textual: planejar → escrever → revisar → publicar.'),
('interpretacao', 103, 'A', 'VF', 'Um bom parágrafo tem uma ideia central (tópico frasal) e frases de desenvolvimento.', '[]', 'Verdadeiro', 'Estrutura do parágrafo: tópico frasal (ideia principal) + desenvolvimento + conclusão/transição.'),
('interpretacao', 103, 'A', 'RF', 'Escreva um parágrafo sobre "a importância do sono" com: tópico frasal, 2 frases de desenvolvimento e 1 conclusão.', '[]', 'Exemplo: "Dormir bem é essencial para a saúde. (tópico) Durante o sono, o cérebro consolida memórias e o corpo se regenera. (des.) Além disso, a falta de sono prejudica a concentração e o humor. (des.) Portanto, priorizar um sono de qualidade é investimento em saúde e bem-estar. (conclusão)"', 'Parágrafo bem estruturado: TF + desenvolvimento + conclusão.'),
('interpretacao', 103, 'A', 'MC', 'O que é um tópico frasal?', '["A última frase do parágrafo","A frase que apresenta a ideia central do parágrafo","Uma frase decorativa","O título do parágrafo"]', 'A frase que apresenta a ideia central do parágrafo', 'Tópico frasal = ideia principal do parágrafo, geralmente na primeira frase.'),
('interpretacao', 103, 'A', 'DS', 'Avalie este parágrafo e sugira melhorias: "O Brasil é grande. O Brasil é bonito. O Brasil tem natureza. O Brasil tem cultura."', '[]', 'Problemas: repetição excessiva de "O Brasil" (falta coesão); ausência de desenvolvimento das ideias; sem tópico frasal claro. Sugestão: "O Brasil é um país de dimensões continentais, reconhecido pela diversidade de sua natureza e pela riqueza de sua cultura."', 'Parágrafo com repetição e sem desenvolvimento — revisão necessária.'),
('interpretacao', 103, 'A', 'VF', 'Cada parágrafo deve tratar de uma única ideia central.', '[]', 'Verdadeiro', 'Unidade temática: um parágrafo, uma ideia. Mudar de ideia = novo parágrafo.'),
('interpretacao', 103, 'A', 'CL', 'Identifique o tópico frasal e as frases de desenvolvimento: "A leitura transforma. Ela amplia o vocabulário e o conhecimento de mundo. Além disso, desenvolve a empatia ao colocar o leitor na perspectiva do personagem."', '[]', 'Tópico frasal: "A leitura transforma." / Desenvolvimento: as outras duas frases explicam e aprofundam a afirmação.', 'O tópico frasal é a tese do parágrafo; o desenvolvimento a comprova.'),
('interpretacao', 103, 'A', 'MC', 'Qual conector é usado para ADICIONAR uma nova ideia ao parágrafo?', '["porém","portanto","além disso","embora"]', 'além disso', '"Além disso", "também", "e" são conectores de adição para desenvolver ideias.'),
('interpretacao', 103, 'A', 'DS', 'Escreva um parágrafo completo sobre "alimentação saudável" usando pelo menos 3 conectores diferentes.', '[]', 'Exemplo: "Uma alimentação saudável é fundamental para a qualidade de vida. Em primeiro lugar, ela fornece os nutrientes necessários para o bom funcionamento do organismo. Além disso, previne doenças crônicas como diabetes e hipertensão. Por isso, investir em uma dieta equilibrada é cuidar da saúde a longo prazo."', 'Conectores: em primeiro lugar, além disso, por isso — garantem coesão.'),

-- Nível 103B — Produção textual: dissertação e argumentação
('interpretacao', 103, 'B', 'VF', 'A introdução de uma dissertação deve apresentar o tema e a tese do autor.', '[]', 'Verdadeiro', 'Introdução dissertativa: contextualizar o tema + anunciar a tese (posição do autor).'),
('interpretacao', 103, 'B', 'MC', 'Quantos parágrafos tem, geralmente, uma dissertação escolar básica?', '["1","2","3 a 5","10 ou mais"]', '3 a 5', 'Estrutura básica: introdução (1) + 2-3 de desenvolvimento + conclusão (1) = 4-5 parágrafos.'),
('interpretacao', 103, 'B', 'CL', 'Organize a dissertação: "Portanto, a educação deve ser prioridade nacional. / Estudos mostram que países com alto nível educacional têm melhor qualidade de vida. / A educação é o maior investimento de uma nação. / Além disso, a educação reduz desigualdades sociais."', '[]', '1. A educação é o maior investimento... (tese/introdução) / 2. Estudos mostram... (argumento 1) / 3. Além disso, a educação reduz... (argumento 2) / 4. Portanto... (conclusão)', 'Ordenar a dissertação: tese → argumentos → conclusão.'),
('interpretacao', 103, 'B', 'RF', 'Escreva uma introdução dissertativa sobre "violência no trânsito" (2-3 frases).', '[]', 'Exemplo: "A violência no trânsito é um dos maiores problemas de saúde pública do Brasil. A cada ano, milhares de pessoas perdem a vida em acidentes evitáveis. Diante desse quadro alarmante, é fundamental discutir as causas desse fenômeno e as possíveis soluções."', 'Introdução: contextualizar + anunciar o problema + indicar a direção do texto.'),
('interpretacao', 103, 'B', 'DS', 'Escreva uma dissertação completa (4 parágrafos) sobre "o papel das redes sociais na vida dos jovens".', '[]', 'Intro: contextualização + tese (benefícios e riscos). / Parágrafo 2: benefícios (comunicação, informação, expressão). / Parágrafo 3: riscos (vício, cyberbullying, desinformação). / Conclusão: uso consciente e regulamentado é o caminho.', 'Dissertação completa com posição equilibrada: pros + contras + conclusão propositiva.'),
('interpretacao', 103, 'B', 'MC', 'A conclusão de uma dissertação deve:', '["repetir a introdução palavra por palavra","apresentar argumentos novos que ficaram de fora","retomar a tese e propor uma síntese ou solução","descrever detalhadamente o problema"]', 'retomar a tese e propor uma síntese ou solução', 'Conclusão: retoma a tese + sintetiza os argumentos + propõe ação/reflexão.'),
('interpretacao', 103, 'B', 'VF', 'A proposta de intervenção na conclusão indica o que pode ser feito para resolver o problema.', '[]', 'Verdadeiro', 'Proposta de intervenção: "Portanto, é necessário que o governo [ação], a escola [ação] e a família [ação]..."'),
('interpretacao', 103, 'B', 'CL', 'Identifique se a conclusão está correta: "Portanto, como vimos, a leitura é importante. Todos devem ler mais."', '[]', 'Conclusão vaga — "Como vimos" é clichê; "todos devem" é genérico demais. Proposta: especificar agentes e ações (ex.: escolas, famílias, políticas públicas).', 'Conclusão eficaz: retoma tese + proposta específica, não genérica.'),
('interpretacao', 103, 'B', 'RF', 'Escreva uma conclusão para o tema "desigualdade social no Brasil" (3 frases).', '[]', 'Exemplo: "Em síntese, a desigualdade social no Brasil é resultado de séculos de exclusão histórica e concentração de renda. Para reverter esse quadro, são necessárias políticas públicas de educação de qualidade e redistribuição de renda. Somente com investimento real nas pessoas será possível construir uma sociedade mais justa e igualitária."', 'Conclusão: síntese + proposta + perspectiva de futuro.'),
('interpretacao', 103, 'B', 'MC', 'Qual é o principal objetivo do desenvolvimento numa dissertação?', '["apresentar o tema ao leitor","repetir a tese várias vezes","apresentar e desenvolver os argumentos que sustentam a tese","descrever o narrador"]', 'apresentar e desenvolver os argumentos que sustentam a tese', 'Desenvolvimento: corpo do texto onde cada parágrafo apresenta um argumento.');

-- Nível 104A — Gêneros literários: lírico, épico, dramático
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 104, 'A', 'MC', 'O gênero lírico expressa principalmente:', '["aventuras de heróis","sentimentos e emoções do eu lírico","conflitos dramatizados por personagens","fatos históricos"]', 'sentimentos e emoções do eu lírico', 'Lírico: poema, música, soneto — expressão do mundo interior do poeta.'),
('interpretacao', 104, 'A', 'CL', 'Classifique em Lírico (L), Épico (E) ou Dramático (D): soneto — epopeia — tragédia — ode — peça teatral — romance de aventura', '[]', 'L — E — D — L — D — E', 'Soneto e ode = lírico. Epopeia e romance de aventura = épico. Tragédia e peça = dramático.'),
('interpretacao', 104, 'A', 'VF', 'O eu lírico é o "eu" que fala no poema — não é necessariamente o autor.', '[]', 'Verdadeiro', 'Eu lírico = voz do poema. O autor pode criar um eu lírico diferente de si mesmo.'),
('interpretacao', 104, 'A', 'RF', 'Identifique o gênero e justifique: "Parte da tua vida, parte do meu coração / E de tudo que sinto, faço esta canção."', '[]', 'Gênero lírico — há um eu lírico expressando sentimentos (amor, saudade, separação) em primeira pessoa.', 'Lírico: sentimentos expressos por um eu lírico em 1ª pessoa.'),
('interpretacao', 104, 'A', 'MC', 'Uma tragédia pertence ao gênero:', '["lírico","épico","dramático","informativo"]', 'dramático', 'Tragédia (Shakespeare, Sófocles) pertence ao gênero dramático — texto para ser encenado.'),
('interpretacao', 104, 'A', 'DS', 'Explique as características do gênero épico com 2 exemplos.', '[]', 'Épico: narrativa longa sobre façanhas heroicas, geralmente em verso. Características: herói, aventura, batalhas, intervenção divina. Ex: "Os Lusíadas" (Camões) / "Odisseia" (Homero)', 'O épico narra feitos heroicos e históricos de forma grandiosa.'),
('interpretacao', 104, 'A', 'VF', 'O gênero dramático é escrito para ser encenado, com falas de personagens e rubricas.', '[]', 'Verdadeiro', 'Texto dramático: diálogos + didascálias (rubricas) indicando ação, expressão, cenário.'),
('interpretacao', 104, 'A', 'CL', 'Identifique os elementos: Eu lírico (___) / Rima (___) / Herói épico (___) / Ato e cena (___) / Estrofe (__)', '[]', 'lírico / lírico / épico / dramático / lírico', 'Cada elemento pertence ao gênero específico.'),
('interpretacao', 104, 'A', 'MC', 'O soneto é uma forma poética com:', '["10 estrofes de 5 versos","2 quartetos e 2 tercetos (14 versos total)","versos livres sem rima","3 estrofes de 4 versos"]', '2 quartetos e 2 tercetos (14 versos total)', 'Soneto clássico: 4+4+3+3 = 14 versos, geralmente com rima.'),
('interpretacao', 104, 'A', 'DS', 'Escreva um pequeno poema lírico de 4 versos expressando um sentimento à sua escolha.', '[]', 'Exemplo: "A saudade é um mar de lembranças / Que vem e vai como as ondas do tempo / Carrega consigo as antigas danças / De um coração que amou sem contemp[l]o."', 'Poema lírico: expressão de sentimento em versos, com ou sem rima.'),

-- Nível 104B — Poesia: análise e elementos
('interpretacao', 104, 'B', 'VF', 'A rima é a repetição de sons iguais ou parecidos no final dos versos.', '[]', 'Verdadeiro', 'Rima: "amor / dor", "céu / mel" — sons iguais ao final dos versos.'),
('interpretacao', 104, 'B', 'MC', 'O que é um verso?', '["um parágrafo de poema","cada linha de um poema","um conjunto de estrofes","a rima do poema"]', 'cada linha de um poema', 'Verso = cada linha do poema. Estrofe = conjunto de versos. Poema = conjunto de estrofes.'),
('interpretacao', 104, 'B', 'CL', 'Analise o poema: "Minha terra tem palmeiras / Onde canta o Sabiá / As aves que aqui gorjeiam / Não gorjeiam como lá." (Gonçalves Dias) — identifique rima, estrofe, tema.', '[]', 'Rima: palmeiras/gorjeiam (toante) / Sabiá/lá (rica) / Estrofe: 1 quarteto (4 versos) / Tema: saudade da terra natal', '"Canção do Exílio" — poema lírico de saudade.'),
('interpretacao', 104, 'B', 'RF', 'Escreva um quarteto (4 versos) com esquema de rima ABAB (alternada).', '[]', 'Exemplo: "O sol nasce devagar (A) / E ilumina o novo dia (B) / Trazendo a luz do mar (A) / E toda a sua magia (B)."', 'Esquema ABAB: 1º verso rima com 3º; 2º com 4º.'),
('interpretacao', 104, 'B', 'DS', 'Analise a métrica e o tema: "Amor é fogo que arde sem se ver / É ferida que dói e não se sente / É um contentamento descontente / É dor que desatina sem doer." (Camões)', '[]', 'Tema: paradoxos do amor / Figura de linguagem: oxímoro (fogo que arde sem se ver, dor que desatina sem doer) / Estrutura: quarteto (4 versos) com anáfora ("É...")', 'Soneto de Camões — análise de figuras e estrutura.'),
('interpretacao', 104, 'B', 'MC', 'O que é uma estrofe?', '["um verso isolado","conjunto de versos que formam uma unidade","o título do poema","a rima final"]', 'conjunto de versos que formam uma unidade', 'Estrofe = grupo de versos. Quarteto = 4 versos. Terceto = 3 versos. Dístico = 2 versos.'),
('interpretacao', 104, 'B', 'VF', 'A poesia concreta rompe com a estrutura tradicional e usa o espaço visual como elemento expressivo.', '[]', 'Verdadeiro', 'Poesia concreta: o arranjo visual das palavras na página contribui para o significado.'),
('interpretacao', 104, 'B', 'CL', 'Identifique o tipo de rima: "saudade/vontade" (___) / "amor/flor" (___) / "vida/ferida" (___)', '[]', 'saudade/vontade = rica (sons iguais) / amor/flor = toante (só a vogal tônica rima) / vida/ferida = rica', 'Rima rica: sons iguais a partir da última vogal tônica. Toante: só a vogal.'),
('interpretacao', 104, 'B', 'RF', 'Escreva um poema sem rima (verso livre) sobre um tema da natureza.', '[]', 'Exemplo: "A chuva chega devagar / Primeiro as nuvens escurecem / Depois o cheiro de terra molhada / E finalmente a água / Lavando tudo que estava cansado."', 'Verso livre: sem rima obrigatória, mas com ritmo e imagens poéticas.'),
('interpretacao', 104, 'B', 'MC', 'O haiku é uma forma poética japonesa com:', '["14 versos","3 versos (5-7-5 sílabas)","4 estrofes","versos rimados obrigatoriamente"]', '3 versos (5-7-5 sílabas)', 'Haiku: 3 versos, 5-7-5 sílabas, geralmente sobre a natureza e um momento presente.');

-- Nível 105A — Revisão Interpretação I (Níveis 97–104)
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 105, 'A', 'MC', 'Qual tipo de texto é "Um menino encontrou uma chave mágica e viajou para mundos diferentes"?', '["informativo","argumentativo","narrativo","injuntivo"]', 'narrativo', 'Tem personagem (menino), enredo (encontrou chave, viajou), fantasia — texto narrativo.'),
('interpretacao', 105, 'A', 'CL', 'Associe o gênero ao tipo de texto: receita (___) / notícia (___) / conto (___) / editorial (__)', '[]', 'injuntivo / informativo / narrativo / argumentativo', 'Cada gênero pertence a um tipo predominante de texto.'),
('interpretacao', 105, 'A', 'VF', 'A coesão e a coerência são igualmente importantes para a qualidade de um texto.', '[]', 'Verdadeiro', 'Coesão (conexão formal) + coerência (lógica das ideias) = texto bem escrito.'),
('interpretacao', 105, 'A', 'RF', 'Identifique as figuras de linguagem: "O tempo voa." / "Chorei rios de lágrimas." / "Ela sorria como o sol."', '[]', '"O tempo voa" = metáfora (tempo = ser que voa) / "Chorei rios de lágrimas" = hipérbole / "sorria como o sol" = comparação', 'Revisão das três figuras mais comuns.'),
('interpretacao', 105, 'A', 'MC', 'Qual é a estrutura de um texto argumentativo?', '["personagem + enredo + clímax","tese + argumentos + conclusão","apresentação + complicação + desfecho","informação + dados + tabelas"]', 'tese + argumentos + conclusão', 'Argumentativo: tese (opinião) + argumentos (provas/exemplos) + conclusão.'),
('interpretacao', 105, 'A', 'DS', 'Analise um trecho: "Segundo pesquisa da Unicef, 1 em cada 3 crianças no mundo não tem acesso à educação de qualidade. Esse dado alarmante revela a urgência de políticas educacionais mais efetivas." — Identifique: tipo de texto, argumento usado e tese.', '[]', 'Tipo: argumentativo / Argumento: autoridade + dado estatístico (Unicef) / Tese implícita: são necessárias políticas educacionais mais efetivas', 'Análise textual completa de trecho argumentativo.'),
('interpretacao', 105, 'A', 'VF', 'O narrador onisciente é aquele que sabe tudo sobre todos os personagens da história.', '[]', 'Verdadeiro', 'Narrador onisciente (3ª pessoa): acesso a pensamentos e sentimentos de todos.'),
('interpretacao', 105, 'A', 'CL', 'Identifique: literal ou inferencial: "Ela saiu sem olhar para trás." — O que está explícito e o que se pode inferir?', '[]', 'Explícito: ela saiu e não olhou para trás / Inferência: ela estava decidida, não queria se arrepender, havia algo que não queria ver', 'A mesma informação literal permite múltiplas inferências.'),
('interpretacao', 105, 'A', 'MC', 'Uma conclusão argumentativa de qualidade deve:', '["introduzir um argumento novo que contradiz a tese","repetir introdução e argumentos","sintetizar a tese e propor ação/reflexão","descrever personagens"]', 'sintetizar a tese e propor ação/reflexão', 'Conclusão eficaz: não apresenta argumento novo — sintetiza e propõe.'),
('interpretacao', 105, 'A', 'DS', 'Produza um parágrafo dissertativo completo sobre o tema: "A importância do respeito às diferenças."', '[]', 'Exemplo: "Respeitar as diferenças é condição essencial para a convivência em uma sociedade plural. Cada indivíduo carrega experiências, culturas e perspectivas únicas que enriquecem o coletivo. Quando ignoramos ou desprezamos essas diferenças, criamos barreiras que impedem a colaboração e geram conflitos desnecessários. Portanto, cultivar o respeito à diversidade é investir na coesão e no progresso social."', 'Parágrafo com tópico frasal + 2 argumentos + conclusão.'),

-- Nível 105B — Revisão Interpretação II
('interpretacao', 105, 'B', 'VF', 'Textos de diferentes tipos podem coexistir num mesmo gênero (ex.: uma crônica pode ser narrativa e argumentativa).', '[]', 'Verdadeiro', 'Muitos textos são híbridos: crônica (narrativa + reflexão), reportagem (informativa + descritiva).'),
('interpretacao', 105, 'B', 'MC', 'Qual elemento é EXCLUSIVO do texto dramático?', '["tese","narrador","didascália (rubrica)","tópico frasal"]', 'didascália (rubrica)', 'Didascálias são instruções do texto dramático: (entra pela esquerda), (voz alta), (pausa) — não existem em outros gêneros.'),
('interpretacao', 105, 'B', 'CL', 'Analise o trecho e identifique o gênero: "JOÃO (nervoso): Não posso acreditar nisso! / ANA: Calma, vamos conversar. / (Pausa. Olham-se em silêncio.)"', '[]', 'Gênero dramático — há personagens com falas marcadas por seus nomes e rubricas indicando emoção e ação.', 'Elementos do texto dramático: nomes dos personagens, diálogos e rubricas.'),
('interpretacao', 105, 'B', 'RF', 'Identifique a figura de linguagem e o efeito expressivo: "O amor é uma ferida que dói e não se sente."', '[]', 'Oxímoro (ou antítese): "dói e não se sente" — contradição que expressa a ambiguidade do amor, algo que causa sofrimento sem que o amante perceba ou queira parar.', 'Oxímoro: contradição aparente que revela uma verdade mais profunda.'),
('interpretacao', 105, 'B', 'DS', 'Compare dois textos — um narrativo e um argumentativo — sobre o mesmo tema: violência escolar.', '[]', 'Narrativo: "Um dia, Lucas chegou ao colégio e encontrou sua mochila rasgada. Seu coração apertou..." / Argumentativo: "A violência nas escolas é um problema grave que afeta o aprendizado e a saúde mental dos alunos. Dados do MEC mostram que..."', 'Mesmo tema, abordagens completamente diferentes.'),
('interpretacao', 105, 'B', 'MC', 'O que é a "voz passiva" num texto e qual seu efeito?', '["Quando o sujeito pratica a ação","Quando o sujeito sofre a ação, apagando o agente","Quando não há sujeito","Quando o verbo está no imperativo"]', 'Quando o sujeito sofre a ação, apagando o agente', 'Voz passiva: "A decisão foi tomada." — quem tomou? Apaga o agente, é recurso de impessoalidade.'),
('interpretacao', 105, 'B', 'VF', 'A escolha do registro formal ou informal depende do gênero, do público e do contexto de comunicação.', '[]', 'Verdadeiro', 'Carta para o presidente: formal. Mensagem para o amigo: informal. Contexto determina o registro.'),
('interpretacao', 105, 'B', 'CL', 'Identifique o registro (formal/informal) e justifique: "Prezado Senhor Diretor, venho por meio desta solicitar..." / "Ei, professor, posso sair?"', '[]', '"Prezado Senhor Diretor..." = formal (cargo, construção formal, vocabulário culto) / "Ei, professor..." = informal (interjeição, linguagem coloquial)', 'Registro adequado ao interlocutor e à situação.'),
('interpretacao', 105, 'B', 'RF', 'Reescreva a frase informal em registro formal: "Ei, ô chefe, aí a gente conseguiu terminar o projeto!"', '[]', '"Prezado Senhor [nome], informamos que concluímos com sucesso o projeto solicitado."', 'Transformar linguagem coloquial em formal: vocabulário culto + estrutura adequada.'),
('interpretacao', 105, 'B', 'MC', 'Qual recurso de leitura ajuda a compreender uma palavra desconhecida sem dicionário?', '["Ignorar a palavra","Usar o contexto e as palavras ao redor para inferir o significado","Parar de ler","Substituir por qualquer palavra"]', 'Usar o contexto e as palavras ao redor para inferir o significado', 'Inferência de vocabulário pelo contexto é estratégia fundamental de leitura.');

-- Nível 106A — Produção de textos diversos
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 106, 'A', 'MC', 'Ao escrever uma notícia, qual é a parte mais importante e deve responder às 6 perguntas?', '["manchete","lead (primeiro parágrafo)","colofão","editorial"]', 'lead (primeiro parágrafo)', 'Lead = primeiro parágrafo da notícia — responde ao quê, quem, quando, onde, por quê e como.'),
('interpretacao', 106, 'A', 'CL', 'Escreva um lead para a notícia: "Escola recebeu novos computadores para os alunos do ensino fundamental."', '[]', 'Exemplo: "A Escola Municipal Dom Pedro II recebeu, nesta segunda-feira, 30 novos computadores doados pelo governo estadual para uso dos alunos do ensino fundamental."', 'Lead: quem (escola), o quê (computadores), quando (segunda), quem deu (governo), para quem (alunos).'),
('interpretacao', 106, 'A', 'VF', 'A crônica mistura elementos narrativos e reflexivos sobre o cotidiano.', '[]', 'Verdadeiro', 'Crônica: parte de um fato cotidiano → desenvolve reflexão, humor ou crítica social.'),
('interpretacao', 106, 'A', 'RF', 'Escreva a abertura de uma crônica sobre "o primeiro dia de aula" (3-4 frases).', '[]', 'Exemplo: "Todo primeiro dia de aula tem esse cheiro peculiar: mistura de caderno novo, lousa limpa e expectativa. As crianças chegam com a mochila nova bem pesada e os olhos curiosos. É o dia em que tudo ainda pode acontecer."', 'Crônica: observação de detalhe cotidiano + reflexão leve e pessoal.'),
('interpretacao', 106, 'A', 'MC', 'Uma resenha crítica tem como objetivo:', '["narrar a história do livro inteira","avaliar e comentar uma obra, expressando a opinião do resenhista","apenas descrever a capa do livro","instruir como fazer algo"]', 'avaliar e comentar uma obra, expressando a opinião do resenhista', 'Resenha: apresenta + analisa + avalia a obra — texto crítico-informativo.'),
('interpretacao', 106, 'A', 'DS', 'Escreva uma resenha curta (3-4 frases) de um livro ou filme que você conhece.', '[]', 'Exemplo: "O Pequeno Príncipe, de Antoine de Saint-Exupéry, é uma obra que atravessa gerações com sua simplicidade e profundidade. A história de um príncipe de outro planeta que visita a Terra esconde reflexões sobre amor, amizade e o que realmente importa na vida. Recomendo a leitura para todas as idades — cada etapa da vida revela um novo sentido."', 'Resenha: apresentação + análise + avaliação + recomendação.'),
('interpretacao', 106, 'A', 'VF', 'Um resumo deve reproduzir as ideias principais do texto com as próprias palavras do leitor.', '[]', 'Verdadeiro', 'Resumo: síntese das ideias essenciais — sem copiar o original, sem acrescentar opiniões.'),
('interpretacao', 106, 'A', 'CL', 'Identifique qual é o gênero: "Instruções para montar o brinquedo" / "Carta para o vereador pedindo reforma da escola" / "Resenha do filme 'Moana'"', '[]', 'injuntivo (manual) / argumentativo (carta de reclamação/solicitação) / argumentativo-informativo (resenha)', 'Cada gênero tem propósito comunicativo diferente.'),
('interpretacao', 106, 'A', 'MC', 'Qual é a diferença entre um resumo e uma resenha?', '["São a mesma coisa","Resumo sintetiza sem opinar; resenha analisa e avalia com ponto de vista","Resumo é mais longo que a resenha","Resumo tem argumentos; resenha tem personagens"]', 'Resumo sintetiza sem opinar; resenha analisa e avalia com ponto de vista', 'Resumo = síntese objetiva. Resenha = análise crítica com opinião do resenhista.'),
('interpretacao', 106, 'A', 'DS', 'Escreva uma carta aberta à comunidade pedindo a criação de uma praça no bairro (4-5 frases).', '[]', 'Exemplo: "Prezados vizinhos e moradores, venho por meio desta carta propor a criação de uma praça pública em nosso bairro. A falta de espaços de lazer prejudica a qualidade de vida de todos, especialmente das crianças. Uma praça ofereceria área verde, convivência e atividade física para todas as faixas etárias. Convido todos a assinar o abaixo-assinado e levar nossa solicitação à Câmara Municipal."', 'Carta aberta: linguagem clara, argumentação, convocação à ação.'),

-- Nível 106B — Revisão geral de Interpretação
('interpretacao', 106, 'B', 'VF', 'O texto argumentativo e o informativo podem ser combinados numa reportagem.', '[]', 'Verdadeiro', 'Reportagem: informa (informativo) + interpreta + às vezes opina (argumentativo).'),
('interpretacao', 106, 'B', 'MC', 'Qual habilidade de leitura está sendo usada quando identificamos a ironia num texto?', '["leitura literal","leitura inferencial e interpretativa","decodificação fonética","leitura mecânica"]', 'leitura inferencial e interpretativa', 'Ironia exige leitura além do literal — inferência do sentido contrário ou subjacente.'),
('interpretacao', 106, 'B', 'CL', 'Para cada situação, indique o gênero mais adequado: pedir uma informação ao gerente do banco (___) / contar uma aventura vivida (___) / dar orientação a quem está doente (__)', '[]', 'e-mail ou carta formal / relato pessoal ou conto / texto injuntivo (orientação, bula, conselho)', 'A situação comunicativa determina o gênero mais adequado.'),
('interpretacao', 106, 'B', 'RF', 'Escreva um parágrafo argumentativo sobre "a importância de respeitar o meio ambiente" usando: tese + 2 argumentos (um de autoridade e um de causa-consequência) + conclusão.', '[]', 'Tese: Preservar o meio ambiente é dever de toda a humanidade. / Arg.1 (autoridade): Segundo o PNUMA, a biodiversidade está sendo perdida a um ritmo 1.000 vezes maior que o natural. / Arg.2 (causa-consequência): Se não agirmos, fenômenos como seca extrema e inundações se tornarão mais frequentes. / Conclusão: Portanto, cada escolha cotidiana — consumo consciente, reciclagem — contribui para a preservação do planeta.', 'Parágrafo argumentativo completo com dois tipos de argumento.'),
('interpretacao', 106, 'B', 'DS', 'Produza um texto de 5-6 frases no gênero que preferir (narrativo, descritivo, argumentativo ou informativo) e indique qual gênero usou e por quê.', '[]', 'Resposta livre — qualquer texto bem estruturado no gênero indicado é válido. A justificativa deve mencionar as características do gênero escolhido.', 'Produção textual autônoma com reflexão metalinguística.'),
('interpretacao', 106, 'B', 'MC', 'Qual recurso estilístico cria ritmo e musicalidade num poema?', '["vírgulas frequentes","rima e aliteração","uso de travessão","parágrafos longos"]', 'rima e aliteração', 'Rima (sons iguais no final dos versos) e aliteração (repetição de consoantes) criam musicalidade.'),
('interpretacao', 106, 'B', 'VF', 'A intertextualidade ocorre quando um texto faz referência, cita ou dialoga com outro texto.', '[]', 'Verdadeiro', '"Texto dentro do texto": paródia, citação, alusão são formas de intertextualidade.'),
('interpretacao', 106, 'B', 'CL', 'Identifique a intertextualidade: "Era uma vez um lobo que queria ser vegetariano." / "Veni, vidi, comprei no shopping."', '[]', '"lobo vegetariano" = paródia de Chapeuzinho Vermelho / "Veni, vidi, comprei" = paródia de "Veni, vidi, vici" (Júlio César)', 'Intertextualidade por paródia: recria texto conhecido com novo sentido.'),
('interpretacao', 106, 'B', 'RF', 'Escreva uma paródia de 2-3 versos de um poema ou texto famoso que você conhece.', '[]', 'Exemplo (paródia de "Canção do Exílio"): "Minha escola tem recreio / Onde toco futebol / As chuteiras que aqui uso / Não uso como lá, só."', 'Paródia recria o original com humor ou novo sentido — intertextualidade.'),
('interpretacao', 106, 'B', 'MC', 'Qual é o objetivo da paráfrase?', '["criar humor a partir de texto original","explicar ou reformular um texto com as próprias palavras sem mudar o sentido","copiar o texto original exatamente","contradizer o texto original"]', 'explicar ou reformular um texto com as próprias palavras sem mudar o sentido', 'Paráfrase: reformular mantendo o sentido. Diferente de plágio (copiar) e paródia (recriar com novo sentido).');

-- Nível 107A — Revisão Interpretação III (síntese geral)
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 107, 'A', 'MC', 'Qual tipo de texto predomina em "A Terra gira em torno do Sol a uma distância média de 150 milhões de km"?', '["narrativo","descritivo","argumentativo","informativo"]', 'informativo', 'Dado científico verificável, linguagem objetiva e impessoal = texto informativo.'),
('interpretacao', 107, 'A', 'CL', 'Analise o texto completo: "Todos deveriam praticar esportes. Estudos mostram que a atividade física regular reduz o risco de doenças crônicas em até 40%. Além disso, o esporte promove saúde mental e socialização. Portanto, políticas públicas de incentivo ao esporte são indispensáveis." — Identifique: tese, argumentos, conclusão.', '[]', 'Tese: Todos deveriam praticar esportes. / Arg.1: estudos (dado estatístico 40%). / Arg.2: saúde mental e socialização. / Conclusão: políticas públicas necessárias.', 'Análise da estrutura argumentativa completa.'),
('interpretacao', 107, 'A', 'VF', 'A leitura de diferentes gêneros e tipos de texto amplia a compreensão do mundo e o repertório do leitor.', '[]', 'Verdadeiro', 'Ler muito e variado é a melhor forma de aprimorar a leitura, a escrita e o pensamento crítico.'),
('interpretacao', 107, 'A', 'RF', 'Reescreva o trecho argumentativo em forma de texto informativo (sem opinião): "É inadmissível que crianças passem fome no Brasil, um país tão rico."', '[]', 'Exemplo: "O Brasil registra [X milhões de] pessoas em situação de insegurança alimentar, segundo dados da FAO. O país, apesar de ser um dos maiores produtores agropecuários do mundo, enfrenta desafios históricos na distribuição de renda e de alimentos."', 'Texto informativo: dados + objetividade + sem julgamento de valor.'),
('interpretacao', 107, 'A', 'MC', 'Qual alternativa descreve uma leitura CRÍTICA de um texto?', '["Ler sem questionar e aceitar tudo","Identificar a intenção do autor, avaliar os argumentos e considerar outras perspectivas","Ler apenas a introdução e a conclusão","Prestar atenção somente nas figuras de linguagem"]', 'Identificar a intenção do autor, avaliar os argumentos e considerar outras perspectivas', 'Leitura crítica: ativa, questionadora, contextualizada.'),
('interpretacao', 107, 'A', 'DS', 'Escreva um texto narrativo curto (5-6 frases) que também contenha uma argumentação implícita (moral ou mensagem).', '[]', 'Exemplo: "Uma formiguinha carregava grãos enquanto os gafanhotos dançavam no calor do verão. No inverno, a formiga estava aquecida e bem alimentada, enquanto os gafanhotos tremiam de frio. A história não precisa de conclusão — ela fala por si mesma sobre a importância do trabalho e da previsão."', 'Narrativa com moral implícita = argumentação embutida.'),
('interpretacao', 107, 'A', 'VF', 'Resumir um texto com as próprias palavras demonstra compreensão real do conteúdo.', '[]', 'Verdadeiro', 'Parafrasear exige entendimento profundo — não é possível sem compreender o original.'),
('interpretacao', 107, 'A', 'CL', 'Analise a coesão: "Ela estudou muito. Com isso, foi aprovada. O resultado a encheu de alegria. A conquista foi celebrada em família."', '[]', '"Com isso" = conector (referência ao estudo) / "O resultado" = retomada anafórica do "foi aprovada" / "A conquista" = sinônimo de "foi aprovada" — coesão referencial variada', 'Texto coeso com múltiplos recursos: conector + anáfora + sinônimo.'),
('interpretacao', 107, 'A', 'MC', 'Qual é o objetivo da leitura de fruição (leitura por prazer)?', '["Coletar dados para pesquisa","Decorar o texto","Sentir prazer estético, ampliar imaginação e empatia","Identificar erros gramaticais"]', 'Sentir prazer estético, ampliar imaginação e empatia', 'Leitura de fruição: não tem objetivo utilitário — é leitura pelo prazer e enriquecimento pessoal.'),
('interpretacao', 107, 'A', 'DS', 'Descreva 5 hábitos de um bom leitor, relacionando cada um com uma habilidade de leitura.', '[]', '1. Ler com atenção → concentração / 2. Fazer perguntas ao texto → leitura crítica / 3. Relacionar com outros textos → intertextualidade / 4. Reler trechos difíceis → estratégia de compreensão / 5. Registrar ideias → síntese e memória', 'Leitor ativo: usa múltiplas estratégias durante a leitura.'),

-- Nível 107B — Revisão Interpretação IV (síntese e produção)
('interpretacao', 107, 'B', 'VF', 'A variação linguística (regional, social, histórica) deve ser conhecida e respeitada.', '[]', 'Verdadeiro', 'Variações linguísticas fazem parte da riqueza do idioma — "certo" vs. "errado" depende do contexto.'),
('interpretacao', 107, 'B', 'MC', 'O que é adequação linguística?', '["usar sempre a mesma linguagem em qualquer situação","adaptar o registro (formal/informal) ao contexto, ao gênero e ao interlocutor","escrever sempre de forma coloquial","evitar figuras de linguagem"]', 'adaptar o registro (formal/informal) ao contexto, ao gênero e ao interlocutor', 'Adequação: cada situação pede um registro. Carta formal ≠ conversa informal.'),
('interpretacao', 107, 'B', 'CL', 'Identifique o tipo de variação linguística: "Oxente!" (nordestino) / "Bah tchê!" (gaúcho) / "trem" (mineiro, no sentido de coisa)', '[]', 'variação regional (dialetal) — cada região tem expressões próprias que enriquecem o português brasileiro', 'Variações regionais são legítimas e não são "erros" — são identidade cultural.'),
('interpretacao', 107, 'B', 'RF', 'Reescreva em linguagem formal: "Aí, mano, essa prova foi difícil demais da conta, viu?"', '[]', '"A avaliação aplicada apresentou alto grau de dificuldade." ou "Confesso que a prova foi bastante desafiadora."', 'Adaptar linguagem coloquial ao registro formal sem perder o sentido.'),
('interpretacao', 107, 'B', 'DS', 'Escreva um texto de 5-7 frases mostrando domínio de: tipo de texto à escolha + pelo menos 1 figura de linguagem + 2 conectores de coesão.', '[]', 'Resposta livre — válida se apresentar o tipo correto, 1 figura e 2 conectores identificáveis. Ex. argumentativo: "A internet transformou o mundo. Por um lado, facilita o acesso à informação como nunca antes. Por outro, é um oceano de desinformação. Portanto, a educação midiática tornou-se tão essencial quanto a leitura e a escrita."', 'Síntese de todo o módulo: tipos de texto + figuras + coesão.'),
('interpretacao', 107, 'B', 'MC', 'Qual das características abaixo é exclusiva do texto poético?', '["uso de dados estatísticos","presença de versos e estrofes","estrutura de tese e argumentos","uso de verbos no imperativo"]', 'presença de versos e estrofes', 'Versos e estrofes são elementos formais exclusivos do texto poético.'),
('interpretacao', 107, 'B', 'VF', 'A compreensão leitora melhora com a prática regular de leitura variada.', '[]', 'Verdadeiro', 'Leitura regular e diversificada desenvolve vocabulário, fluência e habilidades interpretativas.'),
('interpretacao', 107, 'B', 'CL', 'Analise o seguinte título de texto: "A tecnologia: solução ou problema?" — O que o título sugere sobre o tipo de texto?', '[]', 'Sugere texto argumentativo — apresenta uma questão em aberto (solução ou problema?) que será discutida. Indica que o autor tomará uma posição sobre o tema.', 'O título com pergunta ou contraposição anuncia texto argumentativo.'),
('interpretacao', 107, 'B', 'RF', 'Escreva um parágrafo de conclusão para o tema "A importância da leitura na era digital."', '[]', 'Exemplo: "Em síntese, a leitura continua sendo uma habilidade fundamental na era digital, talvez mais do que nunca. Navegar nas redes sociais, avaliar notícias e compreender textos complexos exigem leitores críticos e capacitados. Investir na formação de leitores desde a infância é o melhor caminho para uma sociedade mais consciente e preparada para os desafios do século XXI."', 'Conclusão: síntese + proposta de ação + perspectiva de futuro.'),
('interpretacao', 107, 'B', 'MC', 'Qual é a função social da literatura?', '["apenas entreter o leitor","humanizar, desenvolver empatia, preservar a memória cultural e ampliar a visão de mundo","ensinar regras gramaticais","informar sobre eventos atuais"]', 'humanizar, desenvolver empatia, preservar a memória cultural e ampliar a visão de mundo', 'Literatura vai além do entretenimento: é forma de conhecimento, expressão e humanização.');
