-- ============================================================
-- GeraFicha — Módulo 3: Classes de Palavras
-- Níveis 61–72 | Séries A e B
-- ============================================================

-- Nível 61A — Interjeições e locuções
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 61, 'A', 'MC', 'Interjeições são palavras que expressam:', '["quantidade","emoções e sentimentos de forma exclamativa","qualidades dos seres","ações praticadas"]', 'emoções e sentimentos de forma exclamativa', 'Interjeições como "Ah!", "Uau!", "Ai!" expressam emoções de forma imediata e exclamativa.'),
('classes', 61, 'A', 'CL', 'Classifique a emoção expressa pela interjeição: Bravo! (___) / Ai! (___) / Silêncio! (___) / Ufa! (___)', '[]', 'aprovação / dor / ordem/pedido / alívio', 'Cada interjeição expressa uma emoção ou reação diferente.'),
('classes', 61, 'A', 'VF', 'Interjeições são sempre seguidas de ponto de exclamação.', '[]', 'Falso', 'Geralmente sim, mas podem vir com vírgula ou ponto final dependendo do contexto: "Ah, que saudade."'),
('classes', 61, 'A', 'RF', 'Escreva uma interjeição adequada para cada situação: surpresa → ___ / dor → ___ / alívio → ___', '[]', 'Surpresa: Uau! / Dor: Ai! / Alívio: Ufa!', 'Qualquer interjeição que expresse a emoção pedida é válida.'),
('classes', 61, 'A', 'MC', '"Psiu!" é uma interjeição que indica:', '["alegria","pedido de silêncio","dor","cumprimento"]', 'pedido de silêncio', 'Psiu! é usada para pedir silêncio ou chamar atenção de alguém.'),
('classes', 61, 'A', 'DS', 'Escreva 5 interjeições diferentes e o sentimento que cada uma expressa.', '[]', 'Exemplos: Ah! (surpresa/admiração) / Ui! (dor/susto) / Oba! (alegria) / Caramba! (espanto) / Eca! (nojo)', 'Interjeições são muito usadas na linguagem oral e informal.'),
('classes', 61, 'A', 'VF', '"Nossa!" e "Caramba!" são interjeições.', '[]', 'Verdadeiro', 'Nossa e caramba expressam surpresa ou espanto — são interjeições.'),
('classes', 61, 'A', 'CL', 'Separe interjeições das outras classes: Ai! — lindo — Bravo! — correu — Silêncio! — mesa', '[]', 'Interjeições: Ai!, Bravo!, Silêncio! | Outras: lindo (adj.), correu (verbo), mesa (subst.)', 'Interjeições se distinguem pelas emoções que expressam e geralmente pelo ponto de exclamação.'),
('classes', 61, 'A', 'MC', 'Uma locução verbal é formada por:', '["dois ou mais substantivos","verbo auxiliar + verbo principal","adjetivo + advérbio","preposição + pronome"]', 'verbo auxiliar + verbo principal', 'Locução verbal: "estava estudando", "vai chover", "tem chegado".'),
('classes', 61, 'A', 'DS', 'Escreva 3 frases com locuções verbais diferentes.', '[]', 'Exemplos: Ela estava dormindo. / Ele vai viajar. / Nós temos trabalhado muito.', 'Locuções verbais expressam aspecto, modo ou tempo de forma mais precisa.'),

-- Nível 61B — Interjeições e locuções
('classes', 61, 'B', 'VF', '"Que pena!" é uma locução interjetiva (grupo de palavras com valor de interjeição).', '[]', 'Verdadeiro', 'Que pena!, Meu Deus!, Que saudade! são locuções interjetivas — funcionam como interjeições.'),
('classes', 61, 'B', 'MC', 'Qual é uma locução interjetiva?', '["correr rápido","Meu Deus!","estuda sempre","casa bonita"]', 'Meu Deus!', '"Meu Deus!" é uma locução interjetiva — grupo de palavras com função de interjeição.'),
('classes', 61, 'B', 'CL', 'Identifique a locução e sua classe: "estava estudando" (___) / "muito bonito" (___) / "por causa de" (___)', '[]', 'locução verbal / locução adjetiva (ou adverbial de intensidade) / locução prepositiva', 'Locuções são grupos de palavras que funcionam como uma só classe gramatical.'),
('classes', 61, 'B', 'RF', 'Reescreva usando locução verbal equivalente ao verbo simples: "Ela dorme cedo." → "Ela ___ dormindo cedo."', '[]', 'Ela está dormindo cedo.', '"Está dormindo" é a locução verbal equivalente (verbo estar + gerúndio).'),
('classes', 61, 'B', 'DS', 'Explique o que é uma locução adjetiva com 3 exemplos.', '[]', 'Locução adjetiva = grupo de palavras que funciona como adjetivo, geralmente "de + substantivo". Ex: de pedra (pétrea), de ouro (áureo), de criança (infantil)', 'Locuções adjetivas substituem adjetivos de origem latina.'),
('classes', 61, 'B', 'MC', 'A locução adjetiva "de leite" equivale ao adjetivo:', '["leiteiro","lácteo","leitoso","lacticínio"]', 'lácteo', '"De leite" = lácteo (adjetivo de origem latina). Ex: produto lácteo.'),
('classes', 61, 'B', 'VF', 'Locuções prepositivas são formadas por duas ou mais palavras com valor de preposição.', '[]', 'Verdadeiro', '"Por causa de", "a fim de", "em vez de" são locuções prepositivas.'),
('classes', 61, 'B', 'CL', 'Identifique se é locução verbal (LV) ou interjeição (I): "estava cantando" / "Que maravilha!" / "vai estudar" / "Ufa!"', '[]', 'LV / I / LV / I', 'Locuções verbais são conjuntos de verbos; interjeições expressam emoções.'),
('classes', 61, 'B', 'RF', 'Escreva a locução adjetiva equivalente: silvestre (___) / aquático (___) / noturno (___)', '[]', 'de selva/mato / de água / de noite', 'Adjetivos eruditos têm locuções adjetivas equivalentes mais simples.'),
('classes', 61, 'B', 'MC', 'Em "Ela tem estudado muito", a locução verbal indica:', '["ação futura","ação concluída há muito tempo","ação que se repete com frequência no passado recente","ação impossível"]', 'ação que se repete com frequência no passado recente', '"Ter + particípio" (pretérito perfeito composto) indica ação repetida que começou no passado.');

-- Nível 62A — Concordância nominal
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 62, 'A', 'MC', 'Concordância nominal é o ajuste de:', '["verbo com sujeito","adjetivo/artigo com o substantivo","sujeito com predicado","pronome com verbo"]', 'adjetivo/artigo com o substantivo', 'Concordância nominal: artigos, adjetivos, pronomes e numerais concordam com o substantivo em gênero e número.'),
('classes', 62, 'A', 'CL', 'Corrija a concordância: "O meninas bonito correram." → ___', '[]', 'As meninas bonitas correram.', 'Meninas = feminino plural → as (artigo fem. pl.) + bonitas (adj. fem. pl.).'),
('classes', 62, 'A', 'VF', '"Os livros novos" está na concordância correta.', '[]', 'Verdadeiro', 'Livros (masc. pl.) → os (artigo masc. pl.) + novos (adj. masc. pl.) — concordância perfeita.'),
('classes', 62, 'A', 'RF', 'Faça a concordância nominal correta: "Ela é muito ___ (inteligente/inteligentes)." / "Os alunos foram ___ (aprovado/aprovados)."', '[]', 'inteligente / aprovados', 'Inteligente é invariável no gênero. Aprovados concorda com alunos (masc. pl.).'),
('classes', 62, 'A', 'MC', 'Em "Ela está cansada", o adjetivo "cansada" concorda com:', '["está","cansado","ela","o verbo"]', 'ela', 'Cansada (fem.) concorda com ela (fem.) — concordância nominal do predicativo.'),
('classes', 62, 'A', 'DS', 'Reescreva no plural mantendo a concordância: "A menina bonita chegou."', '[]', 'As meninas bonitas chegaram.', 'Meninas (pl.) → as + bonitas. Chegaram concorda com o sujeito no plural.'),
('classes', 62, 'A', 'VF', 'Adjetivos invariáveis (como "feliz", "simples", "ágil") não mudam no feminino.', '[]', 'Verdadeiro', 'Feliz, simples e ágil não mudam de forma no feminino — são invariáveis no gênero.'),
('classes', 62, 'A', 'CL', 'Corrija ou confirme: "O aluno feliz." / "A aluna felizes." / "Os meninos felizes."', '[]', 'O aluno feliz. ✓ / A aluna feliz. (felizes ✗) / Os meninos felizes. ✓', 'Aluna é singular → feliz (singular). Felizes só no plural.'),
('classes', 62, 'A', 'MC', 'Qual frase tem concordância nominal INCORRETA?', '["As flores bonitas murcharam.","Os livro velho estão na mesa.","Ela ficou contente com o resultado.","Meus dois filhos estudam aqui."]', 'Os livro velho estão na mesa.', 'Livro (singular) deveria ser livros (plural); velho → velhos. Correto: Os livros velhos estão na mesa.'),
('classes', 62, 'A', 'DS', 'Escreva a frase no masculino e no feminino: "O aluno dedicado foi aprovado."', '[]', 'Masculino: O aluno dedicado foi aprovado. / Feminino: A aluna dedicada foi aprovada.', 'Todos os termos que concordam com o substantivo mudam de gênero.'),

-- Nível 62B — Concordância nominal
('classes', 62, 'B', 'VF', 'Quando um adjetivo qualifica dois substantivos de gêneros diferentes, fica no masculino plural.', '[]', 'Verdadeiro', 'Ex: "O pai e a mãe estavam preocupados" — preocupados (masc. pl.) porque inclui masc.'),
('classes', 62, 'B', 'MC', 'Qual a concordância correta do adjetivo em "O pai e a mãe ficaram ___"?', '["preocupado","preocupada","preocupados","preocupadas"]', 'preocupados', 'Dois sujeitos (masc. + fem.) → adjetivo no masculino plural.'),
('classes', 62, 'B', 'CL', 'Corrija todos os erros: "Minhas dois filha caçula estão doente."', '[]', 'Minha(s) duas filhas caçulas estão doentes.', 'Minhas (fem. pl.) / duas (numeral fem. pl.) / filhas (fem. pl.) / caçulas (fem. pl.) / doentes (pl.).'),
('classes', 62, 'B', 'RF', 'Reescreva no singular: "As crianças animadas brincavam felizes no parque."', '[]', 'A criança animada brincava feliz no parque.', 'Crianças → criança; animadas → animada; felizes → feliz (invariável no gênero mas muda no número).'),
('classes', 62, 'B', 'DS', 'Explique por que "É proibido a entrada" está errado e corrija.', '[]', '"Proibido" deve concordar com "entrada" (fem.): É proibida a entrada. Ou: É proibido entrar (verbo no infinitivo).', 'Quando o sujeito é substantivo feminino, o predicativo fica no feminino.'),
('classes', 62, 'B', 'MC', '"Elas estão muito cansadas" — o adjetivo "cansadas" concorda com:', '["estão","muito","elas","cansadas"]', 'elas', 'Cansadas (fem. pl.) concorda com o pronome sujeito elas (fem. pl.).'),
('classes', 62, 'B', 'VF', '"Meio" como advérbio de intensidade é invariável: "Ela está meio cansada."', '[]', 'Verdadeiro', 'Quando "meio" modifica adjetivo (= um pouco), é advérbio invariável: ela está meio cansada.'),
('classes', 62, 'B', 'CL', 'Identifique se a concordância está correta ou errada: "Água e suco gelado." / "Água e suco gelados."', '[]', '"Gelado" = pode concordar só com o mais próximo (suco). "Gelados" = concorda com os dois. Ambas aceitas.', 'Quando o adjetivo vem depois de vários substantivos, pode concordar com o mais próximo ou com todos.'),
('classes', 62, 'B', 'RF', 'Complete com a forma correta do adjetivo: "A professora ficou ___ (satisfeito)." / "Os alunos foram ___ (dedicado)."', '[]', 'satisfeita / dedicados', 'Satisfeita concorda com professora (fem. sing.); dedicados com alunos (masc. pl.).'),
('classes', 62, 'B', 'MC', 'Qual frase apresenta concordância nominal correta?', '["As meninas estão animadas.","O menino e a menina estava animado.","As flores bonito estão na mesa.","Meu duas filha viajaram."]', 'As meninas estão animadas.', 'Meninas (fem. pl.) + animadas (fem. pl.) — concordância perfeita.');

-- Nível 63A — Concordância verbal
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 63, 'A', 'MC', 'Concordância verbal é o ajuste de:', '["adjetivo com substantivo","verbo com seu sujeito","artigo com pronome","advérbio com verbo"]', 'verbo com seu sujeito', 'O verbo concorda em número e pessoa com o sujeito da oração.'),
('classes', 63, 'A', 'VF', '"Os alunos chegaram cedo" — a concordância verbal está correta.', '[]', 'Verdadeiro', 'Alunos (3ª pessoa do plural) → chegaram (3ª pessoa do plural). Concordância correta.'),
('classes', 63, 'A', 'RF', 'Faça o verbo concordar com o sujeito: "As crianças ___ (brincar) no parque." / "O professor ___ (chegar) tarde."', '[]', 'brincaram (ou brincam) / chegou (ou chega)', 'Crianças = 3ª pessoa plural; professor = 3ª pessoa singular.'),
('classes', 63, 'A', 'MC', '"Eu e meus amigos fomos ao cinema." O verbo está na:', '["1ª pessoa singular","2ª pessoa plural","1ª pessoa plural","3ª pessoa plural"]', '1ª pessoa plural', 'Eu + meus amigos = nós → 1ª pessoa plural → fomos.'),
('classes', 63, 'A', 'CL', 'Corrija a concordância verbal: "Os meninos foi ao parque." / "Ela chegaram cedo."', '[]', 'Os meninos foram ao parque. / Ela chegou cedo.', 'Meninos (pl.) → foram; ela (sing.) → chegou.'),
('classes', 63, 'A', 'DS', 'Explique por que "A maioria dos alunos faltou" e "A maioria dos alunos faltaram" são ambas possíveis.', '[]', '"Faltou" concorda com maioria (singular). "Faltaram" concorda com alunos (plural — concordância atrativa). Ambas são aceitas pela gramática.', 'Com expressões partitivas como "a maioria de", a concordância pode ser singular ou plural.'),
('classes', 63, 'A', 'VF', '"Faz dois anos que não te vejo." O verbo "faz" está correto.', '[]', 'Verdadeiro', 'Verbos que exprimem tempo transcorrido são impessoais — ficam sempre no singular.'),
('classes', 63, 'A', 'MC', 'Qual frase tem concordância verbal INCORRETA?', '["Nós estudamos muito.","Ele e ela foram ao mercado.","As flores está bonitas.","Tu vieste cedo."]', 'As flores está bonitas.', 'Flores é plural → deveriam estar (plural). Correto: As flores estão bonitas.'),
('classes', 63, 'A', 'CL', 'Conjugue na pessoa correta: "Eu e você ___ (precisar) estudar." / "Tu ___ (ter) razão."', '[]', 'precisamos / tens', 'Eu + você = nós → precisamos; tu → tens.'),
('classes', 63, 'A', 'RF', 'Reescreva corrigindo: "Meu amigo e eu foi ao shopping ontem."', '[]', 'Meu amigo e eu fomos ao shopping ontem.', 'Meu amigo + eu = nós → fomos (1ª pessoa plural).'),

-- Nível 63B — Concordância verbal
('classes', 63, 'B', 'VF', '"Há muitos anos" usa "há" porque é verbo haver impessoal.', '[]', 'Verdadeiro', '"Há" (haver) quando indica tempo ou existência é impessoal — sempre singular.'),
('classes', 63, 'B', 'MC', 'Em "Existem muitas soluções", o verbo concorda com:', '["existem","muitas","soluções","o sujeito implícito"]', 'soluções', 'Soluções é o sujeito (posposto) — existem concorda com ele no plural.'),
('classes', 63, 'B', 'CL', 'Corrija: "Fazem três anos que não chove." / "Haviam muitas pessoas na festa."', '[]', '"Faz três anos..." (impessoal, singular) / "Havia muitas pessoas..." (haver impessoal, singular)', 'Fazer e haver quando impessoais ficam sempre no singular.'),
('classes', 63, 'B', 'RF', 'Complete com o verbo na forma correta: "Um ou outro aluno ___ (precisar) de ajuda." / "Nem ele nem ela ___ (chegar) ainda."', '[]', 'precisa (sujeito composto com ou → singular — mais próximo) / chegou (nem...nem → mais próximo)', 'Com sujeitos alternativos (ou, nem...nem), o verbo pode concordar com o mais próximo.'),
('classes', 63, 'B', 'DS', 'Escreva 2 exemplos de concordância verbal com sujeito composto (dois sujeitos + verbo).', '[]', 'Exemplos: João e Maria foram ao parque. / O sol e a lua iluminam o mundo.', 'Sujeito composto com e → verbo no plural.'),
('classes', 63, 'B', 'MC', '"Mais de um aluno errou a prova." A concordância está:', '["errada — deveria ser erraram","correta","errada — deveria ser errara","errada — deveria ser errassem"]', 'correta', '"Mais de um" geralmente pede o verbo no singular, apesar do sentido plural.'),
('classes', 63, 'B', 'VF', '"Todo mundo foram embora" está incorreto.', '[]', 'Verdadeiro', '"Todo mundo" é singular → foi embora. Correto: Todo mundo foi embora.'),
('classes', 63, 'B', 'CL', 'Corrija as 3 frases: "Nós vai sair." / "Tu foste ontem?" / "Eles estudaram bastante."', '[]', '"Nós vamos sair." (✗ → vamos) / "Tu foste ontem?" (✓) / "Eles estudaram bastante." (✓)', 'Nós → vamos (não vai). As demais estão corretas.'),
('classes', 63, 'B', 'RF', 'Reescreva no plural: "O aluno dedicado foi aprovado no exame."', '[]', 'Os alunos dedicados foram aprovados no exame.', 'Alunos (pl.) → os + dedicados + foram + aprovados — todos concordam no plural.'),
('classes', 63, 'B', 'MC', 'Qual é a concordância correta para sujeito coletivo? "A multidão ___ (gritar)."', '["gritaram","gritou","gritaras","gritaste"]', 'gritou', 'Sujeito coletivo (multidão = singular) → verbo no singular: gritou.');

-- Nível 64A — Regência verbal básica
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 64, 'A', 'MC', 'Regência verbal trata da relação entre:', '["sujeito e predicado","verbo e seus complementos","adjetivo e substantivo","advérbio e verbo"]', 'verbo e seus complementos', 'Regência verbal estuda a relação do verbo com seus complementos (objeto direto e indireto).'),
('classes', 64, 'A', 'VF', 'O verbo "gostar" exige complemento com preposição "de": "Gosto de música."', '[]', 'Verdadeiro', '"Gostar" é transitivo indireto — pede complemento introduzido por "de".'),
('classes', 64, 'A', 'RF', 'Complete com a preposição correta (ou sem preposição): "Preciso ___ ajuda." / "Assisti ___ o filme." / "Vi ___ você."', '[]', 'de ajuda / Assisti ao filme (a + o) / Vi você (sem preposição)', '"Precisar de", "assistir a" (TV/espetáculo), "ver" (transitivo direto).'),
('classes', 64, 'A', 'MC', 'O verbo "amar" exige:', '["complemento com de","complemento com a","complemento sem preposição","não exige complemento"]', 'complemento sem preposição', '"Amar" é transitivo direto: "Amo você" (sem preposição).'),
('classes', 64, 'A', 'CL', 'Classifique o verbo em TD (transitivo direto) ou TI (transitivo indireto): gostar / comprar / precisar / ver', '[]', 'TI / TD / TI / TD', 'Gostar (de) e precisar (de) são TI; comprar e ver são TD.'),
('classes', 64, 'A', 'DS', 'Escreva uma frase com cada verbo, usando a regência correta: obedecer / assistir (espetáculo) / encontrar', '[]', 'Exemplos: Obedeça aos seus pais. / Assistimos ao show. / Encontrei meu amigo.', 'Obedecer a, assistir a (espetáculo), encontrar (sem preposição).'),
('classes', 64, 'A', 'VF', '"Ir" pede complemento com a preposição "a": "Fui à escola."', '[]', 'Verdadeiro', 'Ir é transitivo indireto — pede complemento com "a": fui à praia, fui à escola.'),
('classes', 64, 'A', 'MC', '"Ele chegou ___ casa cedo." A preposição correta é:', '["à","de","em","a"]', 'em', '"Chegar em" é o uso popular aceito. Formalmente: "chegou a casa" — mas "em" é amplamente aceito no Brasil.'),
('classes', 64, 'A', 'CL', 'Identifique se o verbo é intransitivo (I) ou transitivo (T): chover / comprar / dormir / gostar', '[]', 'I / T / I / T', 'Chover e dormir não exigem complemento (I); comprar e gostar exigem (T).'),
('classes', 64, 'A', 'RF', 'Reescreva usando a regência correta: "Eu prefiro ___ piano ___ guitarra." (preferir... a)', '[]', 'Eu prefiro o piano à guitarra.', '"Preferir" pede complemento com "a": prefiro X a Y.'),

-- Nível 64B — Regência verbal básica
('classes', 64, 'B', 'VF', '"Informar" pode ser usado de duas formas: "informar algo a alguém" e "informar alguém de algo".', '[]', 'Verdadeiro', '"Informar" admite dupla regência: "Informei o resultado ao diretor" ou "Informei o diretor do resultado."'),
('classes', 64, 'B', 'MC', 'Qual é a regência correta de "obedecer"?', '["obedecer alguém (TD)","obedecer a alguém (TI)","obedecer de alguém","obedecer em alguém"]', 'obedecer a alguém (TI)', 'Obedecer é transitivo indireto: "Obedece aos pais", "obedece às regras."'),
('classes', 64, 'B', 'CL', 'Corrija a regência: "Assisti o filme." / "Obedeci minha mãe." / "Precisei dinheiro."', '[]', 'Assisti ao filme. / Obedeci à minha mãe. / Precisei de dinheiro.', 'Assistir a, obedecer a, precisar de — regências obrigatórias.'),
('classes', 64, 'B', 'RF', 'Complete com preposição (se necessário): "Ela gosta ___ cantar." / "Eu comprei ___ livro." / "Ele foi ___ a escola."', '[]', 'de cantar / comprei o livro (sem prep.) / foi à escola', 'Gostar de, comprar (TD, sem prep.), ir a.'),
('classes', 64, 'B', 'DS', 'Explique a diferença de sentido entre "custar caro" e "me custou entender".', '[]', '"Custar caro" = ser caro (transitivo direto). "Me custou entender" = foi difícil para mim (custar = ser difícil, com objeto indireto).', 'Custar tem regências e sentidos diferentes conforme o uso.'),
('classes', 64, 'B', 'MC', '"Lembrar" como transitivo direto é usado da seguinte forma:', '["Eu lembro de você","Eu me lembro de você","Eu lembro você","Eu lembro a você"]', 'Eu lembro você', '"Lembrar" TD = "Lembro você" (sem preposição). "Lembrar-se de" = TI com "de".'),
('classes', 64, 'B', 'VF', '"Chegar a" e "ir a" expressam a mesma ideia de destino.', '[]', 'Verdadeiro', 'Chegar a / ir a — ambos indicam destino: "Chegou ao parque" = "Foi ao parque".'),
('classes', 64, 'B', 'CL', 'Identifique a regência e corrija se errado: "Respondei a pergunta." / "Ele aspirava o cargo."', '[]', '"Responder à pergunta" (responder a = TI). / "Ele aspirava ao cargo" (aspirar a = TI, no sentido de desejar).', 'Responder e aspirar (desejar) são transitivos indiretos.'),
('classes', 64, 'B', 'RF', 'Escreva 2 frases usando "amar" (TD) e 2 usando "gostar" (TI).', '[]', 'TD: Amo minha família. / Ele ama a música. / TI: Gosto de estudar. / Ela gosta de arte.', 'Amar não pede preposição; gostar pede "de".'),
('classes', 64, 'B', 'MC', 'Verbos intransitivos:', '["sempre pedem complemento","nunca pedem complemento","pedem complemento com preposição","pedem só objeto direto"]', 'nunca pedem complemento', 'Verbos intransitivos têm sentido completo por si mesmos: "Ela dorme." / "Chove."');

-- Nível 65A — Análise morfológica
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 65, 'A', 'MC', 'Análise morfológica consiste em:', '["identificar a função de uma oração","identificar a classe e as flexões de cada palavra","analisar o significado do texto","separar o texto em parágrafos"]', 'identificar a classe e as flexões de cada palavra', 'Morfologia estuda as palavras isoladas: classe, gênero, número, pessoa, tempo, modo, etc.'),
('classes', 65, 'A', 'CL', 'Analise morfologicamente cada palavra: "Os meninos correram rapidamente."', '[]', 'Os = artigo definido masc. pl. / meninos = subst. comum masc. pl. / correram = verbo correr, 3ª p. pl., passado perf. / rapidamente = advérbio de modo', 'Análise morfológica completa descreve cada palavra com sua classe e flexões.'),
('classes', 65, 'A', 'VF', 'O estudo das flexões (gênero, número, grau, tempo, modo) faz parte da morfologia.', '[]', 'Verdadeiro', 'Morfologia inclui as flexões das palavras variáveis: substantivos, adjetivos, verbos e pronomes.'),
('classes', 65, 'A', 'RF', 'Identifique o grau do adjetivo: "bom → melhor → ótimo" — explique cada grau.', '[]', 'Bom = grau normal / melhor = grau comparativo de superioridade (irregular) / ótimo = grau superlativo absoluto sintético (irregular)', 'Os graus do adjetivo indicam a intensidade da qualidade.'),
('classes', 65, 'A', 'MC', '"Grande → grandíssimo" é um exemplo de superlativo:', '["relativo de superioridade","relativo de inferioridade","absoluto sintético","absoluto analítico"]', 'absoluto sintético', 'Superlativo absoluto sintético é formado com sufixo (-íssimo): grande → grandíssimo.'),
('classes', 65, 'A', 'DS', 'Forme o superlativo absoluto sintético de: fácil / bom / mau / grande / pequeno', '[]', 'facilíssimo / ótimo (irregular) / péssimo (irregular) / grandíssimo / pequeníssimo', 'Bom e mau têm superlativos irregulares: ótimo e péssimo.'),
('classes', 65, 'A', 'VF', '"Mais bonito que" é superlativo relativo de superioridade.', '[]', 'Verdadeiro', 'Superlativo relativo de superioridade: mais + adjetivo + que/do que.'),
('classes', 65, 'A', 'CL', 'Classifique o grau do adjetivo: "O teste foi difícil." / "Este é o mais difícil de todos." / "Foi dificílimo."', '[]', 'grau normal / superlativo relativo de superioridade / superlativo absoluto sintético', 'Três graus diferentes de "difícil" na análise morfológica.'),
('classes', 65, 'A', 'MC', 'O grau comparativo de igualdade é formado com:', '["mais...que","tão...quanto/como","menos...que","o mais...de"]', 'tão...quanto/como', '"Tão alto quanto" / "tão bonita como" — comparativo de igualdade.'),
('classes', 65, 'A', 'DS', 'Escreva os 3 graus comparativos de "bom": superioridade, igualdade, inferioridade.', '[]', 'Superioridade: melhor que (irregular) / Igualdade: tão bom quanto / Inferioridade: menos bom que', 'Bom tem comparativo irregular de superioridade: melhor (não "mais bom").'),

-- Nível 65B — Análise morfológica
('classes', 65, 'B', 'VF', '"Belíssimo" é o superlativo absoluto sintético de "belo".', '[]', 'Verdadeiro', 'Belo → belíssimo (sufixo -íssimo aplicado ao radical bel-).'),
('classes', 65, 'B', 'MC', 'Qual é o comparativo irregular de "mau"?', '["mais mau","mauíssimo","pior","péssimo"]', 'pior', 'Pior é o comparativo de superioridade de mau (irregular). Péssimo é o superlativo.'),
('classes', 65, 'B', 'CL', 'Analise o modo e tempo de cada verbo: "cantaria / cante / cantei / cantava"', '[]', 'cantaria = indicativo, futuro do pretérito / cante = subjuntivo, presente / cantei = indicativo, pretérito perfeito / cantava = indicativo, pretérito imperfeito', 'A análise verbal inclui modo e tempo verbais.'),
('classes', 65, 'B', 'RF', 'Complete a análise morfológica de "rapidamente": classe → ___ / formação → ___ / tipo → ___', '[]', 'advérbio / rápida + -mente (adjetivo fem. + sufixo) / modo', '"Rapidamente" é advérbio de modo formado por adjetivo feminino + -mente.'),
('classes', 65, 'B', 'DS', 'Faça a análise morfológica completa de "eles": classe / tipo / pessoa / número', '[]', 'pronome pessoal / reto / 3ª pessoa / plural', 'Eles: pronome pessoal do caso reto, 3ª pessoa do plural.'),
('classes', 65, 'B', 'MC', 'O plural de "cidadão" é "cidadãos". Qual é a análise morfológica de "cidadãos"?', '["substantivo próprio masc. pl.","substantivo comum masc. pl.","pronome masc. pl.","adjetivo masc. pl."]', 'substantivo comum masc. pl.', 'Cidadãos é substantivo comum (designa qualquer habitante de uma cidade), masculino, plural.'),
('classes', 65, 'B', 'VF', 'A análise morfológica de "muito" em "muito bonito" seria: advérbio de intensidade.', '[]', 'Verdadeiro', '"Muito" modifica o adjetivo "bonito" com função de advérbio de intensidade.'),
('classes', 65, 'B', 'CL', 'Analise as flexões de "fomos": verbo / modo / tempo / pessoa / número', '[]', 'verbo ir / modo indicativo / pretérito perfeito / 1ª pessoa / plural', '"Fomos" = nós fomos — 1ª p. pl. pretérito perfeito do indicativo do verbo ir.'),
('classes', 65, 'B', 'RF', 'Analise morfologicamente: "A pequena menina sorriu alegremente."', '[]', 'A = artigo def. fem. sing. / pequena = adj. fem. sing. / menina = subst. comum fem. sing. / sorriu = verbo sorrir, 3ª p. sing., pret. perf. ind. / alegremente = advérbio de modo', 'Análise morfológica palavra por palavra.'),
('classes', 65, 'B', 'MC', 'Qual palavra da frase "Ele sempre estuda muito bem" é advérbio de TEMPO?', '["bem","muito","sempre","bem e sempre"]', 'sempre', '"Sempre" é advérbio de tempo (indica frequência). "Muito" = intensidade. "Bem" = modo.');

-- Nível 66A — Derivação e composição de palavras
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 66, 'A', 'MC', 'Derivação é o processo de formação de novas palavras por:', '["junção de duas palavras","adição de prefixo ou sufixo à palavra primitiva","reduplicação da sílaba inicial","abreviação de uma palavra"]', 'adição de prefixo ou sufixo à palavra primitiva', 'Derivação acrescenta afixos (prefixos ou sufixos) à palavra primitiva: feliz → infeliz, felizmente.'),
('classes', 66, 'A', 'CL', 'Identifique derivação prefixal (P) ou sufixal (S): infeliz / felizmente / reescrever / lentidão', '[]', 'P / S / P / S', 'in-feliz (prefixo in-); feliz-mente (sufixo -mente); re-escrever (prefixo re-); lenti-dão (sufixo -dão).'),
('classes', 66, 'A', 'VF', '"Guarda-chuva" é formada por composição.', '[]', 'Verdadeiro', 'Guarda-chuva = guarda + chuva — duas palavras unidas por hífen = composição.'),
('classes', 66, 'A', 'RF', 'Forme palavras derivadas acrescentando prefixos: possível → ___ / feliz → ___ / ativo → ___', '[]', 'impossível / infeliz / inativo (ou reativo, hiperativo)', 'Prefixos como im-, in- geralmente indicam negação ou oposição.'),
('classes', 66, 'A', 'MC', '"Peixe-espada" é formada por:', '["derivação","composição","hibridismo","abreviação"]', 'composição', 'Peixe-espada = peixe + espada — duas palavras com significado próprio unidas.'),
('classes', 66, 'A', 'DS', 'Dê exemplos de palavras formadas com os prefixos: re- / des- / super-', '[]', 're-: reler, refazer, reorganizar / des-: desfazer, desejo, desconforto / super-: supermercado, superforte, superpoder', 'Prefixos modificam o sentido da palavra base.'),
('classes', 66, 'A', 'VF', '"Aguardente" é um exemplo de composição por aglutinação.', '[]', 'Verdadeiro', 'Aguardente = água + ardente (aglutinação — as palavras se fundem sem hífen).'),
('classes', 66, 'A', 'CL', 'Classifique o tipo de composição — Justaposição (J) ou Aglutinação (A): girassol / pé-de-moleque / planalto / guarda-roupa', '[]', 'A / J / A / J', 'Girassol (gira+sol) e planalto (plan+alto) = aglutinação. Pé-de-moleque e guarda-roupa = justaposição.'),
('classes', 66, 'A', 'MC', 'O sufixo "-eiro" em "padeiro" indica:', '["ação","lugar","profissão ou agente","qualidade"]', 'profissão ou agente', 'O sufixo -eiro frequentemente forma substantivos de profissão: padeiro, ferreiro, pedreiro.'),
('classes', 66, 'A', 'DS', 'Forme 3 palavras com o sufixo -ção (ação) e 3 com o sufixo -dade (qualidade).', '[]', '-ção: criação, educação, produção / -dade: felicidade, bondade, liberdade', '-ção forma substantivos de ação; -dade forma substantivos de qualidade.'),

-- Nível 66B — Derivação e composição de palavras
('classes', 66, 'B', 'VF', '"Planalto" é formado por aglutinação: plan(o) + alto.', '[]', 'Verdadeiro', 'Planalto = plano + alto com fusão dos elementos — aglutinação.'),
('classes', 66, 'B', 'MC', 'Qual palavra é formada por DERIVAÇÃO REGRESSIVA (o verbo vira substantivo perdendo sílabas)?', '["beleza","corrida (de correr)","frete (de fretar)","releitura"]', 'frete (de fretar)', 'Derivação regressiva: fretar → frete (o verbo origina o substantivo por redução).'),
('classes', 66, 'B', 'CL', 'Identifique o processo de formação: aguardente / pé-de-moleque / re-fazer / padeiro', '[]', 'aglutinação / justaposição / derivação prefixal / derivação sufixal', 'Cada palavra foi formada por um processo diferente.'),
('classes', 66, 'B', 'RF', 'Desmembre as palavras compostas em seus elementos: girassol → ___ + ___ / aguardente → ___ + ___', '[]', 'gira + sol / água + ardente', 'Identificar os elementos formadores das palavras compostas.'),
('classes', 66, 'B', 'DS', 'Explique a diferença entre prefixo e sufixo com 2 exemplos de cada.', '[]', 'Prefixo: vem antes da palavra — infeliz (in-), reescrever (re-). / Sufixo: vem depois da palavra — felizmente (-mente), padeiro (-eiro).', 'Prefixo modifica o sentido; sufixo geralmente muda a classe ou cria nova palavra.'),
('classes', 66, 'B', 'MC', 'O prefixo "bi-" em "bicicleta" significa:', '["um","dois","três","metade"]', 'dois', 'Bi- indica dois: bicicleta (duas rodas), biscoito, bilateral.'),
('classes', 66, 'B', 'VF', 'Uma palavra pode ser formada por PREFIXO e SUFIXO ao mesmo tempo (derivação parassintética).', '[]', 'Verdadeiro', 'Parassintética: en+triste+cer = entristecer (prefixo en- + sufixo -ecer adicionados simultaneamente).'),
('classes', 66, 'B', 'CL', 'Identifique o sufixo e o significado que ele adiciona: livraria (-aria) / tristeza (-eza) / professoral (-al)', '[]', '-aria = lugar / -eza = qualidade / -al = relativo a / adjetivo', 'Sufixos indicam diferentes relações de significado.'),
('classes', 66, 'B', 'RF', 'Forme palavras usando os prefixos indicados: [des-] + fazer → ___ / [re-] + nascer → ___ / [super-] + mercado → ___', '[]', 'desfazer / renascer / supermercado', 'Prefixos se juntam à palavra base sem alterar sua forma gráfica (geralmente).'),
('classes', 66, 'B', 'MC', '"Guarda-chuva" se escreve com hífen porque:', '["é uma palavra derivada","é uma composição por justaposição","é uma palavra aglutinada","é um estrangeirismo"]', 'é uma composição por justaposição', 'Justaposição: as palavras mantêm sua forma original e geralmente se unem por hífen.');

-- Nível 67A — Semântica: sinonímia e antonímia
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 67, 'A', 'MC', 'Sinônimos são palavras que:', '["têm significados opostos","têm significados parecidos ou equivalentes","pertencem à mesma família","têm a mesma escrita mas sons diferentes"]', 'têm significados parecidos ou equivalentes', 'Sinônimos: palavras de sentido semelhante. Ex: bonito/belo, rápido/veloz.'),
('classes', 67, 'A', 'CL', 'Identifique o sinônimo e o antônimo de "feliz": sinônimos → ___ | antônimos → ___', '[]', 'Sinônimos: alegre, contente, satisfeito / Antônimos: triste, infeliz, melancólico', 'Feliz tem muitos sinônimos e antônimos — importante para ampliar o vocabulário.'),
('classes', 67, 'A', 'VF', '"Bonito" e "feio" são antônimos.', '[]', 'Verdadeiro', 'Antônimos têm significados opostos: bonito ↔ feio.'),
('classes', 67, 'A', 'RF', 'Escreva um sinônimo para cada palavra: casa → ___ / rápido → ___ / começo → ___', '[]', 'lar, moradia, residência / veloz, ligeiro, ágil / início, princípio, abertura', 'Sinônimos ampliam o vocabulário e ajudam a evitar repetições.'),
('classes', 67, 'A', 'MC', 'Qual par é de ANTÔNIMOS?', '["bonito/lindo","frio/gelado","alto/baixo","rápido/veloz"]', 'alto/baixo', 'Alto e baixo têm significados opostos — são antônimos.'),
('classes', 67, 'A', 'DS', 'Escreva 2 sinônimos e 2 antônimos para: "coragem", "alegre", "iniciar"', '[]', 'Coragem: sin. bravura, ousadia / ant. covardia, medo. Alegre: sin. feliz, contente / ant. triste, melancólico. Iniciar: sin. começar, principiar / ant. encerrar, terminar.', 'Conhecer sinônimos e antônimos enriquece a expressão e a compreensão.'),
('classes', 67, 'A', 'VF', 'Sinônimos perfeitos (com exatamente o mesmo significado) são muito raros.', '[]', 'Verdadeiro', 'Na maioria das vezes, sinônimos têm pequenas diferenças de uso, contexto ou intensidade.'),
('classes', 67, 'A', 'CL', 'Separe em pares de sinônimos ou antônimos: (bonito/feio) — (belo/lindo) — (alto/baixo) — (veloz/rápido)', '[]', 'Antônimos: bonito/feio, alto/baixo | Sinônimos: belo/lindo, veloz/rápido', 'Identificar a relação semântica entre as palavras.'),
('classes', 67, 'A', 'MC', 'O antônimo de "incluir" é:', '["colocar","excluir","adicionar","inserir"]', 'excluir', 'Incluir ↔ excluir — sentidos opostos.'),
('classes', 67, 'A', 'DS', 'Reescreva o parágrafo substituindo as palavras repetidas por sinônimos: "O livro é lindo. O livro conta uma história linda."', '[]', 'Exemplo: O livro é lindo. A obra conta uma história bela/encantadora.', 'Sinônimos evitam repetições e tornam o texto mais rico.'),

-- Nível 67B — Semântica: sinonímia e antonímia
('classes', 67, 'B', 'VF', '"Abolir" e "extinguir" são sinônimos contextuais.', '[]', 'Verdadeiro', 'Abolir e extinguir podem ser usados como sinônimos em contextos como "abolir/extinguir a escravidão".'),
('classes', 67, 'B', 'MC', 'Qual é o antônimo de "superficial"?', '["leve","raso","profundo","aparente"]', 'profundo', 'Superficial ↔ profundo — opostos em nível de profundidade/análise.'),
('classes', 67, 'B', 'CL', 'Encontre o par de sinônimos em cada grupo: (bonito/feio/lindo) / (correr/pular/trotar) / (triste/feliz/melancólico)', '[]', 'bonito/lindo / correr/trotar / triste/melancólico', 'Dentro de cada grupo, dois têm sentido parecido.'),
('classes', 67, 'B', 'RF', 'Substitua as palavras em negrito por antônimos: "O aluno [tímido] respondeu de forma [errada]."', '[]', 'O aluno extrovertido (ousado, corajoso) respondeu de forma correta.', 'Tímido ↔ extrovertido/ousado; errada ↔ correta.'),
('classes', 67, 'B', 'DS', 'Explique com exemplos a diferença entre antônimos gradativos e complementares.', '[]', 'Gradativos: admitem intermediários — quente/morno/frio (não é só um ou outro). Complementares: não admitem intermediários — vivo/morto, verdadeiro/falso (sem meio-termo).', 'Antônimos gradativos têm uma escala; complementares formam pares absolutos.'),
('classes', 67, 'B', 'MC', 'Sinônimos podem ter:', '["exatamente o mesmo sentido sempre","sentidos parecidos mas com diferentes matizes/usos","significados completamente opostos","a mesma origem sempre"]', 'sentidos parecidos mas com diferentes matizes/usos', 'Sinônimos raramente são intercambiáveis em todos os contextos — há nuances de uso.'),
('classes', 67, 'B', 'VF', '"Lar" e "casa" são sinônimos, mas "lar" tem conotação mais afetiva.', '[]', 'Verdadeiro', 'Sinônimos podem ter conotações diferentes: "lar" evoca afeto/família; "casa" é mais neutro.'),
('classes', 67, 'B', 'CL', 'Classifique o tipo de antonímia: vivo/morto (___) / quente/frio (___) / comprar/vender (___)', '[]', 'complementar / gradativo / converso (recíproco)', 'Vivo/morto = complementar; quente/frio = gradativo; comprar/vender = converso.'),
('classes', 67, 'B', 'RF', 'Reescreva as frases com antônimos: "Ela tem uma personalidade forte e alegre." → "Ela tem uma personalidade ___ e ___."', '[]', 'Ela tem uma personalidade fraca e triste. (antônimos de forte e alegre)', 'Forte ↔ fraca; alegre ↔ triste.'),
('classes', 67, 'B', 'MC', 'Em "O início do filme foi emocionante", o antônimo de "início" é:', '["começo","princípio","fim","abertura"]', 'fim', 'Início ↔ fim — antônimos que marcam os extremos de uma duração.');

-- Nível 68A — Revisão Classes de Palavras III (síntese geral)
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('classes', 68, 'A', 'MC', 'Qual alternativa apresenta corretamente as 10 classes gramaticais?', '["substantivo, adjetivo, verbo, advérbio, pronome, artigo, preposição, conjunção, numeral, interjeição","substantivo, adjetivo, verbo, adverbio, artigo, conjunção, preposição, numeral, sinônimo, antônimo","sujeito, predicado, objeto, advérbio, pronome, artigo, conjunção, numeral, verbo, interjeição","substantivo, adjetivo, verbo, advérbio, pronome, artigo, preposição, oração, numeral, interjeição"]', 'substantivo, adjetivo, verbo, advérbio, pronome, artigo, preposição, conjunção, numeral, interjeição', 'As 10 classes gramaticais da língua portuguesa.'),
('classes', 68, 'A', 'CL', 'Identifique a classe de cada palavra na frase: "Uau! Três alunos inteligentes chegaram hoje."', '[]', 'Uau! = interjeição / Três = numeral / alunos = substantivo / inteligentes = adjetivo / chegaram = verbo / hoje = advérbio', 'Revisão completa das classes gramaticais.'),
('classes', 68, 'A', 'VF', 'Classes variáveis incluem: substantivo, adjetivo, verbo, pronome, artigo, numeral.', '[]', 'Verdadeiro', 'Essas 6 classes flexionam em gênero, número, pessoa, tempo ou modo.'),
('classes', 68, 'A', 'RF', 'Monte uma frase usando obrigatoriamente 6 classes diferentes de palavras.', '[]', 'Exemplo: "Eu (pronome) comprei (verbo) dois (numeral) livros (subst.) interessantes (adj.) para (preposição) você." — 6 classes usadas.', 'Um texto bem escrito usa diferentes classes gramaticais com funções específicas.'),
('classes', 68, 'A', 'MC', 'Qual classe é INVARIÁVEL (não flexiona)?', '["pronome","numeral","preposição","adjetivo"]', 'preposição', 'Preposições, advérbios, conjunções e interjeições são invariáveis.'),
('classes', 68, 'A', 'DS', 'Escreva um parágrafo curto (3-4 frases) e identifique pelo menos uma palavra de cada classe gramatical.', '[]', 'Exemplo: "O(art.) menino(subst.) inteligente(adj.) estudou(verb.) muito(adv.). Ele(pron.) leu(verb.) três(num.) livros(subst.) e(conj.) ficou(verb.) feliz(adj.). Uau!(interj.) Que conquista! Para(prep.) quê? Para aprender."', 'Um texto usa naturalmente todas as classes gramaticais.'),
('classes', 68, 'A', 'CL', 'Classifique corretamente: meu (___) / dois (___) / mas (___) / sob (___) / bravo! (__)', '[]', 'pronome possessivo / numeral cardinal / conjunção adversativa / preposição / interjeição', 'Revisão de 5 classes gramaticais.'),
('classes', 68, 'A', 'VF', 'O artigo é sempre classificado como definido ou indefinido.', '[]', 'Verdadeiro', 'Artigo definido: o, a, os, as. Artigo indefinido: um, uma, uns, umas.'),
('classes', 68, 'A', 'MC', 'Qual classe de palavra conecta ORAÇÕES ou palavras de mesma função?', '["preposição","conjunção","pronome relativo","artigo"]', 'conjunção', 'Conjunções conectam orações (e, mas, porque, portanto) ou palavras de mesma função.'),
('classes', 68, 'A', 'DS', 'Analise morfologicamente a frase completa: "Ela sempre estuda aqui."', '[]', 'Ela = pronome pessoal reto, 3ª p. sing. / sempre = advérbio de tempo / estuda = verbo estudar, 3ª p. sing., presente indic. / aqui = advérbio de lugar', 'Análise morfológica completa de uma frase simples.'),

-- Nível 68B — Revisão Classes de Palavras IV (síntese e aplicação)
('classes', 68, 'B', 'VF', 'Uma palavra pode mudar de classe conforme o contexto ("o bem" vs. "fazer o bem").', '[]', 'Verdadeiro', '"O bem" = substantivo; "bem feito" = advérbio. O contexto define a classe gramatical.'),
('classes', 68, 'B', 'MC', '"O jantar estava delicioso." Nesta frase, "jantar" é:', '["verbo","adjetivo","substantivo","advérbio"]', 'substantivo', '"O jantar" — precedido de artigo, funcionando como sujeito — é substantivo aqui.'),
('classes', 68, 'B', 'CL', 'Identifique a classe de "que" em cada contexto: "O livro que comprei." / "Que livro bonito!" / "Quero que você venha."', '[]', 'pronome relativo / pronome exclamativo (ou interjeição) / conjunção integrante', '"Que" pode exercer diferentes funções dependendo do contexto.'),
('classes', 68, 'B', 'RF', 'Corrija todos os erros de classe (concordância e regência) na frase: "Os aluno bonito foi para o escola rapidamente."', '[]', 'Os alunos bonitos foram para a escola rapidamente.', 'Alunos (pl.) → os + bonitos + foram; escola (fem.) → a escola.'),
('classes', 68, 'B', 'DS', 'Liste 3 palavras que podem ser usadas em classes diferentes conforme o contexto, e dê um exemplo de cada uso.', '[]', 'Exemplos: "mal" (advérbio: "fez mal" / substantivo: "o mal do mundo") / "melhor" (adjetivo: "o melhor aluno" / advérbio: "estuda melhor") / "como" (conjunção: "fez como mandou" / advérbio: "como assim?")','Palavras podem mudar de classe gramatical conforme o contexto.'),
('classes', 68, 'B', 'MC', 'Qual frase contém um erro de CONCORDÂNCIA NOMINAL?', '["Os livros novos estão na mesa.","As flores bonitas perfumam o ambiente.","Ela ficou muito contente.","Os alunos dedicados foi aprovados."]', 'Os alunos dedicados foi aprovados.', '"Foi" deveria ser "foram" — concordância verbal (alunos = plural). Os demais têm concordância nominal correta.'),
('classes', 68, 'B', 'VF', 'Interjeições não fazem concordância com outras palavras da frase.', '[]', 'Verdadeiro', 'Interjeições são invariáveis e independentes — não estabelecem concordância.'),
('classes', 68, 'B', 'CL', 'Analise: "Ela leu [rapidamente] [três] [livros] [interessantes] [e] [ficou] [feliz]." Identifique a classe de cada palavra entre colchetes.', '[]', 'rapidamente = advérbio / três = numeral / livros = substantivo / interessantes = adjetivo / e = conjunção / ficou = verbo / feliz = adjetivo (predicativo)', 'Síntese das classes gramaticais em análise de texto.'),
('classes', 68, 'B', 'RF', 'Reescreva a frase enriquecendo-a com pelo menos 4 classes a mais: "O menino correu."', '[]', 'Exemplo: "O(art.) jovem(adj.) menino(subst.) inteligente(adj.) correu(verb.) rapidamente(adv.) para(prep.) a(art.) escola(subst.), mas(conj.) chegou(verb.) tarde(adv.)."', 'Uma frase simples pode ser expandida com muitas classes gramaticais.'),
('classes', 68, 'B', 'MC', 'Análise sintática e análise morfológica diferem porque:', '["são a mesma coisa","morfológica estuda as palavras isoladas; sintática estuda as relações entre as palavras na oração","morfológica estuda orações; sintática estuda palavras","morfológica é mais avançada que sintática"]', 'morfológica estuda as palavras isoladas; sintática estuda as relações entre as palavras na oração', 'Morfologia = palavra isolada (classe, flexão). Sintaxe = função na oração (sujeito, predicado, etc.).');
