-- ============================================================
-- GeraFicha — Módulo 4: Sintaxe e Análise
-- Níveis 84–96 | Séries A e B
-- ============================================================

-- Nível 84A — Pontuação: vírgula
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 84, 'A', 'MC', 'A vírgula NÃO deve ser usada para:', '["separar o vocativo","separar termos de uma enumeração","separar o sujeito do predicado","isolar o aposto"]', 'separar o sujeito do predicado', 'Regra básica: NUNCA separe o sujeito do predicado com vírgula.'),
('sintaxe', 84, 'A', 'CL', 'Justifique o uso da vírgula: "Brasília, capital do Brasil, fica no Centro-Oeste." / "João, sente-se!"', '[]', 'Brasília → vírgulas isolam o aposto "capital do Brasil" / João → vírgula isola o vocativo', 'Aposto e vocativo são separados por vírgulas.'),
('sintaxe', 84, 'A', 'VF', '"Comprei pão, leite, ovos e manteiga." — A vírgula antes de "e" é opcional na enumeração.', '[]', 'Verdadeiro', 'Na enumeração, a vírgula antes de "e" (vírgula serial) é opcional em português — mas antes de "mas" é obrigatória.'),
('sintaxe', 84, 'A', 'RF', 'Coloque as vírgulas onde necessário: "Alunos prestem atenção pois a prova é amanhã."', '[]', 'Alunos, prestem atenção, pois a prova é amanhã.', '"Alunos" = vocativo (vírgula); "pois" = conjunção explicativa (vírgula antes).'),
('sintaxe', 84, 'A', 'MC', 'Em qual frase o uso da vírgula está INCORRETO?', '["O menino, que estava cansado, dormiu.","Comprou leite, pão e ovos.","A professora, chegou cedo.","Maria, venha aqui!"]', 'A professora, chegou cedo.', 'A vírgula entre sujeito e predicado é erro grave: "A professora chegou cedo." — sem vírgula.'),
('sintaxe', 84, 'A', 'DS', 'Escreva uma frase usando 3 empregos diferentes da vírgula: vocativo, enumeração e aposto.', '[]', 'Exemplo: "Ana (vocativo), minha amiga querida (aposto), comprou leite, pão e ovos (enumeração)."', 'Uma frase pode usar múltiplos empregos da vírgula.'),
('sintaxe', 84, 'A', 'VF', 'Antes de "mas", "porém", "contudo" — conjunções adversativas — usa-se vírgula.', '[]', 'Verdadeiro', '"Estudou muito, mas não passou." — vírgula obrigatória antes de conjunção adversativa.'),
('sintaxe', 84, 'A', 'CL', 'Corrija o uso da vírgula em cada frase: "O aluno estudou, e passou." / "Ela, é minha amiga."', '[]', '"O aluno estudou e passou." (vírgula desnecessária antes de "e" ligando sujeitos iguais) / "Ela é minha amiga." (vírgula errada entre sujeito e predicado)', 'Vírgula antes de "e" é desnecessária quando liga orações de mesmo sujeito.'),
('sintaxe', 84, 'A', 'MC', 'A vírgula é usada para isolar a oração subordinada adverbial quando ela vem ANTES da principal:', '["Nunca","Sempre","Apenas às vezes","Só se for causal"]', 'Sempre', 'Quando a subordinada adverbial precede a principal, usa-se vírgula: "Quando chegou, todos aplaudiram."'),
('sintaxe', 84, 'A', 'DS', 'Explique com exemplos quando usar ponto e vírgula.', '[]', 'Ponto e vírgula separa orações coordenadas longas ou paralelas: "Ela estudou muito; ele, pouco." / Separa itens complexos em listas.', 'Ponto e vírgula indica pausa maior que vírgula e menor que ponto.'),

-- Nível 84B — Pontuação: ponto, dois-pontos e travessão
('sintaxe', 84, 'B', 'MC', 'Os dois-pontos são usados para:', '["indicar pausa entre sujeito e predicado","anunciar uma citação, enumeração ou explicação","substituir o ponto final","indicar pergunta"]', 'anunciar uma citação, enumeração ou explicação', 'Dois-pontos: "Comprei três frutas: maçã, pera e uva." / "Ela disse: Volto logo."'),
('sintaxe', 84, 'B', 'VF', 'O travessão é usado para indicar fala do personagem em diálogos.', '[]', 'Verdadeiro', '— Bom dia! / — Como vai você? — O travessão marca a fala de cada personagem.'),
('sintaxe', 84, 'B', 'CL', 'Justifique o sinal de pontuação: "Ele perguntou: onde está meu livro?" / "— Bom dia! — disse ela."', '[]', '":": anuncia a citação/pergunta direta / "—": marca o diálogo e a fala do personagem', 'Dois-pontos = citação; travessão = diálogo.'),
('sintaxe', 84, 'B', 'RF', 'Pontue corretamente: "Ela pediu [_] Pode me ajudar [_] perguntou com voz suave [_]"', '[]', 'Ela pediu: — Pode me ajudar? — perguntou com voz suave.', 'Dois-pontos anuncia; travessão abre fala; ponto de interrogação termina a pergunta.'),
('sintaxe', 84, 'B', 'DS', 'Escreva um diálogo de 4 falas usando corretamente travessão, dois-pontos e pontuação final.', '[]', 'Exemplo: — Você estudou? — perguntou a professora. — Sim — respondeu o aluno. — Que bom! — disse ela. — A prova é amanhã: prepare-se bem.', 'Diálogos usam travessão para cada fala; dois-pontos anuncia discurso direto.'),
('sintaxe', 84, 'B', 'MC', 'Quando usamos reticências (...) na escrita?', '["Apenas em citações","Para indicar pausa, suspense, pensamento incompleto ou omissão","Para substituir a vírgula","Somente no final da frase"]', 'Para indicar pausa, suspense, pensamento incompleto ou omissão', 'Reticências: "Não sei... talvez amanhã." / Suspense / Pensamento que continua.'),
('sintaxe', 84, 'B', 'VF', 'O ponto de exclamação encerra frases exclamativas, imperativas e interjeitivas.', '[]', 'Verdadeiro', '"Que lindo!" (exclamativa) / "Venha aqui!" (imperativa) / "Ai!" (interjeição) — todos com exclamação.'),
('sintaxe', 84, 'B', 'CL', 'Pontue cada frase e justifique: "Que dia maravilhoso ___" / "Você virá amanhã ___" / "Ela respondeu ___ Sim ___"', '[]', 'Que dia maravilhoso! (exclamação) / Você virá amanhã? (interrogação) / Ela respondeu: — Sim. (dois-pontos + travessão + ponto final)', 'Cada tipo de frase usa um sinal de pontuação específico.'),
('sintaxe', 84, 'B', 'RF', 'Reescreva adicionando a pontuação correta: "Ela listou os materiais lápis borracha régua e caderno"', '[]', 'Ela listou os materiais: lápis, borracha, régua e caderno.', 'Dois-pontos antes da enumeração; vírgulas entre os itens.'),
('sintaxe', 84, 'B', 'MC', 'Qual uso dos parênteses está CORRETO?', '["Separar sujeito e predicado","Incluir informações adicionais ou explicativas","Substituir o ponto final","Indicar diálogo"]', 'Incluir informações adicionais ou explicativas', 'Parênteses: "O IBGE (Instituto Brasileiro de Geografia e Estatística) divulgou os dados."');

-- Nível 85A — Coesão e coerência textual
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 85, 'A', 'MC', 'Coesão textual refere-se a:', '["o conteúdo lógico do texto","os mecanismos linguísticos que ligam as partes do texto","o uso de palavras difíceis","a extensão do texto"]', 'os mecanismos linguísticos que ligam as partes do texto', 'Coesão = conexão entre as partes do texto por pronomes, conjunções, sinônimos, etc.'),
('sintaxe', 85, 'A', 'CL', 'Identifique o recurso de coesão: "Ana estudou. [Ela] foi aprovada." / "Comprou um livro [e] um caderno." / "O resultado foi ótimo. [Por isso], comemorou."', '[]', 'pronome pessoal / conjunção aditiva / conjunção conclusiva', 'Pronomes, conjunções e conectivos garantem coesão ao texto.'),
('sintaxe', 85, 'A', 'VF', 'Coerência é a relação lógica e semântica entre as ideias do texto.', '[]', 'Verdadeiro', 'Um texto é coerente quando suas ideias fazem sentido e não se contradizem.'),
('sintaxe', 85, 'A', 'RF', 'Identifique o problema de coesão e corrija: "Pedro foi ao mercado. Ela comprou pão e leite."', '[]', '"Ela" não tem antecedente claro (Pedro é masculino). Correto: "Pedro foi ao mercado. Ele comprou pão e leite."', 'Pronomes devem concordar com o antecedente para garantir coesão.'),
('sintaxe', 85, 'A', 'MC', '"O aluno estudou. O aluno foi aprovado. O aluno ficou feliz." Qual recurso de coesão tornaria o texto melhor?', '["Usar mais adjetivos","Substituir "o aluno" por pronomes e sinônimos","Acrescentar mais verbos","Dividir em parágrafos"]', 'Substituir "o aluno" por pronomes e sinônimos', 'Evitar repetição com pronomes (ele, o jovem) e sinônimos é recurso de coesão.'),
('sintaxe', 85, 'A', 'DS', 'Reescreva o texto tornando-o mais coeso: "Maria chegou. Maria estava cansada. Maria dormiu cedo. Maria acordou disposta."', '[]', 'Exemplo: "Maria chegou cansada e dormiu cedo. Na manhã seguinte, ela acordou disposta."', 'Pronomes, conjunções e reorganização melhoram a coesão.'),
('sintaxe', 85, 'A', 'VF', 'Um texto pode ter coesão sem ter coerência.', '[]', 'Verdadeiro', 'As partes podem estar bem conectadas (coesão) mas as ideias podem não fazer sentido (falta coerência).'),
('sintaxe', 85, 'A', 'CL', 'Identifique se o problema é de coesão (CO) ou coerência (CE): "Faz sol. Portanto, vou levar guarda-chuva." / "Ana disse que João chegou mas ela não estava lá."', '[]', '"Portanto" = CE (incoerência lógica: sol ≠ razão para guarda-chuva) / pronome ambíguo = CO (ela = Ana ou outra?)', 'Coesão = conexão formal; coerência = lógica das ideias.'),
('sintaxe', 85, 'A', 'MC', 'Quais são os principais mecanismos de coesão referencial?', '["conjunções e preposições","pronomes, sinônimos e hiperônimos","adjetivos e adjetivos","verbos e advérbios"]', 'pronomes, sinônimos e hiperônimos', 'Coesão referencial: retomar um elemento usando pronome, sinônimo ou palavra mais geral.'),
('sintaxe', 85, 'A', 'DS', 'Escreva um parágrafo de 4 frases usando 3 recursos de coesão diferentes.', '[]', 'Exemplo: "A estudante se preparou muito para o exame. Ela revisou todo o conteúdo com atenção. Além disso, fez exercícios diariamente. Por isso, foi aprovada com sucesso."', 'Ela (pronome), além disso (conectivo aditivo), por isso (conectivo conclusivo) = coesão.'),

-- Nível 85B — Coesão e coerência textual
('sintaxe', 85, 'B', 'VF', 'O uso excessivo do pronome "que" pode prejudicar a coesão e a clareza do texto.', '[]', 'Verdadeiro', '"O homem que disse que sabia que..." — acúmulo de "que" torna o texto confuso.'),
('sintaxe', 85, 'B', 'MC', 'Qual recurso de coesão é usado em "Os estudantes trabalharam duro. Os jovens merecem o resultado."?', '["pronome anafórico","sinonímia/paráfrase","elipse","conjunção"]', 'sinonímia/paráfrase', '"Os jovens" retoma "os estudantes" por paráfrase/sinônimo.'),
('sintaxe', 85, 'B', 'CL', 'Identifique o tipo de coesão: "Ela estudou; [por isso], passou." / "Comprou maçãs e laranjas. [A fruta] estava fresca." / "Ana chegou; [ela] estava cansada."', '[]', 'conjunção conclusiva / hiperônimo (fruta = maçãs e laranjas) / pronome anafórico', 'Três tipos de recursos de coesão sequencial e referencial.'),
('sintaxe', 85, 'B', 'RF', 'Reescreva eliminando a incoerência: "Como estava com fome, ele bebeu bastante água."', '[]', 'Como estava com fome, ele comeu bastante. / Como estava com sede, ele bebeu bastante água.', '"Fome" e "beber água" são incoerentes — corrigir a causa ou a consequência.'),
('sintaxe', 85, 'B', 'DS', 'Identifique 3 problemas de coesão no texto: "O aluno chegou. O aluno estava atrasado. O aluno sentou. A professora olhou para o aluno."', '[]', '1. Repetição do sujeito "o aluno" quatro vezes. / 2. Falta de pronomes ou sinônimos. / 3. Ausência de conectivos que indiquem relação entre as ideias.', 'Correto: "O aluno chegou atrasado e sentou. A professora o olhou."'),
('sintaxe', 85, 'B', 'MC', '"Embora estivesse cansada, ela continuou." O conectivo "embora" garante coesão do tipo:', '["referencial","sequencial/temporal","adversativa/concessiva","adicional"]', 'adversativa/concessiva', '"Embora" conecta as orações indicando concessão — coesão sequencial.'),
('sintaxe', 85, 'B', 'VF', 'A progressão temática é uma estratégia de coesão em que cada frase retoma e avança o tema.', '[]', 'Verdadeiro', 'Ex: "Ana chegou. Ela estava cansada. O cansaço a fez dormir cedo." — cada frase retoma e desenvolve.'),
('sintaxe', 85, 'B', 'CL', 'Classifique o recurso de coesão: "Pedro estudou. Com isso, foi aprovado." / "Eles compraram livros. As obras eram importadas." / "Ela canta. Canta muito bem."', '[]', '"com isso" = conector (conclusivo) / "obras" = sinônimo de livros / elipse do sujeito (ela)', 'Conectores, sinônimos e elipse são recursos de coesão.'),
('sintaxe', 85, 'B', 'RF', 'Corrija o texto tornando-o mais coeso: "Gosto de ler. Ler é bom. Ler me faz aprender."', '[]', 'Gosto de ler, pois é uma atividade que me faz aprender muito.', 'Conjunção causal + pronome relativo eliminam a repetição de "ler".'),
('sintaxe', 85, 'B', 'MC', 'A "elipse" como recurso de coesão consiste em:', '["repetir uma palavra","omitir um elemento recuperável pelo contexto","usar sinônimos","acrescentar um aposto"]', 'omitir um elemento recuperável pelo contexto', 'Elipse: "Ela chegou e [ela] sentou." — o sujeito da 2ª oração é omitido por ser recuperável.');

-- Nível 86A — Pontuação avançada e análise de texto
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 86, 'A', 'MC', 'O uso das aspas (" ") em textos indica:', '["pausa breve","citação, ironia, estrangeirismos ou termos em sentido especial","substituto do travessão","parágrafo novo"]', 'citação, ironia, estrangeirismos ou termos em sentido especial', 'Aspas: "O aluno foi \"aprovado\" (ironia)." / "O \'feedback\' foi positivo." (estrangeirismo)'),
('sintaxe', 86, 'A', 'VF', 'O ponto de interrogação pode vir junto com o de exclamação: "Como assim?!"', '[]', 'Verdadeiro', '"Como assim?!" ou "Sério?!" — os dois sinais juntos indicam surpresa e questionamento simultâneos.'),
('sintaxe', 86, 'A', 'RF', 'Pontue o texto: "O professor disse _ Estudem para a prova _ acrescentou _ pois ela é difícil _"', '[]', 'O professor disse: — Estudem para a prova — acrescentou —, pois ela é difícil.', 'Dois-pontos anuncia; travessão marca falas; vírgula antes de pois (explicativo).'),
('sintaxe', 86, 'A', 'CL', 'Identifique e justifique cada sinal de pontuação: "Ana — minha melhor amiga — chegou de surpresa: estava carregando flores, chocolates e um sorriso enorme."', '[]', 'Travessões = isolam aposto / dois-pontos = anuncia enumeração / vírgulas = separam itens da lista', 'Análise dos sinais de pontuação num texto real.'),
('sintaxe', 86, 'A', 'DS', 'Reescreva o parágrafo adicionando a pontuação correta: "Maria chegou cedo ela estava ansiosa pois havia uma reunião importante todos os professores chegaram e a reunião começou"', '[]', 'Maria chegou cedo; ela estava ansiosa, pois havia uma reunião importante. Todos os professores chegaram e a reunião começou.', 'Ponto e vírgula, vírgula antes de pois, ponto final.'),
('sintaxe', 86, 'A', 'VF', 'A vírgula é obrigatória antes de "mas", "porém" e "contudo".', '[]', 'Verdadeiro', 'Conjunções adversativas são sempre precedidas de vírgula: "Estudou, mas não passou."'),
('sintaxe', 86, 'A', 'MC', 'Qual sinal marca uma pausa mais longa que a vírgula mas mais breve que o ponto?', '["reticências","ponto de exclamação","ponto e vírgula","dois-pontos"]', 'ponto e vírgula', 'Hierarquia de pausa: vírgula < ponto e vírgula < dois-pontos < ponto.'),
('sintaxe', 86, 'A', 'CL', 'Corrija todos os erros de pontuação: "Ela disse, que viria. O resultado foi, ótimo. João venha aqui"', '[]', '"Ela disse que viria." (sem vírgula antes de "que" integrante) / "O resultado foi ótimo." (sem vírgula entre pred.nominal) / "João, venha aqui!" (vocativo + exclamação)', 'Três erros de pontuação diferentes para corrigir.'),
('sintaxe', 86, 'A', 'RF', 'Escreva um parágrafo usando: ponto final, vírgula, dois-pontos, travessão e ponto de interrogação.', '[]', 'Exemplo: "O diretor anunciou: — Há uma novidade importante. Todos ficaram curiosos: seria uma viagem? — Não — disse ele —, é uma festa!"', 'Um bom texto usa variados sinais de pontuação com função específica.'),
('sintaxe', 86, 'A', 'DS', 'Explique quando usar vírgula antes de "e": situações em que é obrigatória, opcional e proibida.', '[]', 'Obrigatória: quando liga orações de sujeitos diferentes ("Pedro chegou, e Ana saiu.") / Opcional: enumeração longa / Proibida: entre sujeito composto e verbo ("Pedro e Ana chegaram") — não entre os sujeitos nem antes do verbo', 'O uso de vírgula antes de "e" depende da estrutura sintática.'),

-- Nível 86B — Revisão de pontuação
('sintaxe', 86, 'B', 'VF', '"[...] " (colchetes com reticências) indica supressão de trecho em citação.', '[]', 'Verdadeiro', '[...] é usado em citações acadêmicas para indicar que parte do texto foi omitida.'),
('sintaxe', 86, 'B', 'MC', 'Qual sinal deve ser usado na frase "Ela respondeu _ Sim _ com firmeza"?', '["vírgula","travessão","reticências","parênteses"]', 'travessão', 'Ela respondeu — Sim —, com firmeza. Travessão marca a fala no diálogo.'),
('sintaxe', 86, 'B', 'CL', 'Analise a pontuação: "As cidades mais visitadas são: Paris, Londres, Roma e Tóquio."', '[]', '":" anuncia a enumeração; vírgulas separam os itens; "e" antes do último elemento (não precisa de vírgula antes).', 'Dois-pontos + enumeração com vírgulas é padrão correto.'),
('sintaxe', 86, 'B', 'RF', 'Pontue adequadamente: "O aluno que chegou tarde isso não deveria acontecer perdeu a chamada"', '[]', 'O aluno que chegou tarde — isso não deveria acontecer — perdeu a chamada.', 'Travessões isolam o comentário intercalado.'),
('sintaxe', 86, 'B', 'DS', 'Escreva 3 frases demonstrando usos diferentes das aspas.', '[]', 'Citação: O poeta escreveu: "Amor é fogo que arde sem se ver." / Ironia: Ele foi muito "educado" (ironia). / Estrangeirismo: O "deadline" é amanhã.', 'Aspas para citação, ironia e estrangeirismo.'),
('sintaxe', 86, 'B', 'MC', 'O colchete [ ] é usado para:', '["indicar diálogo","inserir explicações dentro de citações ou corrigir erros","substituir vírgula","indicar reticências"]', 'inserir explicações dentro de citações ou corrigir erros', 'Colchetes: "Ele [o presidente] assinou o decreto." — esclarece o referente na citação.'),
('sintaxe', 86, 'B', 'VF', 'A hífen (-) e o travessão (—) têm usos diferentes.', '[]', 'Verdadeiro', 'Hífen (-): separação de sílabas, compostos (guarda-chuva). Travessão (—): diálogos, interrupções, apostos.'),
('sintaxe', 86, 'B', 'CL', 'Identifique o sinal de pontuação e sua função: "Não sei... talvez amanhã." / "João [o capitão] marcou o gol." / "Ei! Presta atenção!"', '[]', '"..." = reticências (pausa/suspense) / "[o capitão]" = colchetes (explicação) / "Ei!" = interjeição com exclamação', 'Cada sinal tem uma função específica no texto.'),
('sintaxe', 86, 'B', 'RF', 'Corrija a pontuação: "Ela comprou leite pão ovos e manteiga, mas esqueceu o sal?"', '[]', 'Ela comprou leite, pão, ovos e manteiga, mas esqueceu o sal.', 'Vírgulas na enumeração; vírgula antes de "mas"; ponto final (não interrogação).'),
('sintaxe', 86, 'B', 'MC', 'Qual frase tem a pontuação CORRETA?', '["Ela disse, que voltaria cedo.","João Pedro e Ana chegaram juntos.","Estudou muito; portanto, passou.","Comprei leite pão e ovos."]', 'Estudou muito; portanto, passou.', 'Ponto e vírgula antes de "portanto" + vírgula depois = pontuação correta para conclusiva.');

-- Nível 87A — Revisão Sintaxe III (acumulativa)
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 87, 'A', 'MC', 'Qual é a análise sintática correta de "O cachorro late muito"?', '["Suj: O cachorro / Pred verbal: late muito / Adj.adv.: muito","Suj: cachorro / Pred nominal: late muito / Pred.: muito","Suj: muito / Pred verbal: O cachorro late","Suj: O / Pred: cachorro late muito"]', 'Suj: O cachorro / Pred verbal: late muito / Adj.adv.: muito', '"Muito" é adjunto adverbial de intensidade do verbo late.'),
('sintaxe', 87, 'A', 'CL', 'Analise o período composto: "Ela saiu cedo porque tinha uma reunião importante."', '[]', 'O. Principal: Ela saiu cedo / O. Sub. Adv. Causal: porque tinha uma reunião importante', '"Porque" introduz oração subordinada adverbial causal.'),
('sintaxe', 87, 'A', 'VF', '"Que você venha é essencial." — "Que você venha" é sujeito da oração.', '[]', 'Verdadeiro', '"Que você venha" = sujeito de "é essencial" — subordinada substantiva subjetiva.'),
('sintaxe', 87, 'A', 'RF', 'Identifique o tipo de predicado e o predicativo: "Ela chegou cansada." / "O resultado foi perfeito." / "Ela cantou animada."', '[]', '"chegou cansada" = verbo-nominal (cansada = pred. sujeito) / "foi perfeito" = nominal (perfeito = pred. sujeito) / "cantou animada" = verbo-nominal (animada = pred. sujeito)', 'Três tipos de predicado com predicativo do sujeito.'),
('sintaxe', 87, 'A', 'MC', 'Qual oração é COORDENADA CONCLUSIVA?', '["Embora estudasse, não passou.","Estudou, logo passou.","Estudou porque queria.","Quando estudou, passou."]', 'Estudou, logo passou.', '"Logo" é conjunção conclusiva — indica conclusão a partir de premissa anterior.'),
('sintaxe', 87, 'A', 'DS', 'Escreva a análise sintática completa de: "Os alunos dedicados entregaram o trabalho ao professor ontem."', '[]', 'Suj: Os alunos dedicados (adj.adnom.: dedicados) / Pred.verbal: entregaram o trabalho ao professor ontem / OD: o trabalho / OI: ao professor / Adj.adv.tempo: ontem', 'Análise de período simples com OD, OI e adjunto adverbial.'),
('sintaxe', 87, 'A', 'VF', 'Um texto bem escrito equilibra períodos simples e compostos.', '[]', 'Verdadeiro', 'Variar a estrutura dos períodos torna o texto mais fluente e interessante.'),
('sintaxe', 87, 'A', 'CL', 'Classifique cada oração sublinhada: "Sei [que virás]. / Fui ao cinema [que fica perto]. / [Quando chegar], avise."', '[]', 'sub. substantiva OD / sub. adjetiva restritiva / sub. adverbial temporal', 'As três orações subordinadas mais comuns: substantiva, adjetiva e adverbial.'),
('sintaxe', 87, 'A', 'MC', 'Qual é a função sintática de "de história" em "Ela leu um livro de história"?', '["OD","OI","adjunto adnominal","predicativo"]', 'adjunto adnominal', '"De história" caracteriza o livro — adjunto adnominal (locução adjetiva).'),
('sintaxe', 87, 'A', 'DS', 'Analise sintaticamente e determine o tipo de período: "Embora estivesse cansada, ela terminou o relatório e o enviou ao chefe."', '[]', 'Período composto: O1 = sub.adv.concessiva / O2 = oração principal / O3 = coord.aditiva / Suj.: ela / OD de O2: o relatório / OD de O3: o (lo) / OI de O3: ao chefe', 'Período complexo com subordinação e coordenação.'),

-- Nível 87B — Revisão Sintaxe IV (síntese)
('sintaxe', 87, 'B', 'VF', 'A análise de texto envolve identificar estrutura sintática, recursos de coesão e coerência.', '[]', 'Verdadeiro', 'Análise textual completa: morfologia + sintaxe + semântica + coesão + coerência.'),
('sintaxe', 87, 'B', 'MC', 'Na frase "Ela me deu o livro", "me" é:', '["sujeito","OD","OI","adjunto adnominal"]', 'OI', '"Deu o livro a mim" → "me" = OI (objeto indireto, pronome oblíquo átono).'),
('sintaxe', 87, 'B', 'CL', 'Identifique coesão e coerência: "Ela chegou cedo. Isso era incomum nela. Normalmente, atrasava-se sempre."', '[]', 'Coesão: "Isso" (pronome demonstrativo retomando "chegou cedo") + "normalmente, sempre" (advérbios de frequência) / Coerência: lógica coerente (chegar cedo → incomum → normalmente atrasada)', 'O texto tem boa coesão e coerência — análise positiva.'),
('sintaxe', 87, 'B', 'RF', 'Analise todos os termos: "A bela professora de literatura ensinou poesia aos alunos com entusiasmo."', '[]', 'Suj: A bela professora de literatura (adj.adnom.: bela, de literatura) / Pred.verbal: ensinou poesia aos alunos com entusiasmo / OD: poesia / OI: aos alunos / Adj.adv.modo: com entusiasmo', 'Análise completa de período simples rico.'),
('sintaxe', 87, 'B', 'DS', 'Produza um parágrafo de 5 frases sobre um tema à escolha, usando: 2 períodos simples, 1 composto coordenado, 1 composto subordinado e 1 com oração adjetiva.', '[]', 'Exemplo sobre leitura: "A leitura é fundamental. (simples) Ela nos transforma. (simples) Quem lê cresce intelectualmente, mas também emocionalmente. (coord.) A leitura muda o mundo porque amplia horizontes. (subord.) O livro que li semana passada me inspirou muito. (adj.)', 'Síntese de toda a análise sintática em produção textual.'),
('sintaxe', 87, 'B', 'MC', 'Qual elemento NÃO faz parte da análise sintática de uma oração?', '["sujeito","predicado","objeto direto","raiz da palavra"]', 'raiz da palavra', 'Raiz é elemento da morfologia (análise de palavras), não da sintaxe (análise da oração).'),
('sintaxe', 87, 'B', 'VF', 'O estudo da pontuação faz parte da sintaxe porque depende das relações entre os termos da oração.', '[]', 'Verdadeiro', 'A pontuação segue as estruturas sintáticas: vírgula após vocativo, dois-pontos antes de enumeração, etc.'),
('sintaxe', 87, 'B', 'CL', 'Faça a análise morfossintática da frase: "Ela sempre estuda com dedicação." — morfologia + função sintática de cada palavra', '[]', 'Ela = pron.pessoal reto (sujeito) / sempre = advérbio de tempo (adj.adv.tempo) / estuda = verbo (núcleo pred.verbal) / com dedicação = locução adv.modo (adj.adv.modo) / dedicação = subst.fem.sing. (núcleo da loc.adv.)', 'Análise morfossintática combina morfologia e sintaxe.'),
('sintaxe', 87, 'B', 'RF', 'Corrija os erros sintáticos e de pontuação: "Os alunos, chegaram cedo e eles sentaram rápido"', '[]', 'Os alunos chegaram cedo e sentaram rapidamente.', 'Remover vírgula errada entre sujeito e pred.; elipse do sujeito repetido; rápido → rapidamente (advérbio).'),
('sintaxe', 87, 'B', 'MC', 'O núcleo do predicado é sempre:', '["o sujeito","o verbo","o adjetivo","o objeto direto"]', 'o verbo', 'O verbo é o núcleo do predicado — é o elemento central em torno do qual os demais termos se organizam.');
