-- ============================================================
-- GeraFicha — Módulo 5: Interpretação e Produção de Texto
-- Níveis 108–120 | Séries A e B
-- ============================================================

-- Nível 108A — Leitura de textos multimodais
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 108, 'A', 'MC', 'Textos multimodais são aqueles que:', '["usam apenas palavras escritas","combinam diferentes linguagens: escrita, imagem, gráfico, áudio, vídeo","são escritos em várias línguas","têm muitos parágrafos"]', 'combinam diferentes linguagens: escrita, imagem, gráfico, áudio, vídeo', 'Multimodal: jornais, sites, cartazes, infográficos combinam texto, imagem e outros modos.'),
('interpretacao', 108, 'A', 'CL', 'Classifique em Monomodal (M) ou Multimodal (MM): Poema impresso / Infográfico / Conto em livro / Notícia com foto e gráfico / Vídeo informativo', '[]', 'M / MM / M / MM / MM', 'Multimodal = duas ou mais linguagens. Monomodal = apenas verbal.'),
('interpretacao', 108, 'A', 'VF', 'Em textos multimodais, a imagem e o texto se complementam para construir o sentido.', '[]', 'Verdadeiro', 'Imagem não é decoração — contribui ativamente para o significado do texto multimodal.'),
('interpretacao', 108, 'A', 'RF', 'Descreva o que deveria estar num infográfico sobre "o ciclo da água". Quais elementos visuais e textuais incluiria?', '[]', 'Elementos: título claro / diagrama com setas mostrando evaporação→condensação→precipitação→escoamento / legendas curtas explicando cada etapa / ícones (sol, nuvem, chuva, rio) / porcentagens ou dados', 'Infográfico eficaz combina visual + texto sintético.'),
('interpretacao', 108, 'A', 'MC', 'Qual habilidade é necessária para ler um infográfico?', '["Apenas decodificar as palavras escritas","Relacionar as informações visuais e verbais simultaneamente","Ignorar as imagens e focar só no texto","Traduzir o texto para outra língua"]', 'Relacionar as informações visuais e verbais simultaneamente', 'Leitura de infográfico: interpretar gráficos, imagens e texto de forma integrada.'),
('interpretacao', 108, 'A', 'DS', 'Analise um cartaz de campanha de saúde: que elementos verbais e não verbais estão presentes e qual é o papel de cada um?', '[]', 'Verbais: título impactante, slogan, texto informativo curto, logo. / Não verbais: imagem forte e chamativa, cores associadas à saúde (verde, azul), seta ou destaque visual. / Papel: imagem atrai atenção; texto informa e orienta.', 'Análise de texto multimodal: cada elemento tem função comunicativa específica.'),
('interpretacao', 108, 'A', 'VF', 'Charges e histórias em quadrinhos são exemplos de textos multimodais.', '[]', 'Verdadeiro', 'Charge: texto verbal (balão) + imagem + ironia visual. HQ: sequência de imagens + texto = multimodal.'),
('interpretacao', 108, 'A', 'CL', 'Identifique a função de cada elemento numa charge: imagem / balão / expressão facial do personagem', '[]', 'Imagem: contextualiza a cena visualmente / Balão: apresenta a fala ou pensamento / Expressão facial: reforça a emoção ou a ironia da cena', 'Análise dos elementos da charge como texto multimodal.'),
('interpretacao', 108, 'A', 'MC', 'O que é linguagem não verbal?', '["Apenas imagens fotográficas","Qualquer sistema de comunicação que não usa palavras escritas ou faladas: gestos, imagens, cores, sons","Linguagem de programação","Escrita em código"]', 'Qualquer sistema de comunicação que não usa palavras escritas ou faladas: gestos, imagens, cores, sons', 'Linguagem não verbal: imagem, gesto, cor, música — comunicam sem palavras.'),
('interpretacao', 108, 'A', 'DS', 'Explique como as cores num anúncio publicitário comunicam sentidos específicos (dê 3 exemplos).', '[]', 'Verde: saúde, natureza, frescor (marcas de alimentos saudáveis) / Vermelho: urgência, paixão, promoção (alertas, liquidações) / Azul: confiança, segurança, tecnologia (bancos, plataformas digitais)', 'Cores são elementos de comunicação não verbal com significados culturais.'),

-- Nível 108B — Leitura crítica de mídias
('interpretacao', 108, 'B', 'VF', 'A desinformação (fake news) é um problema de literacia midiática.', '[]', 'Verdadeiro', 'Fake news exige leitores críticos capazes de verificar fontes, datas e contextos.'),
('interpretacao', 108, 'B', 'MC', 'Qual estratégia ajuda a verificar se uma notícia é confiável?', '["Ler apenas o título","Compartilhar rapidamente com amigos","Verificar a fonte, a data e buscar confirmação em outros veículos","Acreditar em tudo que está no celular"]', 'Verificar a fonte, a data e buscar confirmação em outros veículos', 'Verificação: checar fonte + data + outras fontes = prática básica de literacia midiática.'),
('interpretacao', 108, 'B', 'CL', 'Analise e aponte 3 sinais de alerta que indicam possível fake news: "CHOQUEI!!! Cientistas provaram que vacinas causam doenças! Compartilhe antes que seja deletado!"', '[]', '1. Linguagem sensacionalista ("CHOQUEI!!!", exclamações) / 2. Urgência artificial ("antes que seja deletado") / 3. Afirmação genérica sem citar fonte específica', 'Características típicas de desinformação online.'),
('interpretacao', 108, 'B', 'RF', 'Escreva 3 perguntas que um leitor crítico deve fazer ao encontrar uma notícia nas redes sociais.', '[]', '1. Quem publicou? A fonte é confiável e verificável? / 2. Quando foi publicado? A informação está atualizada? / 3. Outros veículos sérios confirmam a informação? Há evidências?', 'Perguntas críticas fundamentais para avaliação de informação.'),
('interpretacao', 108, 'B', 'DS', 'Explique o que é "bolha algorítmica" e como ela afeta nossa visão de mundo.', '[]', 'Bolha algorítmica: os algoritmos das redes sociais nos mostram apenas conteúdos que combinam com nossas preferências anteriores. Isso nos isola de outras perspectivas e reforça nossas crenças existentes, dificultando o pensamento crítico e a empatia.', 'Conhecer os mecanismos das plataformas digitais é essencial para a literacia midiática.'),
('interpretacao', 108, 'B', 'MC', 'Propaganda e publicidade diferem porque:', '["não há diferença real","propaganda defende ideias/causas; publicidade vende produtos ou serviços","propaganda é legal; publicidade é ilegal","propaganda usa imagens; publicidade usa texto"]', 'propaganda defende ideias/causas; publicidade vende produtos ou serviços', 'Propaganda: ideológica (política, religiosa). Publicidade: comercial (vende produto).'),
('interpretacao', 108, 'B', 'VF', 'Análise de discurso estuda não só o que é dito, mas como e por que é dito.', '[]', 'Verdadeiro', 'Análise do discurso: considera contexto, poder, ideologia e escolhas linguísticas do autor.'),
('interpretacao', 108, 'B', 'CL', 'Identifique o recurso persuasivo: "9 em cada 10 dentistas recomendam..." / "Seja como os campeões — use X!" / "Oferta por tempo limitado!"', '[]', 'autoridade (dado estatístico) / identificação com modelo (celebridade/campeão) / urgência (pressão temporal)', 'Recursos persuasivos comuns na publicidade.'),
('interpretacao', 108, 'B', 'RF', 'Crie um anúncio publicitário de 3 frases para um produto fictício, usando 2 recursos persuasivos diferentes.', '[]', 'Exemplo: "O sabonete NaturFresh é o preferido de 9 em cada 10 dermatologistas. [autoridade] Com ingredientes 100% naturais, cuida da sua pele como ela merece. [apelo à natureza/saúde] Experimente por 7 dias ou seu dinheiro de volta — porque sua pele não pode esperar! [urgência + garantia]"', 'Publicidade usa múltiplos recursos persuasivos combinados.'),
('interpretacao', 108, 'B', 'MC', 'Qual é a principal diferença entre opinar e informar num texto?', '["Não há diferença","Opinar expressa o ponto de vista do autor; informar transmite fatos verificáveis","Informar usa adjetivos; opinar usa dados","Opinar é formal; informar é informal"]', 'Opinar expressa o ponto de vista do autor; informar transmite fatos verificáveis', 'Distinção fundamental: fato (verificável) vs. opinião (ponto de vista pessoal).');

-- Nível 109A — Produção avançada: dissertação completa
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 109, 'A', 'MC', 'Qual é a diferença entre dissertação expositiva e dissertação argumentativa?', '["Expositiva é mais longa; argumentativa é mais curta","Expositiva apenas explica e informa; argumentativa defende uma tese","São a mesma coisa","Expositiva usa imagens; argumentativa usa só texto"]', 'Expositiva apenas explica e informa; argumentativa defende uma tese', 'Expositiva: explica um tema de forma neutra. Argumentativa: defende posição com argumentos.'),
('interpretacao', 109, 'A', 'CL', 'Identifique que tipo de dissertação é cada uma: "O ciclo da água ocorre em quatro etapas: evaporação, condensação, precipitação e infiltração." / "É urgente reduzir o consumo de plástico descartável para preservar os oceanos."', '[]', '"O ciclo da água..." = expositiva (neutra, explica processo) / "É urgente reduzir..." = argumentativa (defende posição com adjetivo de urgência)', 'Tom neutro = expositiva. Tom de defesa = argumentativa.'),
('interpretacao', 109, 'A', 'VF', 'Uma boa dissertação argumentativa considera e rebate o ponto de vista contrário.', '[]', 'Verdadeiro', 'Concessão + refutação torna o texto mais maduro: "Embora X, na verdade Y porque Z."'),
('interpretacao', 109, 'A', 'RF', 'Escreva a introdução de uma dissertação argumentativa sobre "o uso de celular por crianças" (3 frases).', '[]', 'Exemplo: "O uso de smartphones por crianças tornou-se um tema de debate crescente entre especialistas, pais e educadores. Por um lado, a tecnologia oferece recursos educacionais valiosos; por outro, o uso excessivo e descontrolado pode prejudicar o desenvolvimento cognitivo e social. Diante desse cenário, é fundamental discutir limites e critérios de uso adequados à faixa etária."', 'Introdução: contextualizar + apresentar a tensão + anunciar a discussão.'),
('interpretacao', 109, 'A', 'MC', 'Qual técnica argumentativa é usada em "Embora alguns defendam X, os estudos mostram Y"?', '["exemplificação","concessão e refutação","apelo emocional","argumento de autoridade"]', 'concessão e refutação', 'Concessão: reconhecer o outro lado. Refutação: apresentar argumento contrário com evidência.'),
('interpretacao', 109, 'A', 'DS', 'Escreva uma dissertação argumentativa completa de 4 parágrafos sobre: "A importância da educação financeira nas escolas."', '[]', 'P1 (intro): contextualização + tese. P2: arg.1 (ex: evitar endividamento + dado). P3: arg.2 (construir hábitos desde cedo + concessão/refutação). P4 (concl.): síntese + proposta de ação (incluir na grade curricular).', 'Dissertação completa com 4 blocos bem estruturados.'),
('interpretacao', 109, 'A', 'VF', 'O uso de conectivos variados enriquece a argumentação e evita a repetição.', '[]', 'Verdadeiro', 'Variar conectivos: "além disso", "por outro lado", "contudo", "portanto" → fluidez textual.'),
('interpretacao', 109, 'A', 'CL', 'Identifique o tipo de argumento: "Segundo relatório da ONU 2023, 2,4 bilhões de pessoas não têm acesso a alimentos nutritivos." / "Imagine não poder dar ao seu filho o que comer."', '[]', 'dado estatístico com fonte (argumento de autoridade) / apelo emocional (argumento patético)', 'Dados e emoção são tipos distintos de argumento, cada um com seus efeitos.'),
('interpretacao', 109, 'A', 'MC', 'A proposta de intervenção numa redação de vestibular deve:', '["repetir a tese da introdução","apresentar ação específica, com agente, ação e finalidade","descrever o problema sem solução","usar linguagem coloquial"]', 'apresentar ação específica, com agente, ação e finalidade', 'Proposta de intervenção modelo: "Cabe ao [agente] [ação] a fim de [finalidade]."'),
('interpretacao', 109, 'A', 'DS', 'Escreva a conclusão e proposta de intervenção para o tema: "Desigualdade educacional no Brasil."', '[]', 'Exemplo: "Em síntese, a desigualdade educacional perpetua ciclos de exclusão que impedem o pleno desenvolvimento do país. Cabe ao governo federal ampliar o financiamento das escolas públicas, garantindo infraestrutura e formação de professores. Às famílias e à sociedade civil cabe cobrar e participar ativamente das políticas educacionais, a fim de construir um Brasil mais justo e com oportunidades reais para todos."', 'Conclusão com proposta de intervenção: agentes + ações + finalidade.'),

-- Nível 109B — Revisão integrada
('interpretacao', 109, 'B', 'VF', 'Escrever bem requer planejamento, execução e revisão sistemática.', '[]', 'Verdadeiro', 'A escrita de qualidade passa por: planejar (o quê/como) → escrever (1ª versão) → revisar (melhorar).'),
('interpretacao', 109, 'B', 'MC', 'Qual é a função da revisão textual?', '["apenas corrigir erros de ortografia","verificar e aprimorar clareza, coesão, coerência, argumentação e adequação ao gênero","reescrever completamente o texto","publicar o texto final"]', 'verificar e aprimorar clareza, coesão, coerência, argumentação e adequação ao gênero', 'Revisão vai além da ortografia: melhora estrutura, argumentação e linguagem.'),
('interpretacao', 109, 'B', 'CL', 'Revise o trecho e aponte melhorias: "A educação é muito importante. Muito importante porque faz as coisas melhores. As coisas melhores fazem a vida boa."', '[]', 'Problemas: repetição de "muito importante", "as coisas" vago, progressão incoerente. Melhoria: "A educação é fundamental para o desenvolvimento humano, pois amplia perspectivas, forma cidadãos críticos e contribui para uma vida mais plena."', 'Revisão elimina repetições, vagas e melhora a progressão temática.'),
('interpretacao', 109, 'B', 'RF', 'Escreva 5 critérios que você usaria para avaliar um texto de um colega.', '[]', '1. Adequação ao gênero e ao propósito / 2. Clareza e objetividade / 3. Coesão (conectivos, pronomes, sinônimos) / 4. Coerência das ideias / 5. Qualidade dos argumentos (para texto argumentativo)', 'Critérios de avaliação textual para leitura crítica de produção alheia.'),
('interpretacao', 109, 'B', 'DS', 'Produza e avalie seu próprio texto: escreva 3 parágrafos sobre "o futuro da tecnologia na educação" e depois liste 3 qualidades e 1 ponto a melhorar.', '[]', 'Resposta livre — o estudante produz o texto e faz sua própria avaliação metacognitiva.', 'Metacognição: refletir sobre o próprio processo de escrita é habilidade avançada.'),
('interpretacao', 109, 'B', 'MC', 'Qual estratégia de revisão é mais eficaz?', '["Revisar imediatamente após escrever","Deixar o texto "descansar" e reler depois com olhar fresco","Pedir para alguém corrigir sem ler você mesmo","Usar apenas corretor automático"]', 'Deixar o texto "descansar" e reler depois com olhar fresco', 'Distância temporal ajuda a ver o próprio texto com mais objetividade.'),
('interpretacao', 109, 'B', 'VF', 'A leitura em voz alta é uma estratégia eficaz de revisão textual.', '[]', 'Verdadeiro', 'Ler em voz alta revela trechos confusos, repetições e falta de fluidez que a leitura silenciosa pode esconder.'),
('interpretacao', 109, 'B', 'CL', 'Identifique se cada frase está clara ou precisa de revisão: "Ela foi lá fazer aquilo." / "A estudante percorreu 5 km até a biblioteca para devolver o livro que havia emprestado."', '[]', '"Ela foi lá fazer aquilo" = precisa de revisão (pronomes vagos: ela? lá? aquilo?) / Segunda frase: clara e precisa.', '"Lá", "aquilo", "ela" sem referente claro = falta de coesão e precisão.'),
('interpretacao', 109, 'B', 'RF', 'Revise e reescreva: "O meio ambiente ele é importante. Porque sem ele a gente não vive. Então deve ser preservado o meio ambiente por nós."', '[]', '"O meio ambiente é essencial para a sobrevivência humana. Sem ele, a vida como a conhecemos seria impossível. Por isso, cabe a todos nós a responsabilidade de preservá-lo."', 'Revisão: eliminar pronome redundante + coesão + ordem das ideias + registro.'),
('interpretacao', 109, 'B', 'MC', 'O que é plagiar um texto?', '["resumir com as próprias palavras","citar a fonte corretamente","copiar e apresentar como próprio sem dar crédito ao autor","traduzir um texto estrangeiro"]', 'copiar e apresentar como próprio sem dar crédito ao autor', 'Plágio: cópia sem crédito ao autor = desonestidade intelectual e infração ética/legal.');

-- Nível 110A — Revisão Interpretação V (acumulativa)
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 110, 'A', 'MC', 'Qual tipo de texto usa predominantemente verbos no passado para narrar eventos?', '["informativo","argumentativo","narrativo","injuntivo"]', 'narrativo', 'Textos narrativos geralmente usam verbos no passado para relatar eventos.'),
('interpretacao', 110, 'A', 'CL', 'Analise: "Branca de Neve foi envenenada pela rainha. O príncipe a salvou com um beijo." — Identifique: tipo de texto, narrador, elementos narrativos.', '[]', 'Tipo: narrativo / Narrador: 3ª pessoa (observador externo) / Personagens: Branca de Neve, rainha, príncipe / Enredo: envenenamento + salvação', 'Análise rápida dos elementos narrativos.'),
('interpretacao', 110, 'A', 'VF', 'Figuras de linguagem estão presentes em textos literários e também em textos cotidianos (conversas, propagandas).', '[]', 'Verdadeiro', '"Morri de rir!" (hipérbole cotidiana) / "Um Mar de Oportunidades" (metáfora em anúncio)'),
('interpretacao', 110, 'A', 'RF', 'Complete com a figura de linguagem indicada: "Ela é ___ (comparação com pássaro)" / "A notícia ___ o mundo" (metáfora com abanou)', '[]', 'Ela é livre como um pássaro. / A notícia sacudiu o mundo. (ou: A notícia foi um terremoto.)','Completar frases usando as figuras indicadas.'),
('interpretacao', 110, 'A', 'MC', 'Qual é a estrutura do parágrafo argumentativo ideal?', '["Tópico frasal + desenvolvimento + frase de transição","Tese + título + conclusão","Apenas argumentos, sem tópico frasal","Exemplos sem afirmação central"]', 'Tópico frasal + desenvolvimento + frase de transição', 'TF (ideia central) + desenvolvimento (argumentos/exemplos) + frase de transição ou conclusão.'),
('interpretacao', 110, 'A', 'DS', 'Escreva sobre o mesmo tema usando 2 tipos de texto diferentes: narrativo e argumentativo. Tema: "A importância da amizade."', '[]', 'Narrativo: "Era uma tarde de inverno quando Carla recebeu a ligação do amigo. Ele havia perdido o emprego. Ela largou tudo e foi consolá-lo. Às vezes, a amizade se prova nos momentos mais difíceis." / Argumentativo: "A amizade é um dos pilares do bem-estar humano. Estudos mostram que pessoas com vínculos afetivos fortes têm melhor saúde física e mental. Cultivar amizades genuínas é, portanto, um investimento na qualidade de vida."', 'O mesmo tema, tratado de formas completamente diferentes.'),
('interpretacao', 110, 'A', 'VF', 'A adequação do texto ao público-alvo é fundamental para que a comunicação seja eficaz.', '[]', 'Verdadeiro', 'Texto para criança: linguagem simples, exemplos concretos. Texto para especialistas: técnico, denso.'),
('interpretacao', 110, 'A', 'CL', 'Identifique coesão, coerência e adequação: "A chuva caiu. Logo em seguida, o sol saiu e todos foram brincar. O clima colaborou para a alegria."', '[]', 'Coesão: "logo em seguida" (conectivo temporal), "o clima" (sinônimo anafórico). Coerência: sequência lógica (chuva→sol→brincadeira). Adequação: linguagem simples, adequada a narrativa informal.', 'Análise tripla: coesão + coerência + adequação.'),
('interpretacao', 110, 'A', 'MC', 'O que é intertextualidade explícita?', '["Quando o texto menciona outro texto sem citar a fonte","Quando o texto cita diretamente outro texto, identificando autor e/ou obra","Quando há personagens de outros textos sem menção","Quando se usa metáforas originais"]', 'Quando o texto cita diretamente outro texto, identificando autor e/ou obra', 'Explícita: "Como disse Machado de Assis, ..." / Implícita: alusão sem citar.'),
('interpretacao', 110, 'A', 'DS', 'Escreva um texto curto que contenha: 1 figura de linguagem, 1 conector de coesão e 1 exemplo de intertextualidade.', '[]', 'Exemplo: "Como dizia Drummond, a pedra do caminho sempre aparece — e a vida é uma sequência de pedras a superar. Mas é justamente por isso que seguimos em frente, um passo de cada vez." / Figuras: metáfora (pedra = obstáculo) / Conector: "mas" / Intertextualidade: referência a Drummond ("No meio do caminho").', 'Texto integrado com os três recursos pedidos.'),

-- Nível 110B — Revisão Interpretação VI (síntese final)
('interpretacao', 110, 'B', 'VF', 'Ler, interpretar e produzir textos são habilidades integradas que se desenvolvem juntas.', '[]', 'Verdadeiro', 'Quanto mais lemos e analisamos textos, melhor nos tornamos na produção textual — e vice-versa.'),
('interpretacao', 110, 'B', 'MC', 'Qual é a diferença entre inferir e deduzir num texto?', '["São idênticos","Inferir usa pistas do texto + conhecimento prévio; deduzir segue estritamente a lógica do texto","Inferir é exclusivo de poemas","Deduzir é exclusivo de textos informativos"]', 'Inferir usa pistas do texto + conhecimento prévio; deduzir segue estritamente a lógica do texto', 'Inferência: pistas + experiência do leitor. Dedução: lógica estrita das informações do texto.'),
('interpretacao', 110, 'B', 'CL', 'Para cada habilidade, cite um exercício prático: leitura literal / leitura inferencial / leitura crítica / produção textual', '[]', 'Literal: responder "o que" e "quem" a partir do texto / Inferencial: "por que o personagem agiu assim?" (não explícito) / Crítica: "qual é a intenção do autor?" / Produção: "escreva um texto sobre X usando o mesmo gênero"', 'As quatro habilidades de leitura-escrita formam um ciclo integrado.'),
('interpretacao', 110, 'B', 'RF', 'Escreva uma dissertação argumentativa completa (introdução + 2 parágrafos de desenvolvimento + conclusão) sobre: "O esporte como ferramenta de inclusão social."', '[]', 'Intro: o esporte vai além da competição e pode ser instrumento poderoso de inclusão. / P2: acesso ao esporte em comunidades vulneráveis gera disciplina, pertencimento e oportunidades (ex.: programas sociais esportivos). / P3: embora infraestrutura seja desafio, o baixo custo de modalidades como futebol e natação facilita a democratização. / Concl.: políticas públicas de esporte + educação = caminho para sociedade mais inclusiva.', 'Dissertação completa de 4 parágrafos sobre tema social.'),
('interpretacao', 110, 'B', 'DS', 'Reflita e responda: qual é a diferença entre ler por obrigação e ler por prazer? Como transformar a leitura obrigatória em mais prazerosa?', '[]', 'Leitura obrigatória: motivação externa, pode gerar resistência / Leitura por prazer: motivação interna, engajamento total. / Como transformar: escolher temas de interesse, ler em ambientes confortáveis, conectar com o universo do leitor, começar com gêneros atraentes (HQ, crônica, aventura).', 'Reflexão sobre leitura e motivação — fundamental para formação de leitores.'),
('interpretacao', 110, 'B', 'MC', 'Por que é importante variar os tipos e gêneros de texto lidos?', '["Para não se cansar de um único tema","Para ampliar o repertório, as estratégias de leitura e a compreensão de diferentes contextos comunicativos","Para ser mais rápido na leitura","Para não precisar de dicionário"]', 'Para ampliar o repertório, as estratégias de leitura e a compreensão de diferentes contextos comunicativos', 'Cada gênero usa recursos diferentes — lê-los todos torna o leitor mais completo.'),
('interpretacao', 110, 'B', 'VF', 'O domínio da leitura e da escrita está diretamente relacionado ao sucesso acadêmico e profissional.', '[]', 'Verdadeiro', 'Pesquisas confirmam: habilidades de leitura e escrita são preditores fortes de desempenho escolar e inserção no mercado de trabalho.'),
('interpretacao', 110, 'B', 'CL', 'Faça uma análise completa do trecho: "Não é a chuva que molha, mas o vento que a carrega." — Tipo de texto, figura de linguagem, significado literal e figurado.', '[]', 'Tipo: sentença aforística (máxima/provérbio) / Figura: metáfora / Literal: o vento transporta a chuva / Figurado: os problemas não surgem por si mesmos — há uma causa maior que os impulsiona', 'Análise completa de texto breve com múltiplas dimensões.'),
('interpretacao', 110, 'B', 'RF', 'Escreva sua própria definição de "boa escrita" em 3-4 frases.', '[]', 'Resposta pessoal — válida se mencionar: clareza + adequação ao propósito/público + coesão + conteúdo relevante. Exemplo: "Boa escrita é aquela que comunica com clareza o que precisa ser dito, no registro adequado ao leitor, com ideias bem desenvolvidas e linguagem que não obstaculiza — mas facilita — a compreensão."', 'Metacognição sobre escrita: o estudante define com suas palavras o que considera qualidade textual.'),
('interpretacao', 110, 'B', 'MC', 'O que é "adequação ao gênero" na produção textual?', '["Usar sempre a mesma estrutura para qualquer texto","Escrever o texto respeitando as convenções do gênero solicitado (forma, linguagem, propósito)","Adicionar muitos adjetivos","Escrever de forma longa e complexa"]', 'Escrever o texto respeitando as convenções do gênero solicitado (forma, linguagem, propósito)', 'Adequação ao gênero: uma carta não é um poema. Cada gênero tem suas regras.');
