-- ============================================================
-- GeraFicha — Módulo 4: Sintaxe e Análise
-- Níveis 80–96 | Séries A e B
-- ============================================================

-- Nível 80A — Orações subordinadas adjetivas
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 80, 'A', 'MC', 'As orações subordinadas adjetivas exercem a função de:', '["sujeito","adjunto adnominal (como adjetivo)","objeto direto","predicativo"]', 'adjunto adnominal (como adjetivo)', 'Adjetivas caracterizam um substantivo da oração principal, como um adjetivo.'),
('sintaxe', 80, 'A', 'CL', 'Identifique a oração adjetiva e o substantivo que ela caracteriza: "O livro [que comprei] é ótimo." / "Conheço o aluno [que tirou nota 10]."', '[]', 'que comprei → livro / que tirou nota 10 → aluno', 'A oração adjetiva se refere a um antecedente (substantivo) na oração principal.'),
('sintaxe', 80, 'A', 'VF', 'O pronome relativo "que" é o mais usado para introduzir orações adjetivas.', '[]', 'Verdadeiro', '"Que" refere-se ao antecedente e introduz a adjetiva: "o livro que li", "a menina que chegou".'),
('sintaxe', 80, 'A', 'RF', 'Identifique o pronome relativo e o antecedente: "A cidade [onde] nasci é linda." / "O dia [em que] chegamos foi emocionante."', '[]', 'onde → cidade / em que → dia', 'Onde, quando, cujo, em que, que são pronomes relativos.'),
('sintaxe', 80, 'A', 'MC', '"Adoro o parque em que brinquei na infância." A oração adjetiva é:', '["Adoro o parque","em que brinquei na infância","na infância","parque"]', 'em que brinquei na infância', '"Em que brinquei na infância" caracteriza/restringe o parque — oração adjetiva restritiva.'),
('sintaxe', 80, 'A', 'DS', 'Explique a diferença entre adjetiva RESTRITIVA e EXPLICATIVA com exemplos.', '[]', 'Restritiva: restringe/identifica o substantivo, sem vírgula — "Os alunos que estudaram passaram." (só os que estudaram) / Explicativa: acrescenta informação, com vírgula — "Os alunos, que estudaram muito, passaram." (todos estudaram)', 'A presença ou ausência de vírgulas muda o sentido da adjetiva.'),
('sintaxe', 80, 'A', 'VF', '"O atleta, que correu 10 km, está cansado" — a adjetiva é explicativa (tem vírgulas).', '[]', 'Verdadeiro', 'Vírgulas + oração adjetiva = explicativa. Acrescenta informação não restritiva.'),
('sintaxe', 80, 'A', 'CL', 'Classifique em Restritiva (R) ou Explicativa (E): "O candidato que estudou foi aprovado." / "O candidato, que estudou muito, foi aprovado."', '[]', 'R / E', 'Sem vírgula = restritiva (identifica). Com vírgula = explicativa (acrescenta informação).'),
('sintaxe', 80, 'A', 'MC', 'O pronome relativo "cujo" indica:', '["tempo","lugar","posse","condição"]', 'posse', '"Cujo" = de quem / do qual — indica posse: "O aluno cujo livro sumiu..." = o livro desse aluno.'),
('sintaxe', 80, 'A', 'DS', 'Escreva 2 orações adjetivas restritivas e 2 explicativas.', '[]', 'Restritivas: "As pessoas que trabalham duro merecem sucesso." / "O livro que li me inspirou." / Explicativas: "Minha mãe, que é médica, chegou cedo." / "O Rio de Janeiro, que é lindo, recebe muitos turistas."', 'Restritivas identificam; explicativas informam.'),

-- Nível 80B — Orações subordinadas adjetivas
('sintaxe', 80, 'B', 'VF', 'A adjetiva restritiva não pode ser removida sem alterar o sentido da frase.', '[]', 'Verdadeiro', '"Aprovei os alunos que estudaram." — se remover a restritiva, o sentido muda: "Aprovei os alunos" (todos).'),
('sintaxe', 80, 'B', 'MC', 'Qual pronome relativo pode ser substituído por "onde" em sentido figurado?', '["cujo","que","em que / onde","quem"]', 'em que / onde', '"O país em que / onde vivo" — onde e em que são equivalentes para lugar.'),
('sintaxe', 80, 'B', 'CL', 'Substitua "cujo" pela construção equivalente: "O aluno cujo caderno sumiu ficou triste."', '[]', 'O aluno de quem o caderno sumiu / O aluno do qual o caderno sumiu ficou triste.', '"Cujo" = de quem / do qual — indica posse.'),
('sintaxe', 80, 'B', 'RF', 'Una as duas frases com pronome relativo: "Comprei um livro." + "O livro é interessante." → "Comprei um livro [___] é interessante."', '[]', 'Comprei um livro que é interessante.', '"Que" retoma "livro" e introduz a oração adjetiva.'),
('sintaxe', 80, 'B', 'DS', 'Analise a oração adjetiva: "Os professores, aos quais devemos respeito, merecem valorização."', '[]', '"Aos quais devemos respeito" = oração adjetiva explicativa / pronome relativo: aos quais (= a eles, os professores) / antecedente: professores', 'Análise completa de uma adjetiva com pronome relativo composto.'),
('sintaxe', 80, 'B', 'MC', '"A menina de quem gosto chegou." O pronome relativo "quem" tem como antecedente:', '["gosto","de quem","a menina","chegou"]', 'a menina', '"Quem" retoma "a menina" — antecedente é sempre o substantivo a que o relativo se refere.'),
('sintaxe', 80, 'B', 'VF', 'O pronome "quem" como relativo só se refere a pessoas.', '[]', 'Verdadeiro', '"Quem" refere-se apenas a antecedentes com traço [+humano]: "a criança de quem cuido".'),
('sintaxe', 80, 'B', 'CL', 'Identifique o tipo (restritiva ou explicativa) e o antecedente: "Todos os alunos que chegaram tarde perderam a chamada." / "O diretor, que sempre chega cedo, abriu a escola."', '[]', 'restritiva / antecedente: alunos — explicativa / antecedente: diretor', 'Restritiva identifica quais alunos; explicativa acrescenta info sobre o diretor.'),
('sintaxe', 80, 'B', 'RF', 'Reescreva transformando a adjetiva restritiva em explicativa e note a mudança de sentido: "Os candidatos que se prepararam foram aprovados."', '[]', '"Os candidatos, que se prepararam, foram aprovados." — Agora indica que TODOS se prepararam (e todos foram aprovados).', 'A vírgula muda o sentido: de "apenas os que se prepararam" para "todos (que por sinal se prepararam)".'),
('sintaxe', 80, 'B', 'MC', 'Qual oração NÃO é adjetiva (relativa)?', '["O homem que trabalha merece.","A casa onde moro é antiga.","Sei que você virá.","O livro cujo autor conheço."]', 'Sei que você virá.', '"Sei que você virá" — "que" é conjunção integrante de uma subordinada substantiva (OD), não adjetiva.');

-- Nível 81A — Análise sintática de período simples
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 81, 'A', 'MC', 'Na análise sintática de período simples, identificamos:', '["sujeito e predicado e seus termos","apenas o verbo","apenas o sujeito","somente as conjunções"]', 'sujeito e predicado e seus termos', 'A análise sintática do período simples identifica: sujeito, predicado, OD, OI, adjuntos, etc.'),
('sintaxe', 81, 'A', 'CL', 'Analise sintaticamente: "O menino estudioso leu o livro rapidamente."', '[]', 'Sujeito: O menino estudioso (núcleo: menino, adj.adnominal: estudioso) / Predicado verbal: leu o livro rapidamente / OD: o livro / adj.adverbial de modo: rapidamente', 'Análise completa de período simples com complemento e adjunto.'),
('sintaxe', 81, 'A', 'VF', 'Toda oração tem obrigatoriamente sujeito e predicado.', '[]', 'Falso', 'Orações sem sujeito existem: "Choveu.", "Faz frio." — têm predicado mas não têm sujeito.'),
('sintaxe', 81, 'A', 'RF', 'Identifique todos os termos sintáticos: "Ela enviou flores ao professor."', '[]', 'Sujeito: Ela / Predicado verbal: enviou flores ao professor / OD: flores / OI: ao professor', 'Verbo bitransitivo com OD e OI.'),
('sintaxe', 81, 'A', 'MC', 'Em "O resultado saiu perfeito", qual é a análise correta?', '["sujeito: o resultado / predicado nominal: saiu perfeito / predicativo: perfeito","sujeito: o resultado / predicado verbal: saiu / adjunto: perfeito","sujeito: perfeito / predicado: o resultado saiu","sujeito oculto / predicado: o resultado saiu perfeito"]', 'sujeito: o resultado / predicado nominal: saiu perfeito / predicativo: perfeito', '"Saiu" = verbo de ligação; "perfeito" = predicativo do sujeito = predicado nominal.'),
('sintaxe', 81, 'A', 'DS', 'Faça a análise sintática completa: "Os jovens alunos chegaram animados ao colégio."', '[]', 'Sujeito: Os jovens alunos (núcleo: alunos; adj.adnom.: jovens) / Predicado verbo-nominal: chegaram animados ao colégio / verbo: chegaram / predicativo do sujeito: animados / adj.adverbial de lugar: ao colégio', 'Predicado verbo-nominal: verbo de ação + predicativo do sujeito.'),
('sintaxe', 81, 'A', 'VF', 'O adjunto adverbial pode ser suprimido sem tornar a frase agramatical.', '[]', 'Verdadeiro', 'Adjuntos adverbiais são termos optativos — a frase permanece gramatical sem eles.'),
('sintaxe', 81, 'A', 'CL', 'Identifique a função de cada termo: "A professora [dedicada] ensinou [gramática] [aos alunos]."', '[]', 'dedicada = adj.adnominal de professora / gramática = OD / aos alunos = OI', 'Análise dos termos do predicado no período simples.'),
('sintaxe', 81, 'A', 'MC', 'Em "Chove muito no inverno", qual é a função de "no inverno"?', '["sujeito","OD","adjunto adverbial de tempo","predicativo"]', 'adjunto adverbial de tempo', '"No inverno" indica quando acontece — adjunto adverbial de tempo.'),
('sintaxe', 81, 'A', 'DS', 'Analise sintaticamente: "Minha mãe preparou um bolo delicioso para mim."', '[]', 'Sujeito: Minha mãe (núcleo: mãe; adj.adnom.: minha) / Pred.verbal: preparou um bolo delicioso para mim / OD: um bolo delicioso (adj.adnom.: delicioso) / OI: para mim', 'Análise de período simples com OD modificado por adjetivo e OI.'),

-- Nível 81B — Análise sintática de período simples
('sintaxe', 81, 'B', 'VF', 'O aposto é um termo que explica ou identifica um substantivo da oração.', '[]', 'Verdadeiro', 'Aposto: "Brasília, capital do Brasil, fica no Centro-Oeste." — "capital do Brasil" é o aposto.'),
('sintaxe', 81, 'B', 'MC', '"Pedro, meu melhor amigo, chegou." O termo "meu melhor amigo" é:', '["sujeito","aposto","predicativo","objeto indireto"]', 'aposto', 'Aposto explica/identifica o substantivo Pedro — aparece entre vírgulas.'),
('sintaxe', 81, 'B', 'CL', 'Identifique o aposto: "O Brasil, país de dimensões continentais, tem uma natureza exuberante." / "Camões, o grande poeta português, escreveu Os Lusíadas."', '[]', 'país de dimensões continentais / o grande poeta português', 'Apostos aparecem geralmente entre vírgulas e explicam o antecedente.'),
('sintaxe', 81, 'B', 'RF', 'Acrescente um aposto à frase: "São Paulo ___ é a maior cidade do Brasil."', '[]', 'São Paulo, metrópole brasileira, é a maior cidade do Brasil.', 'O aposto vem entre vírgulas e identifica/explica São Paulo.'),
('sintaxe', 81, 'B', 'DS', 'Faça a análise sintática completa, incluindo o aposto: "O Rio de Janeiro, a cidade maravilhosa, recebe milhões de turistas."', '[]', 'Sujeito: O Rio de Janeiro (núcleo: Rio de Janeiro; aposto: a cidade maravilhosa) / Pred.verbal: recebe milhões de turistas / OD: milhões de turistas', 'O aposto faz parte do sujeito.'),
('sintaxe', 81, 'B', 'MC', 'O vocativo é usado para:', '["completar o sentido do verbo","chamar ou interpelar alguém","caracterizar o sujeito","substituir o objeto"]', 'chamar ou interpelar alguém', 'Vocativo chama/interpela alguém: "João, venha aqui!" — João é o vocativo.'),
('sintaxe', 81, 'B', 'VF', 'O vocativo não é sujeito nem predicado — é um termo isolado na oração.', '[]', 'Verdadeiro', 'O vocativo é independente sintaticamente — não integra o sujeito nem o predicado.'),
('sintaxe', 81, 'B', 'CL', 'Identifique o vocativo e o aposto: "Amigos, Paulo, nosso líder, chegará amanhã."', '[]', 'Amigos = vocativo / nosso líder = aposto de Paulo', 'Amigos chama as pessoas; nosso líder explica quem é Paulo.'),
('sintaxe', 81, 'B', 'RF', 'Reescreva adicionando um vocativo e um aposto: "A Maria ganhou o prêmio."', '[]', 'Parabéns, Maria, minha querida amiga, você ganhou o prêmio!', 'Parabéns ou qualquer chamamento = vocativo; minha querida amiga = aposto.'),
('sintaxe', 81, 'B', 'MC', '"Ana, professora de português, corrigiu as provas." Qual é a análise correta?', '["Sujeito: Ana / Aposto: professora de português / Pred.verbal: corrigiu as provas / OD: as provas","Sujeito: professora de português / Pred.: Ana corrigiu / OD: as provas","Sujeito: Ana e professora / Pred.: corrigiu","Sujeito: as provas / Pred.: Ana corrigiu"]', 'Sujeito: Ana / Aposto: professora de português / Pred.verbal: corrigiu as provas / OD: as provas', 'Ana = sujeito; professora de português = aposto; corrigiu = verbo; as provas = OD.');

-- Nível 82A — Análise sintática de período composto
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 82, 'A', 'MC', 'A análise sintática de período composto identifica:', '["apenas o sujeito e o predicado","as orações e suas relações (coordenação ou subordinação)","apenas os verbos","somente os complementos verbais"]', 'as orações e suas relações (coordenação ou subordinação)', 'No período composto, identificamos cada oração e como elas se relacionam.'),
('sintaxe', 82, 'A', 'CL', 'Analise o período: "Ela estudou porque queria passar." — Identifique as orações e a relação.', '[]', 'OP: Ela estudou / OS adverbial causal: porque queria passar / Relação: subordinação causal', '"Porque" introduz oração subordinada adverbial causal.'),
('sintaxe', 82, 'A', 'VF', 'Em período composto por coordenação, as orações são independentes entre si.', '[]', 'Verdadeiro', 'Coordenadas têm sentido independente — podem ser separadas sem perder o sentido essencial.'),
('sintaxe', 82, 'A', 'RF', 'Analise o período composto: "Estudei, mas não aprovei." — Classifique as orações.', '[]', 'O1: Estudei (coordenada assindética ou principal) / O2: mas não aprovei (coordenada sindética adversativa)', '"Mas" indica oposição — a 2ª oração é coordenada sindética adversativa.'),
('sintaxe', 82, 'A', 'MC', '"Quando chegou, todos aplaudiram." A oração "quando chegou" é:', '["coordenada aditiva","subordinada adverbial temporal","oração principal","subordinada substantiva"]', 'subordinada adverbial temporal', '"Quando" = conjunção temporal → oração subordinada adverbial temporal.'),
('sintaxe', 82, 'A', 'DS', 'Analise completamente: "Ela sabia que a prova seria difícil, mas estudou mesmo assim."', '[]', 'O1: Ela sabia (principal) / O2: que a prova seria difícil (subord. substantiva OD) / O3: mas estudou mesmo assim (coord. adversativa)', 'Período com coordenação e subordinação combinadas.'),
('sintaxe', 82, 'A', 'VF', 'Um período pode ter orações coordenadas e subordinadas ao mesmo tempo.', '[]', 'Verdadeiro', 'Períodos complexos misturam coordenação e subordinação.'),
('sintaxe', 82, 'A', 'CL', 'Identifique o tipo de cada oração: "Embora fosse difícil (___), ela conseguiu (___) e ficou feliz (___)."', '[]', 'subordinada adverbial concessiva / oração principal / coordenada aditiva', 'Três orações: subordinada adverbial + principal + coordenada.'),
('sintaxe', 82, 'A', 'MC', 'A oração principal de "Espero que você melhore" é:', '["que você melhore","Espero","você melhore","melhore"]', 'Espero', '"Espero" é a oração principal — "que você melhore" é a subordinada (OD).'),
('sintaxe', 82, 'A', 'DS', 'Escreva um período composto com 3 orações: uma principal, uma subordinada e uma coordenada.', '[]', 'Exemplo: "Ela sabia (principal) que seria aprovada (subordinada subst.), e ficou tranquila (coordenada aditiva)."', 'Períodos complexos com diferentes tipos de oração.'),

-- Nível 82B — Análise sintática de período composto
('sintaxe', 82, 'B', 'VF', 'A análise sintática e a análise morfológica se complementam para uma compreensão total da frase.', '[]', 'Verdadeiro', 'Morfologia = classe/flexão de cada palavra. Sintaxe = função de cada palavra/oração.'),
('sintaxe', 82, 'B', 'MC', 'Na análise do período composto, "redução de orações" ocorre quando:', '["uma oração é eliminada","a oração subordinada usa verbo no infinitivo, gerúndio ou particípio","há duas orações principais","não há conjunção"]', 'a oração subordinada usa verbo no infinitivo, gerúndio ou particípio', 'Orações reduzidas têm o verbo nas formas nominais (infinitivo, gerúndio, particípio).'),
('sintaxe', 82, 'B', 'CL', 'Identifique a oração reduzida e desenvolva-a: "Ao chegar, cumprimentou a todos." / "Ela saiu correndo."', '[]', '"Ao chegar" = oração reduzida de infinitivo (temporal) → Quando chegou / "correndo" = oração reduzida de gerúndio (modal) → enquanto corria', 'Orações reduzidas de infinitivo e gerúndio são muito comuns.'),
('sintaxe', 82, 'B', 'RF', 'Desenvolva a oração reduzida: "Sendo aprovada, ela comemorou." → "___ ela comemorou."', '[]', 'Como foi aprovada, ela comemorou. / Depois que foi aprovada, ela comemorou.', '"Sendo" = gerúndio → oração adverbial causal ou temporal desenvolvida.'),
('sintaxe', 82, 'B', 'DS', 'Analise completamente o período: "Tendo estudado muito, ela foi aprovada e ficou emocionada."', '[]', 'O1: Tendo estudado muito (subord. adverbial causal reduzida de particípio/inf.) / O2: ela foi aprovada (principal) / O3: ficou emocionada (coord. aditiva)', 'Período com oração reduzida de gerúndio e coordenação.'),
('sintaxe', 82, 'B', 'MC', '"Para vencer, é preciso treinar." A oração "para vencer" é:', '["coordenada conclusiva","subordinada adverbial final reduzida de infinitivo","oração principal","subordinada substantiva"]', 'subordinada adverbial final reduzida de infinitivo', '"Para + infinitivo" = oração final reduzida.'),
('sintaxe', 82, 'B', 'VF', 'Orações reduzidas de infinitivo podem substituir vários tipos de subordinadas adverbiais.', '[]', 'Verdadeiro', '"Ao estudar" (temporal), "por estudar" (causal), "para estudar" (final) — mesmo infinitivo, diferentes relações.'),
('sintaxe', 82, 'B', 'CL', 'Classifique as orações reduzidas: "Terminadas as provas, saíram." / "Ela entrou rindo." / "Esperava encontrar você."', '[]', 'Particípio reduzida temporal ou condicional / gerúndio modal / infinitivo OD', 'Particípio, gerúndio e infinitivo nas orações reduzidas.'),
('sintaxe', 82, 'B', 'RF', 'Reduza a oração sublinhada para infinitivo ou gerúndio: "Quando chegou, cumprimentou a todos."', '[]', 'Ao chegar, cumprimentou a todos.', '"Quando chegou" (oração temporal) → "Ao chegar" (reduzida de infinitivo).'),
('sintaxe', 82, 'B', 'MC', 'Qual período tem oração SUBORDINADA SUBSTANTIVA?', '["Ela chegou e partiu.","Embora chovesse, fomos.","Sei que você virá.","Quando ele chegar, avise."]', 'Sei que você virá.', '"Que você virá" é OD do verbo "sei" — subordinada substantiva objetiva direta.');

-- Nível 83A — Revisão Sintaxe I (Níveis 73–79)
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('sintaxe', 83, 'A', 'MC', 'Qual é a análise correta de "Os professores prepararam aulas excelentes"?', '["Suj: Os professores / OD: aulas excelentes / Pred verbal","Suj: Os professores / Pred verbal / OD: aulas / adj.adnom: excelentes","Suj: aulas / Pred: Os professores prepararam","Suj: aulas excelentes / Pred: prepararam"]', 'Suj: Os professores / Pred verbal / OD: aulas / adj.adnom: excelentes', 'Aulas = OD; excelentes = adj.adnominal de aulas.'),
('sintaxe', 83, 'A', 'CL', 'Identifique sujeito, verbo, OD e adjunto adverbial: "Ela comprou flores ontem no mercado."', '[]', 'Suj: Ela / Verbo: comprou / OD: flores / Adj.adv de tempo: ontem / Adj.adv de lugar: no mercado', 'Análise de período simples com dois adjuntos adverbiais.'),
('sintaxe', 83, 'A', 'VF', 'Orações subordinadas adverbiais indicam circunstâncias como causa, tempo e condição.', '[]', 'Verdadeiro', 'Adverbiais são equivalentes a adjuntos adverbiais — indicam circunstâncias.'),
('sintaxe', 83, 'A', 'RF', 'Transforme: oração coordenada adversativa → "Estudei. Não passei." → ___ / oração subordinada causal → "Estava cansada. Dormiu cedo." → ___', '[]', 'Estudei, mas não passei. / Dormiu cedo porque estava cansada.', '"Mas" = adversativa; "porque" = causal.'),
('sintaxe', 83, 'A', 'MC', '"Ela sorriu quando me viu." A oração subordinada é:', '["nominal","adverbial temporal","adjetiva","aditiva"]', 'adverbial temporal', '"Quando me viu" indica o tempo em que ela sorriu — adverbial temporal.'),
('sintaxe', 83, 'A', 'DS', 'Analise o período completo: "O aluno, que havia estudado muito, foi aprovado com louvor."', '[]', 'Suj: O aluno (aposto/adjetiva: que havia estudado muito) / Pred verbal: foi aprovado com louvor / adj.adv modo: com louvor / oração adjetiva explicativa: que havia estudado muito', 'Período com oração adjetiva explicativa intercalada.'),
('sintaxe', 83, 'A', 'VF', 'A oração principal é aquela que não depende de nenhuma outra para ter sentido.', '[]', 'Verdadeiro', 'Oração principal tem sentido independente; as subordinadas dependem dela.'),
('sintaxe', 83, 'A', 'CL', 'Classifique cada oração em coordenada ou subordinada: "Embora chovesse, fomos ao parque." / "Ela estudou e passou." / "Sei que ela virá."', '[]', 'subordinada adverbial concessiva + principal / coordenadas aditivas / principal + subordinada substantiva OD', 'Revisão dos tipos de orações e suas relações.'),
('sintaxe', 83, 'A', 'MC', 'Qual conjunção introduz oração subordinada CONDICIONAL?', '["embora","porque","se","quando"]', 'se', '"Se" é a principal conjunção condicional: "Se estudar, passará."'),
('sintaxe', 83, 'A', 'DS', 'Escreva um texto curto (3 frases) usando: 1 período simples, 1 coordenado e 1 com subordinada.', '[]', 'Exemplo: "O dia estava lindo. (simples) O sol brilhava e o vento soprava. (composto coord.) Ela saiu porque queria aproveitar o tempo. (comp. subord.)"', 'Diferentes estruturas de período enriquecem a produção textual.'),

-- Nível 83B — Revisão Sintaxe II (acumulativa)
('sintaxe', 83, 'B', 'VF', 'Um mesmo período pode conter orações coordenadas e subordinadas simultaneamente.', '[]', 'Verdadeiro', 'Ex: "Ela sabia que seria difícil, mas não desistiu." — subordinada + coordenada adversativa.'),
('sintaxe', 83, 'B', 'MC', 'Na frase "Recomendo que você descanse", a oração "que você descanse" é:', '["adjetiva restritiva","adverbial causal","substantiva objetiva direta","coordenada aditiva"]', 'substantiva objetiva direta', '"Que você descanse" é OD do verbo recomendar — subordinada substantiva.'),
('sintaxe', 83, 'B', 'CL', 'Analise o período: "Ela correu, saltou e chegou primeiro."', '[]', 'Três orações coordenadas: O1 "Ela correu" (assindética) / O2 "saltou" (aditiva: e implícito) / O3 "chegou primeiro" (aditiva: e)', 'Três orações com o mesmo sujeito (ela), ligadas por coordenação.'),
('sintaxe', 83, 'B', 'RF', 'Identifique todos os termos: "Minha professora dedicada ensinou gramática aos alunos com paciência."', '[]', 'Suj: Minha professora dedicada / Adj.adnom: dedicada, minha / OD: gramática / OI: aos alunos / Adj.adv modo: com paciência', 'Análise sintática completa de período simples rico em termos.'),
('sintaxe', 83, 'B', 'DS', 'Analise sintaticamente e morfologicamente a palavra "rapidamente" em "Ela estudou rapidamente."', '[]', 'Sintaxe: adjunto adverbial de modo do verbo estudou. / Morfologia: advérbio de modo, invariável, formado por rápida + -mente.', 'Análise dupla: morfológica (classe) + sintática (função).'),
('sintaxe', 83, 'B', 'MC', 'Qual é o sujeito de "Choveu muito ontem"?', '["muito","ontem","choveu","não tem sujeito"]', 'não tem sujeito', '"Chover" é impessoal — não tem sujeito.'),
('sintaxe', 83, 'B', 'VF', 'O complemento nominal completa o sentido de substantivos, adjetivos e advérbios abstratos.', '[]', 'Verdadeiro', '"Necessidade de ajuda" (subst. abstrato + compl.nominal), "capaz de tudo" (adj. + compl.nominal).'),
('sintaxe', 83, 'B', 'CL', 'Identifique o complemento nominal vs. adjunto adnominal: "amor de mãe" / "necessidade de carinho" / "casa de pedra"', '[]', '"amor de mãe" = adj.adnominal (especifica que tipo de amor) / "necessidade de carinho" = compl.nominal (completa o sentido de necessidade) / "casa de pedra" = adj.adnominal (caracteriza a casa)', 'A distinção entre compl.nominal e adj.adnominal depende do sentido.'),
('sintaxe', 83, 'B', 'RF', 'Faça a análise sintática completa: "Os alunos que estudaram foram aprovados ontem."', '[]', 'Suj: Os alunos que estudaram (oração adjetiva restritiva) / Pred verbal: foram aprovados ontem / adj.adv de tempo: ontem', 'Sujeito com oração adjetiva restritiva incorporada.'),
('sintaxe', 83, 'B', 'MC', 'Qual é a diferença entre objeto direto e complemento nominal?', '["OD completa verbo; CN completa subst./adj./adv.","OD usa preposição; CN não usa","OD é sempre pronome; CN não","São a mesma coisa"]', 'OD completa verbo; CN completa subst./adj./adv.', 'OD = complemento de verbo transitivo direto. CN = complemento de nome (substantivo abstrato, adjetivo ou advérbio).');
