-- ============================================================
-- GeraFicha — Módulo 5: Interpretação e Produção de Texto
-- Níveis 97–108 | Séries A e B
-- ============================================================

-- Nível 97A — Tipos de texto: narrativo
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 97, 'A', 'MC', 'O texto narrativo tem como principal característica:', '["apresentar argumentos para defender uma ideia","contar eventos que acontecem num espaço e tempo com personagens","descrever características de seres e objetos","explicar como algo funciona"]', 'contar eventos que acontecem num espaço e tempo com personagens', 'Texto narrativo: há personagens, enredo, tempo, espaço e narrador.'),
('interpretacao', 97, 'A', 'CL', 'Identifique os elementos da narrativa no trecho: "João foi à floresta buscar lenha. Quando chegou, viu um lobo enorme."', '[]', 'Personagem: João / Espaço: floresta / Tempo: implícito (passado) / Enredo: buscar lenha + encontrar o lobo', 'Os elementos essenciais da narrativa estão presentes no trecho.'),
('interpretacao', 97, 'A', 'VF', 'O narrador é quem conta a história — pode ser personagem ou observador externo.', '[]', 'Verdadeiro', 'Narrador em 1ª pessoa = personagem. Narrador em 3ª pessoa = observador externo (onisciente).'),
('interpretacao', 97, 'A', 'RF', 'Identifique o ponto de vista: "Eu estava com medo quando entrei na floresta escura." / "Ela entrou na floresta com medo no coração."', '[]', '"Eu estava..." = narrador em 1ª pessoa (personagem) / "Ela entrou..." = narrador em 3ª pessoa (observador externo)', 'A pessoa verbal indica o ponto de vista do narrador.'),
('interpretacao', 97, 'A', 'MC', 'A SEQUÊNCIA básica de uma narrativa é:', '["introdução, desenvolvimento, conclusão","apresentação, complicação, clímax, desfecho","começo, meio e fim da descrição","tese, argumentos, conclusão"]', 'apresentação, complicação, clímax, desfecho', 'Estrutura narrativa: apresentação (quem/onde/quando) → complicação → clímax (ponto máximo de tensão) → desfecho.'),
('interpretacao', 97, 'A', 'DS', 'Leia e identifique: apresentação, complicação e desfecho no trecho: "Era uma vez uma menina que amava flores. Um dia, uma tempestade destruiu seu jardim. Mas ela replantou tudo e o jardim ficou ainda mais lindo."', '[]', 'Apresentação: menina que amava flores / Complicação: tempestade destruiu o jardim / Desfecho: ela replantou e ficou mais lindo', 'Identificar a estrutura narrativa em texto curto.'),
('interpretacao', 97, 'A', 'VF', 'O clímax é o momento de maior tensão ou emoção da narrativa.', '[]', 'Verdadeiro', 'No clímax, o conflito chega ao ponto máximo: é o momento mais emocionante da história.'),
('interpretacao', 97, 'A', 'CL', 'Classifique os elementos narrativos: "personagem, espaço, tempo, enredo, narrador" — explique cada um brevemente.', '[]', 'Personagem: quem age / Espaço: onde / Tempo: quando / Enredo: o que acontece / Narrador: quem conta', 'Os cinco elementos essenciais da narrativa.'),
('interpretacao', 97, 'A', 'MC', 'Qual gênero textual é narrativo?', '["editorial","receita culinária","conto de fadas","bula de remédio"]', 'conto de fadas', 'Conto de fadas é texto narrativo — tem personagens, enredo, clímax e desfecho.'),
('interpretacao', 97, 'A', 'DS', 'Escreva o início de uma narrativa (3-4 frases), incluindo: personagem, espaço, tempo e complicação.', '[]', 'Exemplo: "Era uma tarde ensolarada quando Pedro, um garoto de 10 anos, encontrou uma carta misteriosa no quintal. A carta não tinha remetente. Seu coração disparou..."', 'Narrativa com personagem + espaço (quintal) + tempo (tarde) + complicação (carta misteriosa).'),

-- Nível 97B — Texto narrativo: análise e produção
('interpretacao', 97, 'B', 'VF', 'O narrador onisciente sabe tudo sobre os personagens, inclusive seus pensamentos.', '[]', 'Verdadeiro', 'Narrador onisciente (3ª pessoa): "Ela sorriu, mas por dentro estava arrasada."'),
('interpretacao', 97, 'B', 'MC', 'O que distingue o narrador-personagem do narrador-observador?', '["O narrador-personagem está dentro da história; o observador é externo","O narrador-personagem usa 3ª pessoa; o observador usa 1ª","Não há diferença real entre eles","O observador conhece os pensamentos; o personagem não"]', 'O narrador-personagem está dentro da história; o observador é externo', 'Personagem = eu vivi; observador = eu conto sobre outro.'),
('interpretacao', 97, 'B', 'CL', 'Identifique o tipo de narrador: "Quando abri a porta, vi algo incrível." / "Ele abriu a porta e ficou surpreso com o que encontrou."', '[]', '"Quando abri..." = 1ª pessoa (personagem) / "Ele abriu..." = 3ª pessoa (observador)', 'A pessoa verbal identifica o tipo de narrador.'),
('interpretacao', 97, 'B', 'RF', 'Reescreva o trecho mudando o ponto de vista: "Eu corri o mais rápido que pude." → ___ (3ª pessoa)', '[]', 'Ela/Ele correu o mais rápido que pôde.', 'Mudança de 1ª para 3ª pessoa do singular.'),
('interpretacao', 97, 'B', 'DS', 'Escreva um parágrafo narrativo com narrador em 3ª pessoa, incluindo diálogo.', '[]', 'Exemplo: "Ana caminhou pelo corredor quando escutou uma voz estranha. — Quem está aí? — ela perguntou. Ninguém respondeu. Ela respirou fundo e continuou andando."', 'Narrativa com narrador externo + diálogo com travessão.'),
('interpretacao', 97, 'B', 'MC', 'Qual recurso narrativo cria SUSPENSE?', '["Descrever detalhadamente o espaço","Revelar o final no começo","Usar reticências e perguntas sem resposta imediata","Usar muitos adjetivos"]', 'Usar reticências e perguntas sem resposta imediata', 'Suspense: "O que estaria atrás daquela porta?..." — reticências e questão sem resposta.'),
('interpretacao', 97, 'B', 'VF', 'O tempo numa narrativa pode ser cronológico (linear) ou não-linear (com flashbacks).', '[]', 'Verdadeiro', 'Narrativas podem avançar no tempo (linear) ou voltar ao passado (flashback) ou ao futuro (flashforward).'),
('interpretacao', 97, 'B', 'CL', 'Identifique se o tempo narrativo é linear ou não-linear: "Ela lembrou da infância enquanto olhava as fotos antigas." / "Acordou, tomou café e foi trabalhar."', '[]', '"Lembrou da infância..." = não-linear (flashback) / "Acordou, tomou..." = linear (cronológico)', 'Flashback = retorno ao passado durante a narrativa atual.'),
('interpretacao', 97, 'B', 'RF', 'Acrescente um flashback ao trecho: "Ela olhou a fotografia antiga e sorriu. ___"', '[]', 'Exemplo: "Ela olhou a fotografia antiga e sorriu. Lembrou do dia em que aquela foto foi tirada — era seu aniversário de 8 anos, e toda a família estava reunida."', 'Flashback: interrompemos o presente para narrar algo do passado.'),
('interpretacao', 97, 'B', 'MC', 'Qual elemento NÃO faz parte de uma narrativa?', '["personagem","tese","enredo","clímax"]', 'tese', 'Tese é elemento argumentativo. Narrativa tem personagem, enredo, clímax, espaço, tempo.');

-- Nível 98A — Texto descritivo
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 98, 'A', 'MC', 'O texto descritivo tem como objetivo principal:', '["contar eventos em sequência","defender uma opinião","apresentar características de pessoas, lugares ou objetos","instruir como fazer algo"]', 'apresentar características de pessoas, lugares ou objetos', 'Descrição: pinta com palavras as características de algo — como é, parece, sente, cheira, soa.'),
('interpretacao', 98, 'A', 'CL', 'Identifique se é descritivo (D) ou narrativo (N): "O gato é branco e tem olhos azuis." / "O gato pulou a cerca e fugiu." / "A sala é ampla e iluminada."', '[]', 'D / N / D', 'Descritivo: características estáticas. Narrativo: eventos em sequência.'),
('interpretacao', 98, 'A', 'VF', 'A descrição usa muitos adjetivos e advérbios para criar uma imagem vívida.', '[]', 'Verdadeiro', 'Adjetivos descrevem características; advérbios intensificam: "muito bonito", "extremamente frio".'),
('interpretacao', 98, 'A', 'RF', 'Escreva uma descrição de 3 frases de um lugar que você conhece, usando pelo menos 5 adjetivos.', '[]', 'Exemplo: "A biblioteca é um lugar silencioso e acolhedor. As prateleiras altas e escuras guardam livros novos e antigos. O cheiro de papel e a luz suave criam um ambiente tranquilo."', 'Descrição com adjetivos variados e detalhes sensoriais.'),
('interpretacao', 98, 'A', 'MC', 'Qual recurso NÃO é típico do texto descritivo?', '["adjetivos abundantes","verbos de estado (ser, estar, parecer)","sequência cronológica de eventos","detalhes sensoriais (cor, cheiro, textura)"]', 'sequência cronológica de eventos', 'Sequência cronológica é característica de textos narrativos, não descritivos.'),
('interpretacao', 98, 'A', 'DS', 'Descreva um personagem físico e psicologicamente usando: aparência, personalidade, comportamento.', '[]', 'Exemplo: "Ana é uma mulher alta e de cabelos castanhos. Tem um sorriso caloroso que conquista a todos. É determinada e trabalha com afinco para alcançar seus sonhos."', 'Descrição completa: física (aparência) + psicológica (personalidade) + comportamental.'),
('interpretacao', 98, 'A', 'VF', 'Textos descritivos podem aparecer dentro de narrativas (ex.: descrever o cenário).', '[]', 'Verdadeiro', 'Narrativas geralmente intercalam descrições de personagens e ambientes.'),
('interpretacao', 98, 'A', 'CL', 'Classifique os detalhes como sensoriais: "pele macia" (tato), "aroma de café" (olfato), "luz amarela" (visão), "sabor azedo" (paladar), "som grave" (audição).', '[]', 'pele macia = tato / aroma de café = olfato / luz amarela = visão / sabor azedo = paladar / som grave = audição', 'Descrições sensoriais ativam os cinco sentidos do leitor.'),
('interpretacao', 98, 'A', 'MC', 'Qual frase é tipicamente descritiva?', '["Ela correu até a escola.","O jardim estava florido, com rosas vermelhas e jasmins brancos.","Quando chegou, todos aplaudiram.","Precisa-se de funcionários."]', 'O jardim estava florido, com rosas vermelhas e jasmins brancos.', 'Adjetivos (florido, vermelhas, brancos) + detalhes visuais = texto descritivo.'),
('interpretacao', 98, 'A', 'DS', 'Escreva um parágrafo descritivo de uma manhã de inverno, usando os 5 sentidos.', '[]', 'Exemplo: "A manhã de inverno chegou fria e silenciosa. O ar gelado queimava a pele exposta (tato). O cheiro de café quente vinha da cozinha (olfato). Pelas janelas, a luz branca e pálida entrava timidamente (visão). Os pássaros trinavam baixinho (audição). O gole de chocolate quente aqueceu a garganta (paladar)."', 'Descrição multissensorial cria uma cena vívida para o leitor.'),

-- Nível 98B — Texto descritivo: análise e produção
('interpretacao', 98, 'B', 'VF', 'A ordem dos detalhes na descrição pode seguir um caminho lógico: do geral para o específico.', '[]', 'Verdadeiro', 'Ex: "A cidade → o bairro → a rua → a casa → a sala" — progressão do geral ao específico.'),
('interpretacao', 98, 'B', 'MC', 'Uma descrição objetiva difere de uma subjetiva porque:', '["a objetiva usa adjetivos; a subjetiva não","a objetiva descreve fatos verificáveis; a subjetiva inclui impressões pessoais","a objetiva é mais longa; a subjetiva é mais curta","são a mesma coisa"]', 'a objetiva descreve fatos verificáveis; a subjetiva inclui impressões pessoais', 'Objetiva: "O prédio tem 20 andares." / Subjetiva: "O prédio é imponente e me impressiona."'),
('interpretacao', 98, 'B', 'CL', 'Classifique como Objetiva (O) ou Subjetiva (S): "A sala mede 20m²." / "A sala parece enorme e acolhedora." / "O livro tem 300 páginas." / "O livro é fascinante."', '[]', 'O / S / O / S', 'Dados mensuráveis = objetiva. Impressões/sentimentos = subjetiva.'),
('interpretacao', 98, 'B', 'RF', 'Reescreva a descrição objetiva de forma subjetiva: "O cachorro é de cor marrom, pesa 10 kg e tem olhos castanhos."', '[]', 'Exemplo: "O cachorro marrom é um fofo irresistível, com um olhar tão caloroso que derrete qualquer coração."', 'Subjetiva: impressões, emoções, opiniões do observador.'),
('interpretacao', 98, 'B', 'DS', 'Descreva a mesma pessoa de duas formas: uma objetiva e uma subjetiva.', '[]', 'Objetiva: "João tem 1,75m, cabelos pretos e olhos escuros." / Subjetiva: "João é imponente, com um olhar profundo e misterioso que intriga quem o conhece."', 'As duas formas de descrição coexistem em textos.'),
('interpretacao', 98, 'B', 'MC', 'Qual recurso cria uma imagem mais vívida na descrição?', '["verbos de ação","figuras de linguagem como comparação e metáfora","numerais e estatísticas","conjunções adversativas"]', 'figuras de linguagem como comparação e metáfora', '"Olhos azuis como o mar" (comparação) / "Seus olhos eram oceanos" (metáfora) — imagens mais vivas.'),
('interpretacao', 98, 'B', 'VF', 'A comparação (símile) usa "como" ou "tal qual" para criar imagens descritivas.', '[]', 'Verdadeiro', '"Mãos suaves como seda" — comparação com "como".'),
('interpretacao', 98, 'B', 'CL', 'Identifique a figura de linguagem: "Seu sorriso era um sol." / "Ela caminhava como uma rainha." / "O vento uivava nas montanhas."', '[]', 'metáfora / comparação (símile) / personificação', 'Metáfora = identificação direta; comparação = com "como"; personificação = atributo humano a algo inanimado.'),
('interpretacao', 98, 'B', 'RF', 'Melhore a descrição com pelo menos uma figura de linguagem: "O dia estava quente. O sol estava forte."', '[]', 'Exemplo: "O dia abrasador parecia um forno em chamas. O sol, como uma bola de fogo, derramava luz impiedosa."', 'Figuras de linguagem enriquecem e tornam a descrição mais expressiva.'),
('interpretacao', 98, 'B', 'MC', 'Qual tipo de texto usa a descrição de forma mais intensa?', '["receita culinária","notícia jornalística","guia turístico","artigo científico"]', 'guia turístico', 'Guias turísticos usam descrição de lugares e paisagens para atrair e informar o leitor.');

-- Nível 99A — Texto argumentativo
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 99, 'A', 'MC', 'O texto argumentativo tem como objetivo:', '["narrar eventos","descrever lugares","defender um ponto de vista com argumentos","instruir como fazer algo"]', 'defender um ponto de vista com argumentos', 'Argumentativo: tese (opinião) + argumentos (provas) + conclusão.'),
('interpretacao', 99, 'A', 'CL', 'Identifique tese, argumento e conclusão: "A leitura é fundamental. (___) Ela amplia o vocabulário e desenvolve o raciocínio. (___) Portanto, devemos ler mais. (___)"', '[]', 'tese / argumento / conclusão', 'Estrutura básica do texto argumentativo.'),
('interpretacao', 99, 'A', 'VF', 'Num texto argumentativo, o autor usa linguagem impessoal e formal para ser mais convincente.', '[]', 'Verdadeiro', 'Linguagem formal e impessoal transmite credibilidade e objetividade na argumentação.'),
('interpretacao', 99, 'A', 'RF', 'Escreva uma tese e dois argumentos sobre: "A prática de esportes é importante para crianças."', '[]', 'Tese: A prática de esportes é fundamental para o desenvolvimento das crianças. / Argumento 1: O esporte melhora a saúde física e combate a obesidade infantil. / Argumento 2: Além disso, desenvolve disciplina, trabalho em equipe e superação.', 'Tese + 2 argumentos = base do parágrafo argumentativo.'),
('interpretacao', 99, 'A', 'MC', 'Qual conector é tipicamente argumentativo (indica conclusão)?', '["ou","quando","portanto","enquanto"]', 'portanto', '"Portanto", "logo", "assim", "por isso" são conectivos conclusivos, comuns em argumentação.'),
('interpretacao', 99, 'A', 'DS', 'Escreva um parágrafo argumentativo completo: tese + 2 argumentos + conclusão (tema: uso de celular na escola).', '[]', 'Exemplo: "O uso do celular na escola deve ser regulamentado. Por um lado, o dispositivo pode distrair os alunos durante as aulas. Por outro, usado com responsabilidade, é uma ferramenta educacional valiosa. Portanto, escolas devem criar políticas de uso consciente, em vez de simplesmente proibir."', 'Tese + argumento + contra-argumento + conclusão equilibrada.'),
('interpretacao', 99, 'A', 'VF', 'A argumentação eficaz reconhece o ponto de vista contrário e o refuta.', '[]', 'Verdadeiro', 'Concessão + refutação: "Embora alguns digam que X, na verdade Y..." — argumento mais sofisticado.'),
('interpretacao', 99, 'A', 'CL', 'Classifique o tipo de argumento: "Segundo pesquisa da USP, 70% dos leitores têm melhor desempenho escolar." / "Imagine um mundo sem livros — como seria empobrecido!"', '[]', 'argumento de autoridade (dado estatístico) / argumento emocional/apelo ao leitor', 'Tipos de argumentos: autoridade, causa/consequência, exemplificação, emocional.'),
('interpretacao', 99, 'A', 'MC', 'Qual gênero textual é predominantemente argumentativo?', '["conto","receita","editorial de jornal","poema lírico"]', 'editorial de jornal', 'Editorial expressa a opinião do jornal sobre um tema — texto argumentativo por excelência.'),
('interpretacao', 99, 'A', 'DS', 'Identifique 3 tipos de argumentos usados e exemplifique cada um.', '[]', 'Autoridade: "Segundo estudos científicos..." / Exemplificação: "Por exemplo, em países nórdicos..." / Causa-consequência: "Se não cuidarmos do meio ambiente, sofreremos as consequências..."', 'Variar os tipos de argumento torna o texto mais convincente.'),

-- Nível 99B — Texto argumentativo: análise e produção
('interpretacao', 99, 'B', 'VF', 'A dissertação escolar é um tipo de texto argumentativo com estrutura fixa: introdução, desenvolvimento e conclusão.', '[]', 'Verdadeiro', 'Dissertação: introdução (tese) → parágrafos de desenvolvimento (argumentos) → conclusão.'),
('interpretacao', 99, 'B', 'MC', 'Qual elemento é INDISPENSÁVEL no texto argumentativo?', '["personagem","tese (ponto de vista)","narrador","descrição do ambiente"]', 'tese (ponto de vista)', 'Sem tese (posição do autor), não há argumentação — é o elemento central.'),
('interpretacao', 99, 'B', 'CL', 'Identifique o elemento argumentativo: "Embora seja difícil (___), estudar vale a pena (___), pois garante melhores oportunidades de vida (____)."', '[]', 'concessão / tese / argumento causal', 'Concessão (reconhece o contra-argumento) → tese → argumento.'),
('interpretacao', 99, 'B', 'RF', 'Escreva a conclusão de um texto argumentativo sobre "preservação do meio ambiente".', '[]', 'Exemplo: "Portanto, preservar o meio ambiente não é apenas responsabilidade dos governos, mas um compromisso de toda a sociedade. Cada pequena ação — reduzir plástico, economizar água, plantar árvores — contribui para o futuro do planeta."', 'Conclusão: retoma a tese + proposta de ação.'),
('interpretacao', 99, 'B', 'DS', 'Analise o texto: identifique tese, argumentos e conclusão: "As redes sociais são prejudiciais à saúde mental dos jovens. Estudos mostram aumento de ansiedade e depressão associados ao uso excessivo. Além disso, o cyberbullying é um problema crescente. Devemos, portanto, regular o acesso de menores às plataformas digitais."', '[]', 'Tese: redes sociais prejudicam saúde mental / Arg.1: estudos mostram ansiedade e depressão / Arg.2: cyberbullying crescente / Conclusão: regular acesso de menores', 'Identificação clara da estrutura argumentativa.'),
('interpretacao', 99, 'B', 'MC', 'A concessão no texto argumentativo serve para:', '["enfraquecer a própria tese","mostrar que o autor conhece o ponto de vista contrário e rebatê-lo","introduzir um novo personagem","descrever o cenário"]', 'mostrar que o autor conhece o ponto de vista contrário e rebatê-lo', 'Concessão + refutação: "É verdade que X, mas isso não significa Y..." — estratégia eficaz.'),
('interpretacao', 99, 'B', 'VF', 'Dados estatísticos e citações de especialistas fortalecem a argumentação.', '[]', 'Verdadeiro', 'Argumentos de autoridade (especialistas, pesquisas) dão credibilidade ao texto.'),
('interpretacao', 99, 'B', 'CL', 'Classifique como argumento forte (AF) ou fraco (Fr): "Segundo o IBGE, 45% das crianças não têm acesso à internet." / "Todo mundo sabe que a escola é importante." / "Pesquisas da OMS confirmam que o exercício físico reduz o risco de doenças."', '[]', 'AF (dado estatístico concreto) / Fr (generalização vaga "todo mundo") / AF (autoridade científica)', '"Todo mundo sabe" é argumento fraco — vago e sem comprovação.'),
('interpretacao', 99, 'B', 'RF', 'Melhore o argumento fraco: "Todo mundo acha que ler faz bem." → ___', '[]', 'Exemplo: "Segundo pesquisa publicada pela Universidade de Sussex, apenas 6 minutos de leitura são suficientes para reduzir o estresse em 68%."', 'Substituir opinião genérica por dado concreto e verificável.'),
('interpretacao', 99, 'B', 'MC', 'Qual conector indica CONCESSÃO no texto argumentativo?', '["portanto","embora / ainda que","porque","mas também"]', 'embora / ainda que', '"Embora" e "ainda que" introduzem concessão: "Embora seja difícil, é possível."');

-- Nível 100A — Texto informativo e injuntivo
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 100, 'A', 'MC', 'O texto informativo tem como objetivo:', '["convencer o leitor de uma ideia","transmitir informações de forma clara e objetiva","narrar uma história","descrever sentimentos"]', 'transmitir informações de forma clara e objetiva', 'Informativo: notícias, artigos, enciclopédias, relatórios — focam em informar.'),
('interpretacao', 100, 'A', 'CL', 'Classifique em Informativo (I) ou Injuntivo (INJ): "Bata os ovos e acrescente o leite." / "O Brasil tem 214 milhões de habitantes." / "Misture a farinha com o açúcar."', '[]', 'INJ / I / INJ', 'Injuntivo usa verbos no imperativo (bata, misture) — instrução/ordem. Informativo transmite dados.'),
('interpretacao', 100, 'A', 'VF', 'O texto injuntivo usa verbos no imperativo ou infinitivo para dar instruções.', '[]', 'Verdadeiro', 'Receitas, manuais, bulas, instruções — todos usam imperativo (bata, misture) ou infinitivo (bater, misturar).'),
('interpretacao', 100, 'A', 'RF', 'Identifique o tipo de texto e justifique: "Lava-mãos: Molhe as mãos. Aplique o sabão. Esfregue por 20 segundos. Enxágue. Seque."', '[]', 'Injuntivo — instrução de como realizar um procedimento, com verbos no imperativo.', 'Instrução passo a passo com verbos imperativos = injuntivo.'),
('interpretacao', 100, 'A', 'MC', 'Qual gênero é INJUNTIVO?', '["editorial","conto","manual de instrução","poema"]', 'manual de instrução', 'Manuais, receitas, bulas e tutoriais são textos injuntivos.'),
('interpretacao', 100, 'A', 'DS', 'Escreva um texto injuntivo curto: como fazer um suco de laranja (5 passos).', '[]', '1. Lave as laranjas. 2. Corte-as ao meio. 3. Esprema o suco. 4. Coe para retirar as sementes. 5. Adicione água e açúcar a gosto.', 'Texto injuntivo com verbos no imperativo e sequência lógica.'),
('interpretacao', 100, 'A', 'VF', 'Notícias jornalísticas são textos informativos que respondem: O quê? Quem? Quando? Onde? Por quê? Como?', '[]', 'Verdadeiro', 'As 6 perguntas do lead jornalístico estruturam o texto informativo da notícia.'),
('interpretacao', 100, 'A', 'CL', 'Identifique o tipo: Bula de remédio (___) / Artigo de enciclopédia (___) / Receita culinária (___) / Notícia (___)', '[]', 'injuntivo / informativo / injuntivo / informativo', 'Bulas e receitas = injuntivos. Enciclopédia e notícia = informativos.'),
('interpretacao', 100, 'A', 'MC', 'O que caracteriza o texto informativo?', '["uso de verbos no imperativo","predominância de adjetivos","objetividade, impessoalidade e dados verificáveis","presença de personagens e enredo"]', 'objetividade, impessoalidade e dados verificáveis', 'Informativo: sem opinião pessoal, com dados e fatos verificáveis.'),
('interpretacao', 100, 'A', 'DS', 'Analise uma notícia curta e responda: O quê? Quem? Quando? Onde? Por quê? "O Ministério da Saúde anunciou ontem, em Brasília, nova campanha de vacinação contra a gripe para imunizar a população."', '[]', 'O quê: nova campanha de vacinação / Quem: Ministério da Saúde / Quando: ontem / Onde: Brasília / Por quê: imunizar a população / Como: implícito (campanha)', 'As 6 perguntas do lead respondem ao essencial da notícia.'),

-- Nível 100B — Gêneros textuais: diversidade e função
('interpretacao', 100, 'B', 'MC', 'Gênero textual é:', '["a classe gramatical de um texto","a forma social de uso da linguagem com características relativamente estáveis","o tipo narrativo ou descritivo","apenas a forma do texto"]', 'a forma social de uso da linguagem com características relativamente estáveis', 'Gêneros: carta, e-mail, receita, notícia, poema — cada um com características próprias.'),
('interpretacao', 100, 'B', 'VF', 'E-mail, carta, WhatsApp e bilhete são gêneros diferentes mas todos servem para comunicação pessoal.', '[]', 'Verdadeiro', 'Mesma função social (comunicar), mas em suportes e contextos diferentes.'),
('interpretacao', 100, 'B', 'CL', 'Associe gênero → tipo de texto: Conto (___) / Notícia (___) / Receita (___) / Poema lírico (__)', '[]', 'Narrativo / Informativo / Injuntivo / Lírico/poético', 'Cada gênero pertence a um tipo de texto predominante.'),
('interpretacao', 100, 'B', 'RF', 'Escreva um bilhete de 3 linhas para alguém da família explicando que você saiu e onde está.', '[]', 'Exemplo: "Mãe, fui à casa do Pedro estudar para a prova de matemática. Volto às 18h. Beijos, [nome]."', 'Bilhete: linguagem informal, breve, direto ao ponto.'),
('interpretacao', 100, 'B', 'DS', 'Compare: carta formal vs. carta informal — 3 diferenças na linguagem e estrutura.', '[]', '1. Formal: linguagem culta, informal: linguagem coloquial / 2. Formal: tratamento "Excelentíssimo/Prezado", informal: "Oi, querido" / 3. Formal: estrutura rígida (data, destinatário, fecho), informal: mais livre', 'Contexto social define o registro linguístico adequado.'),
('interpretacao', 100, 'B', 'MC', 'Qual gênero usa linguagem técnica e impessoal por natureza?', '["conversa informal","bula de remédio","conto popular","bilhete"]', 'bula de remédio', 'Bula: linguagem técnica, impessoal, verbos no imperativo — injuntivo e informativo.'),
('interpretacao', 100, 'B', 'VF', 'Cada gênero textual tem uma função social específica.', '[]', 'Verdadeiro', 'Notícia = informar; poema = expressar sentimento; receita = instruir; editorial = opinar.'),
('interpretacao', 100, 'B', 'CL', 'Identifique a função social de cada gênero: decreto / propaganda / crônica / verbete de dicionário', '[]', 'decreto = regulamentar / propaganda = persuadir/vender / crônica = entreter e refletir / verbete = definir/informar', 'A função social determina as características linguísticas do gênero.'),
('interpretacao', 100, 'B', 'RF', 'Escreva o início de um e-mail formal pedindo informações sobre uma vaga de emprego.', '[]', 'Exemplo: "Prezado(a) Senhor(a), Escrevo para solicitar informações sobre a vaga de assistente de comunicação publicada em vosso site. Tenho formação em..." ', 'E-mail formal: saudação respeitosa, linguagem culta, objetivo claro.'),
('interpretacao', 100, 'B', 'MC', 'Qual gênero mistura narração e reflexão sobre o cotidiano, geralmente publicado em jornal?', '["conto","crônica","reportagem","editorial"]', 'crônica', 'Crônica: texto curto, a partir de fato cotidiano, com reflexão e frequentemente humor.');

-- Nível 101A — Interpretação de texto: leitura e compreensão
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 101, 'A', 'MC', 'Interpretar um texto significa:', '["ler rapidamente sem se preocupar com o sentido","compreender o que está escrito e inferir o que não está explícito","copiar o texto para memorizar","apenas identificar as palavras desconhecidas"]', 'compreender o que está escrito e inferir o que não está explícito', 'Interpretação = compreensão literal + inferências + análise crítica.'),
('interpretacao', 101, 'A', 'CL', 'Classifique a questão como Literal (L) ou Inferencial (I): "O que o personagem fez?" / "Por que o personagem agiu assim?" / "Qual a moral da história?"', '[]', 'L / I / I', 'Literal = o texto diz diretamente. Inferencial = o leitor deduz a partir de pistas.'),
('interpretacao', 101, 'A', 'VF', 'A leitura inferencial exige que o leitor complete o texto com seus conhecimentos e a lógica do contexto.', '[]', 'Verdadeiro', 'Inferências: usar pistas do texto + conhecimento prévio para concluir algo não explicitado.'),
('interpretacao', 101, 'A', 'RF', 'Leia e responda literalmente: "Ana comprou maçãs, peras e laranjas na feira." — O que Ana comprou?', '[]', 'Ana comprou maçãs, peras e laranjas.', 'Questão literal: a resposta está explícita no texto.'),
('interpretacao', 101, 'A', 'MC', 'Qual estratégia de leitura ajuda a ANTECIPAR o conteúdo de um texto?', '["ler apenas o final","observar título, imagens e subtítulos antes de ler","ler uma única vez rapidamente","ignorar palavras desconhecidas"]', 'observar título, imagens e subtítulos antes de ler', 'Pré-leitura: título, imagens, subtítulos ativam o conhecimento prévio e facilitam a compreensão.'),
('interpretacao', 101, 'A', 'DS', 'Leia e faça uma inferência: "Quando Paulo chegou em casa, viu que a luz estava apagada e o prato de comida estava cheio na mesa." — O que podemos inferir?', '[]', 'Inferências possíveis: Paulo chegou depois que todos foram dormir / ninguém estava esperando por ele / algo aconteceu que fez a família não jantar', 'O texto não diz explicitamente, mas as pistas permitem inferir.'),
('interpretacao', 101, 'A', 'VF', 'O contexto de uma palavra desconhecida muitas vezes ajuda a descobrir seu significado.', '[]', 'Verdadeiro', '"O menino era furtivo — movia-se sem fazer barulho." → furtivo = silencioso/escondido (pelo contexto).'),
('interpretacao', 101, 'A', 'CL', 'Leia o trecho: "O sol começou a se pôr e as nuvens ficaram cor de laranja." — Identifique: o que está explícito e o que pode ser inferido.', '[]', 'Explícito: o sol está se pondo, as nuvens ficaram cor de laranja / Inferência: é o fim da tarde; pode ser um momento belo/tranquilo', 'Distinguir informação explícita de informação inferida.'),
('interpretacao', 101, 'A', 'MC', 'Qual estratégia ajuda a identificar a ideia principal de um parágrafo?', '["Ler somente a última frase","Identificar a palavra mais longa","Identificar a frase que resume o conteúdo do parágrafo (tópico frasal)","Contar as palavras do parágrafo"]', 'Identificar a frase que resume o conteúdo do parágrafo (tópico frasal)', 'Tópico frasal: frase principal do parágrafo, geralmente no início ou no fim.'),
('interpretacao', 101, 'A', 'DS', 'Escreva 3 estratégias de leitura que um bom leitor usa antes, durante e após a leitura.', '[]', 'Antes: observar título e imagens / prever o tema. Durante: sublinhar ideias importantes / fazer anotações / contextualizar palavras desconhecidas. Após: resumir com as próprias palavras / refletir sobre o que aprendeu.', 'Leitor ativo usa estratégias nas três fases da leitura.'),

-- Nível 101B — Interpretação de texto: análise crítica
('interpretacao', 101, 'B', 'VF', 'A leitura crítica vai além da compreensão — questiona as intenções e valores do texto.', '[]', 'Verdadeiro', 'Leitura crítica: "Para quem este texto foi escrito? Com que intenção? Que valores transmite?"'),
('interpretacao', 101, 'B', 'MC', 'O que é um texto tendencioso?', '["Um texto muito longo","Um texto que apresenta apenas um ponto de vista de forma parcial","Um texto com muitos adjetivos","Um texto sem argumento"]', 'Um texto que apresenta apenas um ponto de vista de forma parcial', 'Texto tendencioso: omite informações, exagera um lado, manipula o leitor.'),
('interpretacao', 101, 'B', 'CL', 'Analise: "O candidato X é claramente o melhor, pois todo mundo o apoia." — Identifique o problema de argumentação.', '[]', '"Claramente" é opinião sem base / "todo mundo" é generalização falsa / ausência de dados concretos = argumento fraco e tendencioso', 'Texto tendencioso usa generalizações, apelos emocionais e falta de evidências.'),
('interpretacao', 101, 'B', 'RF', 'Releia e identifique o que o autor quis dizer além do que está escrito: "A porta estava fechada, mas a janela continuava aberta."', '[]', 'Metáfora: uma oportunidade ou caminho se fechou, mas outro ainda está disponível. Ou: mesmo que uma alternativa falhe, há outras possibilidades.', 'Sentido figurado: porta/janela como metáforas para oportunidades.'),
('interpretacao', 101, 'B', 'DS', 'Analise criticamente a frase: "Crianças que assistem TV são menos inteligentes." — Quais são os problemas dessa afirmação?', '[]', '1. Generalização excessiva (todas as crianças? qualquer TV?) / 2. Falta de dados / fonte / 3. "Menos inteligentes" é impreciso / 4. Ignora variáveis (tipo de programa, tempo de exposição) / 5. Correlação ≠ causalidade', 'Leitura crítica questiona generalizações, dados e relações de causa-efeito.'),
('interpretacao', 101, 'B', 'MC', 'O que é a "ideia principal" de um texto?', '["A primeira frase do texto","A informação mais importante que o texto quer transmitir","A palavra mais repetida","O título do texto"]', 'A informação mais importante que o texto quer transmitir', 'Ideia principal = o que o texto quer que o leitor saiba, creia ou faça.'),
('interpretacao', 101, 'B', 'VF', 'Em textos argumentativos, identificar falácias ajuda a avaliar a qualidade dos argumentos.', '[]', 'Verdadeiro', 'Falácias: "Ad hominem" (atacar a pessoa), "Homem de palha" (distorcer argumento), "Apelo à maioria" — são argumentos inválidos.'),
('interpretacao', 101, 'B', 'CL', 'Identifique a falácia: "Se você não concorda comigo, está contra todos nós." / "Meu avô fumou a vida toda e viveu até os 90 anos, então fumar não faz mal."', '[]', '"Conosco ou contra nós" = falsa dicotomia / "meu avô..." = generalização a partir de caso único / ambas são falácias', 'Reconhecer falácias é habilidade de leitura crítica.'),
('interpretacao', 101, 'B', 'RF', 'Escreva uma pergunta crítica para cada tipo de texto: narrativo, argumentativo e informativo.', '[]', 'Narrativo: "O narrador é confiável? Que perspectiva está sendo omitida?" / Argumentativo: "Os argumentos têm base em dados? Há viés?" / Informativo: "A fonte é confiável? A informação está desatualizada?"', 'Perguntas críticas adaptadas ao tipo de texto.'),
('interpretacao', 101, 'B', 'MC', 'Qual habilidade é essencial para o leitor crítico?', '["Ler rapidamente sem pausas","Questionar a intenção, a fonte e os argumentos do texto","Aceitar tudo que está escrito","Decorar o texto inteiro"]', 'Questionar a intenção, a fonte e os argumentos do texto', 'Leitura crítica: questionar, comparar fontes, avaliar argumentos — não aceitar passivamente.');

-- Nível 102A — Figuras de linguagem
INSERT INTO questions (module, level, series, type, question, options, answer, explanation) VALUES
('interpretacao', 102, 'A', 'MC', 'A metáfora é uma figura de linguagem que:', '["repete um som para criar efeito musical","faz uma comparação usando como ou tal qual","identifica diretamente um termo com outro por semelhança","exagera propositalmente para enfatizar"]', 'identifica diretamente um termo com outro por semelhança', 'Metáfora: "Ela é um anjo." (identifica diretamente, sem "como").'),
('interpretacao', 102, 'A', 'CL', 'Classifique a figura de linguagem: "Sorrindo como o sol" (___) / "Seus olhos eram estrelas" (___) / "Gritou tanto que acordou o bairro todo" (___) / "O vento sussurrou" (___)','[]', 'comparação / metáfora / hipérbole / personificação', 'As quatro figuras mais comuns em textos literários.'),
('interpretacao', 102, 'A', 'VF', 'A hipérbole é um exagero usado para dar ênfase ao que se quer dizer.', '[]', 'Verdadeiro', '"Já te disse um milhão de vezes!" — exagero para enfatizar a repetição.'),
('interpretacao', 102, 'A', 'RF', 'Crie um exemplo de cada figura: metáfora / comparação / hipérbole / personificação', '[]', 'Metáfora: A vida é uma dança. / Comparação: Ela dança como uma borboleta. / Hipérbole: Estou morrendo de fome! / Personificação: A lua me contemplava tristemente.', 'Cada figura cria um efeito expressivo diferente.'),
('interpretacao', 102, 'A', 'MC', '"As pedras cantavam enquanto o rio passava." Que figura de linguagem está presente?', '["metáfora","hipérbole","personificação","eufemismo"]', 'personificação', 'Pedras não cantam — atribuir ação humana a ser inanimado = personificação (ou prosopopeia).'),
('interpretacao', 102, 'A', 'DS', 'Explique o eufemismo e dê 2 exemplos do cotidiano.', '[]', 'Eufemismo: substituição de palavra ou expressão por outra mais suave ou positiva. Ex: "Ele passou desta para melhor" (= morreu) / "Funcionário desligado" (= demitido)', 'Eufemismos suavizam realidades duras ou desagradáveis.'),
('interpretacao', 102, 'A', 'VF', 'A ironia diz o contrário do que se quer expressar — geralmente com humor ou crítica.', '[]', 'Verdadeiro', '"Que bela prova você fez!" (quando a prova foi péssima) — ironia.'),
('interpretacao', 102, 'A', 'CL', 'Identifique a figura: "Ele é uma pedra!" (sobre alguém insensível) / "Estudou, estudou, estudou..." / "O amor é um fogo que arde" / "Uma formiguinha carregou o elefante"', '[]', 'metáfora / repetição (anáfora) / metáfora poética / hipérbole', 'Figuras de linguagem variam em tipo e efeito expressivo.'),
('interpretacao', 102, 'A', 'MC', 'A antítese é a figura que:', '["repete palavras no início de versos","aproxima palavras de sentidos opostos","exagera uma ideia","atribui vida a seres inanimados"]', 'aproxima palavras de sentidos opostos', 'Antítese: "A vida é curta, mas a arte é longa." — oposição entre curta e longa.'),
('interpretacao', 102, 'A', 'DS', 'Identifique e explique as figuras no verso: "A vida é breve, o caminho é comprido, a tentativa difícil, o triunfo incerto."', '[]', 'Antítese: breve × comprido / Paralelismo/gradação: estrutura paralela de quatro elementos. Cada par de conceitos reforça a dificuldade do percurso da vida.', 'Análise de figuras de linguagem em texto literário.'),

-- Nível 102B — Figuras de linguagem avançadas
('interpretacao', 102, 'B', 'VF', 'A aliteração é a repetição de consoantes próximas para criar efeito sonoro.', '[]', 'Verdadeiro', '"O rato roeu a roupa do rei de Roma." — repetição do som R = aliteração.'),
('interpretacao', 102, 'B', 'MC', 'A metonímia é a figura que usa:', '["comparação com "como"","parte pelo todo, causa pelo efeito, continente pelo conteúdo","exagero para enfatizar","oposição de ideias"]', 'parte pelo todo, causa pelo efeito, continente pelo conteúdo', '"Li Machado de Assis." (= li obras de Machado) / "Bebeu um copo." (= bebeu o conteúdo do copo)'),
('interpretacao', 102, 'B', 'CL', 'Identifique o tipo de metonímia: "Preciso de um Shakespeare." / "O Brasil jogou bem." / "Beber um copo."', '[]', 'autor pela obra / continente pelo conteúdo (o Brasil = a seleção) / continente pelo conteúdo (copo = o que está no copo)', 'Metonímia usa associações por contiguidade.'),
('interpretacao', 102, 'B', 'RF', 'Reescreva substituindo a expressão literal pela figura de linguagem: "Ela é muito linda." → ___ (hipérbole) / "Ele é insensível." → ___ (metáfora)', '[]', 'Hipérbole: "Ela é a mulher mais linda do universo!" / Metáfora: "Ele é uma pedra."', 'Figuras de linguagem intensificam a expressão.'),
('interpretacao', 102, 'B', 'DS', 'Analise as figuras em um verso popular: "O sertão vai virar mar, e o mar vai virar sertão." (Patativa do Assaré)', '[]', 'Antítese: sertão × mar / Quiasmo (estrutura cruzada A→B / B→A) / Sentido figurado: mudança radical da realidade / Metáfora de transformação social e climática', 'Análise literária de verso que usa várias figuras.'),
('interpretacao', 102, 'B', 'MC', 'O oxímoro (ou oximoro) é a figura que:', '["repete sons consonantais","une dois conceitos contraditórios numa mesma expressão","exagera uma ideia","usa palavra no sentido contrário"]', 'une dois conceitos contraditórios numa mesma expressão', '"Silêncio ensurdecedor" / "amor e ódio" / "alegre tristeza" — oxímoro.'),
('interpretacao', 102, 'B', 'VF', '"Vai chover canivete!" é um exemplo de hipérbole.', '[]', 'Verdadeiro', '"Vai chover canivete" = vai chover muito — exagero para enfatizar a intensidade.'),
('interpretacao', 102, 'B', 'CL', 'Identifique a figura nos poemas populares: "O sol brilhava com força." / "A saudade me consome." / "Branco por dentro, verde por fora — quem sou eu? Sou a pera."', '[]', 'personificação (o sol "brilhava com força" + literalmente correto) / personificação (saudade que consome) / adivinha com metáfora', 'Figuras aparecem em textos populares e literários.'),
('interpretacao', 102, 'B', 'RF', 'Crie um verso ou frase usando: antítese + hipérbole.', '[]', 'Exemplo: "Sou tão pobre que não tenho nem ar para respirar, mas tão rico em sonhos que poderia comprar o mundo."', 'Combinar figuras enriquece a expressão literária.'),
('interpretacao', 102, 'B', 'MC', 'Qual figura de linguagem é usada em "Vim, vi, venci."?', '["metáfora","gradação (clímax)","hipérbole","personificação"]', 'gradação (clímax)', '"Vim, vi, venci" — gradação ascendente: cada ação supera a anterior em intensidade.');
